### ISSUE TITLE
Home assistant not showing C100

### ISSUE THREAD

**Issue by ady-crow** [JurajNyiri/HomeAssistant-Tapo-Control#114]
**Describe the bug**
no image showing on Picture Entity Card

**To Reproduce**
1. fresh install of Home Assistant
2. added Tapo Camera control
3. Cards auto added to Lovelace page

**Expected behavior**
Expected to see the camera image but not seeing any.

**Log**
If applicable, add error logs.

```
Logger: homeassistant.setup
Source: custom_components/tapo_control/init.py:341
First occurred: 18:08:58 (1 occurrences)
Last logged: 18:08:58

Error during setup of component tapo_control
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/setup.py", line 213, in _async_setup_component
result = await task
File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
result = self.fn(*self.args, **self.kwargs)
File "/config/custom_components/tapo_control/init.py", line 341, in setup
tapoConnector = Tapo(host, username, password)
File "/usr/local/lib/python3.8/site-packages/pytapo/init.py", line 29, in init
self.presets = self.getPresets()
File "/usr/local/lib/python3.8/site-packages/pytapo/init.py", line 430, in getPresets
return self.getPresets(True)
File "/usr/local/lib/python3.8/site-packages/pytapo/init.py", line 427, in getPresets
raise Exception("Error: "+self.getErrorMessage(data['error_code'])+" Response:" + json.dumps(data))
Exception: Error: -1337 Response:{"error": "Not enough pixels!!", "error_code": -1337}
```

**Camera (please complete the following information):**
 - Device Model: C100
 - FW: 1.1.14 Build 210825 Rel. 46648n

**Using stream component**
no

**Camera works through onvif component OR different cameras work in general**
yes

**Camera has all attributes filled out properly in developer tools**
i am not sure what this is about? what else do i need to change?

**HASS Environment**
Running on Windows 10

**Additional context**
[home-assistant.log](https://github.com/JurajNyiri/HomeAssistant-Tapo-Control/files/7313536/home-assistant.log)

**Comment by JurajNyiri** [comment]
```2021-10-08 19:33:47 ERROR (MainThread) [haffmpeg.core] FFmpeg fails [WinError 2] The system cannot find the file specified
Traceback (most recent call last):
  File "C:\Users\Adrian Crowson\AppData\Roaming\.homeassistant\deps\Python39\site-packages\haffmpeg\core.py", line 136, in open
    self._proc = await self._loop.run_in_executor(None, proc_func)
  File "C:\Users\Adrian Crowson\AppData\Local\Programs\Python\Python39\lib\concurrent\futures\thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "C:\Users\Adrian Crowson\AppData\Local\Programs\Python\Python39\lib\subprocess.py", line 951, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Users\Adrian Crowson\AppData\Local\Programs\Python\Python39\lib\subprocess.py", line 1420, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,```

Your Home Assistant install is not correct, you are missing ffmpeg dependency.

**Comment by JurajNyiri** [comment]
https://community.home-assistant.io/t/ffmpeg-camera-under-windows-10/8958
