### ISSUE TITLE
Bug: Error executing script. Unexpected error for call_service at pos 1: Error: -64301 Response:{"error_code": -64301}

### ISSUE THREAD

**Issue by Murder3D** [JurajNyiri/HomeAssistant-Tapo-Control#124]
**Describe the bug**
Whenever I move my Tapo C200 camera to one of the saved positions (presets), the camera moves correctly but I get the following error:

_Error executing script. Unexpected error for call_service at pos 1: Error: -64301 Response:{"error_code": -64301}_

or 

_[546995502288] Error: -64301 Response:{"error_code": -64301}_

**To Reproduce**
1. create a button card which calls the PTZ service to move the device "Tapo C200" to a saved preset location (for example: couch)
2. click the button
3. the camera moves to the correct position
4. the error message is displayed

**Expected behavior**
To make the camera move without getting the error message

**Log**
Log Details (ERROR)
Logger: homeassistant.components.script.tapo_c200_in_posizione_default
Source: custom_components/tapo_control/camera.py:322
Integration: Script (documentation, issues)
First occurred: 4:45:18 PM (1 occurrences)
Last logged: 4:45:18 PM

Tapo C200 in posizione Default: Error executing script. Unexpected error for call_service at pos 1: Error: -64301 Response:{"error_code": -64301}
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 371, in _async_step
    await getattr(self, handler)()
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 571, in _async_call_service_step
    await service_task
  File "/usr/src/homeassistant/homeassistant/core.py", line 1495, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1530, in _execute_service
    await handler.job.target(service_call)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 685, in handle_service
    await service.entity_service_call(
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 667, in entity_service_call
    future.result()  # pop exception if have
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 863, in async_request_call
    await coro
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 704, in _handle_entity_call
    await result
  File "/config/custom_components/tapo_control/camera.py", line 322, in ptz
    await self.hass.async_add_executor_job(
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.9/site-packages/pytapo/__init__.py", line 378, in setPreset
    return self.performRequest(
  File "/usr/local/lib/python3.9/site-packages/pytapo/__init__.py", line 104, in performRequest
    raise Exception(
Exception: Error: -64301 Response:{"error_code": -64301}

**Camera**
Device Model: Tapo C200
FW: 1.1.15 Build 211111 Rel.34670n(4555)

**Using stream component**
No

**Camera works through onvif component OR different cameras work in general**
Yes

**Camera has all attributes filled out properly in developer tools**
Yes

**HASS Environment**
System Health

version: core-2021.11.5
installation_type: Home Assistant OS
dev: false
hassio: true
docker: true
user: root
virtualenv: false
python_version: 3.9.7
os_name: Linux
os_version: 5.10.17-v8
arch: aarch64
timezone: Europe/Rome

HA OS installed on a RPi4 4GB on a 250GB Samsung 870 EVO SSD

**Additional context**
Both my Tapo cameras (C200 and C310) are integrated via ONVIF in HA, and I am using a custom component called WebRTC (https://github.com/AlexxIT/WebRTC) so that I have a high quality video and audio stream without the typical 5 - 7 seconds delay of the standard RTSP stream.

**Comment by Vitalitty** [comment]
Sorry for my late response.

Well as @Murder3D said, I've a button card which calls the PTZ service to move the device "Tapo C200" to a saved preset location. Sometimes it will work without error but sometimes it will trigger an error linked by @Murder3D also. And because of this error some automation will break. Since an error occured, the automation will stop at the breaking point.

**Comment by TitanNano** [comment]
I get this error sometimes if the camera has been restarted. When I reload the integration the error stops occurring.

**Comment by mannipulator** [comment]
Maybe this log can help you, I am facing the same issue


Logger: homeassistant.components.websocket_api.http.connection
Source: custom_components/tapo_control/camera.py:325 
Integration: Home Assistant WebSocket API (documentation, issues) 
First occurred: 23. April 2022, 20:13:40 (6 occurrences) 
Last logged: 10:40:14

[544589237600] Error: -64301 Response:{"error_code": -64301}
[544718685424] Error: -64303 Response:{"error_code": -64303}
[547301871520] Error: Invalid stok value Response:{"error_code": -40401, "result": {"data": {"code": -40407, "encrypt_type": ["1", "2"], "key": "SUPERSECRETKEYWASHERE", "nonce": "PwUaslpO"}}}
[546776322000] Error: Invalid stok value Response:{"error_code": -40401, "result": {"data": {"code": -40407, "encrypt_type": ["1", "2"], "key": SUPERSECRETKEYWASHERE", "nonce": "RCL8tMAB"}}}
[546776322000] Error: -64301 Response:{"error_code": -64301}
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 193, in handle_call_service
    await hass.services.async_call(
  File "/usr/src/homeassistant/homeassistant/core.py", line 1634, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1671, in _execute_service
    await cast(Callable[[ServiceCall], Awaitable[None]], handler.job.target)(
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 692, in handle_service
    await service.entity_service_call(
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 677, in entity_service_call
    future.result()  # pop exception if have
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 955, in async_request_call
    await coro
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 714, in _handle_entity_call
    await result
  File "/config/custom_components/tapo_control/camera.py", line 325, in ptz
    await self.hass.async_add_executor_job(
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.9/site-packages/pytapo/__init__.py", line 421, in setPreset
    return self.performRequest(
  File "/usr/local/lib/python3.9/site-packages/pytapo/__init__.py", line 113, in performRequest
    raise Exception(
Exception: Error: -64301 Response:{"error_code": -64301}

**Comment by vsimanin** [comment]
I also have the same error on my card.  It seemed to me that this was due to the extreme position of the lens.  The error appears if I press the DOWN button, and the camera has nowhere to lower the lens.  Check it.  Error and truth appear quite often.

Card Lovelace WebRTC:
ptz:
  service: tapo_control.ptz
  data_left:
    entity_id: camera.tapo_c200_hd
    pan: LEFT
  data_right:
    entity_id: camera.tapo_c200_hd
    pan: RIGHT
  data_up:
    entity_id: camera.tapo_c200_hd
    tilt: UP
  data_down:
    entity_id: camera.tapo_c200_hd
    tilt: DOWN

**Comment by vsimanin** [comment]
Logger: homeassistant.components.websocket_api.http.connection
Source: custom_components/tapo_control/camera.py:353
Integration: Home Assistant WebSocket API (documentation, issues)
First occurred: 14 июня 2022 г., 21:40:16 (17 occurrences)
Last logged: 14 июня 2022 г., 21:41:49

[2694863912] Error: -64304, Response: {"error_code": -64304}
[2694863912] Error: -64301, Response: {"error_code": -64301}
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 193, in handle_call_service
    await hass.services.async_call(
  File "/usr/src/homeassistant/homeassistant/core.py", line 1704, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1741, in _execute_service
    await cast(Callable[[ServiceCall], Awaitable[None]], handler.job.target)(
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 697, in handle_service
    await service.entity_service_call(
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 680, in entity_service_call
    future.result()  # pop exception if have
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 964, in async_request_call
    await coro
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 717, in _handle_entity_call
    await result
  File "/config/custom_components/tapo_control/camera.py", line 353, in ptz
    await self.hass.async_add_executor_job(
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.9/site-packages/pytapo/__init__.py", line 280, in moveMotor
    return self.performRequest(
  File "/usr/local/lib/python3.9/site-packages/pytapo/__init__.py", line 114, in performRequest
    raise Exception(
Exception: Error: -64304, Response: {"error_code": -64304}

**Comment by JurajNyiri** [comment]
-64304 is an expected response when a limit of PTZ is reached. It could be handled better by showing a nicer message but that is a separate issue.

**Comment by Murder3D** [comment]
Hi,

just wanted to report back on this issue. 
I think that the latest update (4.1.6) and the new way to call for a preset (select.select_option + select.tapo_move_to_preset) solved this issue.

I just updated my buttons with which I call saved preset positions and I am not getting the popup error message and also I am not  getting any error in the logs anymore.
