### ISSUE TITLE
No action for c200

### ISSUE THREAD

**Issue by LeducH** [JurajNyiri/HomeAssistant-Tapo-Control#163]
### Description

There is no action for the c200

### Reproduction Steps

1. Run home assistant in docker 
2. copy the custome_compoents in to the config 
3. add camera as integration
4. add automation to turn on/off private mode camera at defined time  

### Expected behavior

There is an action to set the private field on or off

### If applicable, add error logs.
```
Logger: homeassistant.config_entries
Source: helpers/entity_component.py:157
First occurred: 10:18:55 (1 occurrences)
Last logged: 10:18:55

Error setting up entry Tapo_c200 for binary_sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 335, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/usr/src/homeassistant/homeassistant/components/binary_sensor/__init__.py", line 167, in async_setup_entry
    return await component.async_setup_entry(entry)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 157, in async_setup_entry
    raise ValueError("Config entry has already been setup!")
ValueError: Config entry has already been setup!
```
### Device Firmware

Firmware: 1.1.16 Build 211209

### Using stream component

No

### Does camera work via official integrations?

Yes

### Camera has all attributes filled out in developer tools

Yes

### HASS Environment

Docker in Server

### Search for similar issues

Yes

**Comment by LeducH** [comment]
The action type must be `call service` instead of device
