### ISSUE TITLE
Invalid authentication data with Tapo C210

### ISSUE THREAD

**Issue by s-croot** [JurajNyiri/HomeAssistant-Tapo-Control#164]
### Description

Unable to setup Tapo C210 via method below. Authentication error is returned.

Camera is set up with a camera account and stream is viewable in VLC and through the home assistant integration and motionEye addon with the same user and password.

rtsp://stefan:testpass@192.168.0.34:554/stream1 displays the stream in VLC
also cannot authenticate with pytapo using
tapo = Tapo(host, user, password)
tapo.getbasicinfo()
error as below

### Reproduction Steps

1. Click add integration > Tapo: Cameras Control
2. Enter IP address ('192.168.0.34') for Tapo C210
3. Enter username ('stefan') and password ('testpass') from Camera Account
Error message returned as below.

### Expected behavior

Setup of Tapo C210 device

### If applicable, add error logs.

Errors message from integration GUI:
Invalid authentication data. Make sure you have created your 3rd party account via Tapo app. You can also test if these credentials work via rtsp stream, for example VLC using link rtsp://username:password@IP Address:554/stream1

Error message from pytapo:
Traceback (most recent call last):
  File "C:\Users\Stefan\desktop\taporun.py", line 6, in <module>
    tapo = Tapo(host, user, password)
  File "C:\Users\Stefan\AppData\Roaming\Python\Python39\site-packages\pytapo\__init__.py", line 40, in __init__
    self.basicInfo = self.getBasicInfo()
  File "C:\Users\Stefan\AppData\Roaming\Python\Python39\site-packages\pytapo\__init__.py", line 232, in getBasicInfo
    return self.performRequest(
  File "C:\Users\Stefan\AppData\Roaming\Python\Python39\site-packages\pytapo\__init__.py", line 94, in performRequest
    self.ensureAuthenticated()
  File "C:\Users\Stefan\AppData\Roaming\Python\Python39\site-packages\pytapo\__init__.py", line 60, in ensureAuthenticated
    return self.refreshStok()
  File "C:\Users\Stefan\AppData\Roaming\Python\Python39\site-packages\pytapo\__init__.py", line 79, in refreshStok
    raise Exception("Invalid authentication data")
Exception: Invalid authentication data

### Device Firmware

1.1.13 Build 211209 Rel.21746n(4555)

### Using stream component

No

### Does camera work via official integrations?

Yes

### Camera has all attributes filled out in developer tools

No

### HASS Environment

HAOS in Virtualbox on Ubuntu

### Search for similar issues

Yes

**Comment by RestOp** [comment]
i have c210 and just got it work from the first time. Till now no problems.
Motion detection also works.
I think it can be added to support list

**Comment by JurajNyiri** [comment]
C210 is fully supported. Make sure you are entering correct credentials - the same as for the VLC when viewing RTSP stream.
Try also restarting camera or changing password to something else, maybe it has undocumented issues with special characters or something similar.

**Comment by RestOp** [comment]
Just not in support list

![image](https://user-images.githubusercontent.com/46259141/159185733-54781079-3437-4ef0-82d7-34c016b46244.png)

**Comment by aljer78** [comment]
I still have the same issue after change username, change password even restart camera many time

**Comment by RestOp** [comment]
> I still have the same issue after change username, change password even restart camera many time

Try to reinstall addon and remember that you have to enter cloud password as well for c210.

**Comment by aljer78** [comment]
thanks for the respond @RestOp,  already try reinstalling the addon .  it working fine for few month only recently after i update camera firmware and my DECO M4  (network device) the intergration is not working. Then I delete the device and try add again got this error.

**Comment by RestOp** [comment]
I have read about problems with new firmware, because of it i do not update it!

**Comment by aljer78** [comment]
i think so, but with the new firmware the camera motion tracking is very good. Whent he camera detect motion it will follow the movement until camera out of reach.

**Comment by JurajNyiri** [comment]
I am using latest firmware without any issues on multiple Tapo C200. I cannot replicate this issue so you will need to help me with it.

Please refer to [this](https://community.home-assistant.io/t/use-pan-tilt-function-for-tp-link-tapo-c200-from-home-assistant/170143/18?u=jurajnyiri) post and try to authenticate via postman using the payload and http request detailed in the post. Let me know what response do you get from the camera.

**Comment by RestOp** [comment]
I do not know if it is a bug, but if i **do not enter** (optional) Cloud password i also get an auth error

![image](https://user-images.githubusercontent.com/46259141/160297533-d9992f3d-0465-4dbf-9296-273c17e03a6c.png)

I think that is is a bug, because on c100 and c200 i did not entered cloud password!

**Comment by JurajNyiri** [comment]
@RestOp i hud your commment because its not related to this issue. Please keep discussion on topic.

**Comment by RestOp** [comment]
> @RestOp i hid your commment because its not related to this issue. Everything also works as expected like you described. Please keep discussion on topic.

Really, for few days i have added c210 and works till now fine.
But i still not able to update the settings, the symnptomes are the the same as topic starter described. Do i have to open a new issure?

**Comment by JurajNyiri** [comment]
Camera accepts / can generate a maximum number of auth tokens. Updating settings verifies added data by requesting a new token. This can fail when maximum number of tokens/connections are generated with the same error message as incorrect data.
To update your camera, you need to reduce total number of concurrent connections and reboot it.
If you need more help or think there is something not working, search through closed issues and if you do not find a solution open new issue.

**Comment by JurajNyiri** [comment]
@aljer78 @s-croot 

Please update to [3.4.8](https://github.com/JurajNyiri/HomeAssistant-Tapo-Control/releases/tag/3.4.8) and add following to configuration.yaml:

```
logger:
  default: error
  logs:
    custom_components.tapo_control: debug
```

Restart home assistant and try to add the camera. Please post all the generated logs from this integration. Should look something like:

```
2022-03-27 22:06:25 DEBUG (MainThread) [custom_components.tapo_control] [ADD DEVICE] Setup process for tapo initiated by user.
2022-03-27 22:06:25 DEBUG (MainThread) [custom_components.tapo_control] [ADD DEVICE] Showing config flow for IP.
2022-03-27 22:06:30 DEBUG (MainThread) [custom_components.tapo_control] [ADD DEVICE] Verifying IP address
2022-03-27 22:06:30 DEBUG (MainThread) [custom_components.tapo_control] [ADD DEVICE][192.168.100.70] Verifying port 443.
2022-03-27 22:06:30 DEBUG (MainThread) [custom_components.tapo_control] [ADD DEVICE][192.168.100.70] Port 443 is opened, verifying access to control of camera.
2022-03-27 22:06:31 DEBUG (MainThread) [custom_components.tapo_control] [ADD DEVICE][192.168.100.70] Verifying ports all required camera ports.
2022-03-27 22:06:31 DEBUG (MainThread) [custom_components.tapo_control] [ADD DEVICE][192.168.100.70] All camera ports are opened, proceeding to requesting Camera Account.
...
```

**Comment by aljer78** [comment]
@JurajNyiri Thanks for the response.  Below is the logs a requested.

2022-03-28 20:55:48 DEBUG (MainThread) [custom_components.tapo_control] [ADD DEVICE] Verifying IP address
2022-03-28 20:55:48 DEBUG (MainThread) [custom_components.tapo_control] [ADD DEVICE][192.168.68.135] Verifying port 443.
2022-03-28 20:55:48 DEBUG (MainThread) [custom_components.tapo_control] [ADD DEVICE][192.168.68.135] Port 443 is opened, verifying access to control of camera.
2022-03-28 20:55:48 DEBUG (MainThread) [custom_components.tapo_control] [ADD DEVICE][192.168.68.135] Verifying ports all required camera ports.
2022-03-28 20:55:48 DEBUG (MainThread) [custom_components.tapo_control] [ADD DEVICE][192.168.68.135] All camera ports are opened, proceeding to requesting Camera Account.
2022-03-28 20:55:48 DEBUG (MainThread) [custom_components.tapo_control] [ADD DEVICE][192.168.68.135] Showing config flow for Camera Account.
2022-03-28 20:55:59 DEBUG (MainThread) [custom_components.tapo_control] [ADD DEVICE][192.168.68.135] Verifying Camera Account.
2022-03-28 20:55:59 DEBUG (MainThread) [custom_components.tapo_control] [ADD DEVICE][192.168.68.135] Verifying ports all required camera ports.
2022-03-28 20:55:59 DEBUG (MainThread) [custom_components.tapo_control] [ADD DEVICE][192.168.68.135] All camera ports are opened.
2022-03-28 20:55:59 DEBUG (MainThread) [custom_components.tapo_control] [ADD DEVICE][192.168.68.135] Testing RTSP stream.
2022-03-28 20:55:59 DEBUG (MainThread) [custom_components.tapo_control] [isRtspStreamWorking][192.168.68.135] Testing RTSP stream.
2022-03-28 20:55:59 DEBUG (MainThread) [custom_components.tapo_control] [isRtspStreamWorking][192.168.68.135] Creating image frame.
2022-03-28 20:55:59 DEBUG (MainThread) [custom_components.tapo_control] [isRtspStreamWorking][192.168.68.135] Encoding username and password.
2022-03-28 20:55:59 DEBUG (MainThread) [custom_components.tapo_control] [isRtspStreamWorking][192.168.68.135] Getting image from rtsp://HIDDEN_USERNAME:HIDDEN_PASSWORD@192.168.68.135:554/stream1.
2022-03-28 20:56:00 DEBUG (MainThread) [custom_components.tapo_control] [isRtspStreamWorking][192.168.68.135] Image data received.
2022-03-28 20:56:00 DEBUG (MainThread) [custom_components.tapo_control] [ADD DEVICE][192.168.68.135] RTSP stream returned invalid authentication data error.
2022-03-28 20:56:00 DEBUG (MainThread) [custom_components.tapo_control] [ADD DEVICE][192.168.68.135] Showing config flow for Camera Account.

**Comment by JurajNyiri** [comment]
RTSP stream does not load correctly via Home Assistant.

Does RTSP stream work when you open `rtsp://HIDDEN_USERNAME:HIDDEN_PASSWORD@192.168.68.135:554/stream1` via VLC? Replace `HIDDEN_USERNAME` and `HIDDEN_PASSWORD` with the exactly same string as you are putting into Camera Account username and password.

**Comment by aljer78** [comment]
I do not try at VLC yet. I'll try and update the result.
Regarding the Camera Account, i already try create new username new password with the Tapo app . The result is same.

**Comment by JurajNyiri** [comment]
Please try with vlc or something else where you can put in the link to open stream, without it we cannot move forwards.

**Comment by aljer78** [comment]
Vlc doesn’t work too.. 
User name : azrysyam
Password: watywaty77

**Comment by aljer78** [comment]
![image](https://user-images.githubusercontent.com/75206777/160420246-e04332e0-9dc0-4f75-a20f-e17283fefcb7.png)

**Comment by aljer78** [comment]
noted

**Comment by aljer78** [comment]
@JurajNyiri i found the culprit already.

**Comment by andbuitra** [comment]
In case anyone if having this issue as well. Check that no other connection is being made to the camera at setup time or else it won't let it configure.

I have 2 C200 and one C210. The C200 had no issues in configuration but I was not able to add the C210 with the right credentials. All three of them are in use with Frigate. I had to stop Frigate to kill the connection to the C210 and attempt to add it again. This time it let me add it without issues.

I don't use the streams from this integration but the WebRTC ones from Frigate. I use this integration to control every other aspect of the camera. Therefore I don't mind not having a working stream in this integration but it is something to keep in mind for other people.
