### ISSUE TITLE
Tapo C200 Cannot get HD stream

### ISSUE THREAD

**Issue by deam0n** [JurajNyiri/HomeAssistant-Tapo-Control#165]
### Description

The HD stream is not reachable outputting the attached error.
The SD stream seems to work.

On Tapo app, both streams work without issue.

When I attempt to activate "Use Stream from Home Assistant [requires restart]" I get the error "Invalid authentication data"

### Reproduction Steps

1. integrate camera via HomeAssistant Tapo Control integration
2. Create glance card with had camera entity

### Expected behavior

HD Stream available.

### If applicable, add error logs.

Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/aiohttp/web_protocol.py", line 435, in _handle_request
    resp = await request_handler(request)
  File "/usr/local/lib/python3.9/site-packages/aiohttp/web_app.py", line 504, in _handle
    resp = await handler(request)
  File "/usr/local/lib/python3.9/site-packages/aiohttp/web_middlewares.py", line 117, in impl
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 60, in security_filter_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/forwarded.py", line 222, in forwarded_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 28, in request_context_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 79, in ban_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 219, in auth_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/view.py", line 137, in handle
    result = await result
  File "/usr/src/homeassistant/homeassistant/components/camera/__init__.py", line 752, in get
    return await self.handle(request, camera)
  File "/usr/src/homeassistant/homeassistant/components/camera/__init__.py", line 792, in handle
    stream = await camera.handle_async_mjpeg_stream(request)
  File "/config/custom_components/tapo_control/camera.py", line 255, in handle_async_mjpeg_stream
    await stream.close()
  File "/usr/local/lib/python3.9/site-packages/haffmpeg/core.py", line 158, in close
    await self._loop.run_in_executor(None, _close)
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.9/site-packages/haffmpeg/core.py", line 153, in _close
    self._proc.stdin.write(b"q")
BrokenPipeError: [Errno 32] Broken pipe

### Device Firmware

1.1.16

### Using stream component

No

### Does camera work via official integrations?

No

### Camera has all attributes filled out in developer tools

Yes

### HASS Environment

HassOS

### Search for similar issues

Yes

**Comment by JurajNyiri** [comment]
Restart your camera and Home Assistant. Make sure you are not using more than 1 active stream.

**Comment by deam0n** [comment]
Hi JurajNyiri,

thanks for the feedback. However the solution was to use Home Assistant stream instead. Eventually I was able to activate the option (after a HA and cam restart) and once restarted HA once again, the issue went away.

I can have several (tried 4) simultaneous streams, with very short delays.

**Comment by JurajNyiri** [comment]
To any future readers, no solution was not to use Home Assistant stream instead. It was restarting the camera and/or Home Assistant.
