### ISSUE TITLE
KeyError: 'mac'

### ISSUE THREAD

**Issue by groenmarsmannetje** [JurajNyiri/HomeAssistant-Tapo-Control#166]
### Description

Since some time I have an issue that all the entities of the Tapo C200 camera integration remain unavailable also after restart. The Home Assistant log shows a KeyError: 'mac' message.

Today I tried to remove and reinstall the Tapo integration. But also in that case I get a similar error (see below) and the entities are not created at all. 

The camera is available on the network because at the same time I am able to get the RTSP stream from the Tapo Camera into Home Assistant. 

### Reproduction Steps

1. Remove integration
2. Restart HA
3. Install and configure integration
4. Restart HA
5. Check if entities have been created
6. Check logs for errors

### Expected behavior

The camera and sensor entities should become available again.

### If applicable, add error logs.

Logger: homeassistant.components.camera
Source: custom_components/tapo_control/camera.py:308
Integration: Camera ([documentation](https://www.home-assistant.io/integrations/camera), [issues](https://github.com/home-assistant/home-assistant/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+camera%22))
First occurred: 15:22:08 (2 occurrences)
Last logged: 15:22:08

Error adding entities for domain camera with platform tapo_control
Error while setting up tapo_control platform for camera
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 382, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 442, in _async_add_entity
    if entity.unique_id is not None:
  File "/config/custom_components/tapo_control/camera.py", line 189, in unique_id
    return self.getUniqueID()
  File "/config/custom_components/tapo_control/camera.py", line 308, in getUniqueID
    return slugify(f"{self._attributes['mac']}_{streamType}_tapo_control")
KeyError: 'mac'

### Device Firmware

1.1.16 Build 211209 Rel.37726n(4555)

### Using stream component

Yes

### Does camera work via official integrations?

Yes

### Camera has all attributes filled out in developer tools

No

### HASS Environment

HASSio

### Search for similar issues

Yes

**Comment by groenmarsmannetje** [comment]
Seems to work again after I have:
- Allowed that the camera made internet connection on my router
- Updated the camera to latest firmware

Not sure though which one made the trick
