### ISSUE TITLE
lost connection to working camera and can't re-establish without removing the integration

### ISSUE THREAD

**Issue by dogmatic69** [JurajNyiri/HomeAssistant-Tapo-Control#186]
### Description

Connection to my C200 camera is lost and I can not find any way to re-establish a connection besides removing the integration and setting it up again. Also can't figure out why it happens as there is no fixed time nor a clear cause of the lost connection in the first place.

This has now happened multiple times, and while it can not be reached in HA it is perfectly accessible through the official tapo iOS app.

![image](https://user-images.githubusercontent.com/94674/177119398-0ae07f0e-3227-43c2-b29a-9d45ffd36803.png)

![image](https://user-images.githubusercontent.com/94674/177119257-ebabc449-468c-4479-8e74-ce513f59bdd9.png)

![image](https://user-images.githubusercontent.com/94674/177119551-c70c3b7e-7b72-44e8-aa01-825564cdaf30.png)

### Reproduction Steps

1. not sure

### Expected behavior

if the camera is available, the integration should be able to connect. If there was a connection issue it should be able to recover once the camera is available.

Ideally automatically, but a restart should definitely fix things. Should not need to delete and reconfigure the integration to make it work again.

### If applicable, add error logs.

Seems to start with errors like this, approximately every 15 seconds.

```
ERROR (MainThread) [custom_components.tapo_control] HTTPSConnectionPool(host='xxxx', port=443): Max retries exceeded with url: /stok=xxxxxxx/ds (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff531e8d30>: Failed to establish a new connection: [Errno 110] Operation timed out'))
```

Eventually the errors look like this around every 30 seconds.
```
ERROR (MainThread) [custom_components.tapo_control] Unexpected error fetching Tapo resource status data: All connection attempts failed
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/anyio/_core/_sockets.py", line 164, in try_connect
    stream = await asynclib.connect_tcp(remote_host, remote_port, local_address)
  File "/usr/local/lib/python3.9/site-packages/anyio/_backends/_asyncio.py", line 1691, in connect_tcp
    await get_running_loop().create_connection(
  File "/usr/local/lib/python3.9/asyncio/base_events.py", line 1065, in create_connection
    raise exceptions[0]
  File "/usr/local/lib/python3.9/asyncio/base_events.py", line 1050, in create_connection
    sock = await self._connect_sock(
  File "/usr/local/lib/python3.9/asyncio/base_events.py", line 961, in _connect_sock
    await self.sock_connect(sock, address)
  File "/usr/local/lib/python3.9/asyncio/selector_events.py", line 499, in sock_connect
    return await fut
  File "/usr/local/lib/python3.9/asyncio/selector_events.py", line 534, in _sock_connect_cb
    raise OSError(err, f'Connect call failed {address}')
OSError: [Errno 113] Connect call failed ('192.168.7.149', 2020)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/httpcore/_exceptions.py", line 8, in map_exceptions
    yield
  File "/usr/local/lib/python3.9/site-packages/httpcore/backends/asyncio.py", line 109, in connect_tcp
    stream: anyio.abc.ByteStream = await anyio.connect_tcp(
  File "/usr/local/lib/python3.9/site-packages/anyio/_core/_sockets.py", line 222, in connect_tcp
    raise OSError("All connection attempts failed") from cause
OSError: All connection attempts failed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/httpx/_transports/default.py", line 60, in map_httpcore_exceptions
    yield
  File "/usr/local/lib/python3.9/site-packages/httpx/_transports/default.py", line 353, in handle_async_request
    resp = await self._pool.handle_async_request(req)
  File "/usr/local/lib/python3.9/site-packages/httpcore/_async/connection_pool.py", line 253, in handle_async_request
    raise exc
  File "/usr/local/lib/python3.9/site-packages/httpcore/_async/connection_pool.py", line 237, in handle_async_request
    response = await connection.handle_async_request(request)
  File "/usr/local/lib/python3.9/site-packages/httpcore/_async/connection.py", line 86, in handle_async_request
    raise exc
  File "/usr/local/lib/python3.9/site-packages/httpcore/_async/connection.py", line 63, in handle_async_request
    stream = await self._connect(request)
  File "/usr/local/lib/python3.9/site-packages/httpcore/_async/connection.py", line 111, in _connect
    stream = await self._network_backend.connect_tcp(**kwargs)
  File "/usr/local/lib/python3.9/site-packages/httpcore/backends/auto.py", line 29, in connect_tcp
    return await self._backend.connect_tcp(
  File "/usr/local/lib/python3.9/site-packages/httpcore/backends/asyncio.py", line 109, in connect_tcp
    stream: anyio.abc.ByteStream = await anyio.connect_tcp(
  File "/usr/local/lib/python3.9/contextlib.py", line 137, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/usr/local/lib/python3.9/site-packages/httpcore/_exceptions.py", line 12, in map_exceptions
    raise to_exc(exc)
httpcore.ConnectError: All connection attempts failed

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 191, in _async_refresh
    self.data = await self._async_update_data()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 150, in _async_update_data
    return await self.update_method()
  File "/config/custom_components/tapo_control/__init__.py", line 204, in async_update_data
    await syncTime(hass, entry)
  File "/config/custom_components/tapo_control/utils.py", line 263, in syncTime
    await device_mgmt.SetSystemDateAndTime(time_params)
  File "/usr/local/lib/python3.9/site-packages/zeep/proxy.py", line 64, in __call__
    return await self._proxy._binding.send_async(
  File "/usr/local/lib/python3.9/site-packages/zeep/wsdl/bindings/soap.py", line 156, in send_async
    response = await client.transport.post_xml(
  File "/usr/local/lib/python3.9/site-packages/zeep/transports.py", line 230, in post_xml
    response = await self.post(address, message, headers)
  File "/usr/local/lib/python3.9/site-packages/zeep/transports.py", line 215, in post
    response = await self.client.post(
  File "/usr/local/lib/python3.9/site-packages/httpx/_client.py", line 1842, in post
    return await self.request(
  File "/usr/local/lib/python3.9/site-packages/httpx/_client.py", line 1527, in request
    return await self.send(request, auth=auth, follow_redirects=follow_redirects)
  File "/usr/local/lib/python3.9/site-packages/httpx/_client.py", line 1614, in send
    response = await self._send_handling_auth(
  File "/usr/local/lib/python3.9/site-packages/httpx/_client.py", line 1642, in _send_handling_auth
    response = await self._send_handling_redirects(
  File "/usr/local/lib/python3.9/site-packages/httpx/_client.py", line 1679, in _send_handling_redirects
    response = await self._send_single_request(request)
  File "/usr/local/lib/python3.9/site-packages/httpx/_client.py", line 1716, in _send_single_request
    response = await transport.handle_async_request(request)
  File "/usr/local/lib/python3.9/site-packages/httpx/_transports/default.py", line 353, in handle_async_request
    resp = await self._pool.handle_async_request(req)
  File "/usr/local/lib/python3.9/contextlib.py", line 137, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/usr/local/lib/python3.9/site-packages/httpx/_transports/default.py", line 77, in map_httpcore_exceptions
    raise mapped_exc(message) from exc
httpx.ConnectError: All connection attempts failed
```

### Device Firmware

1.1.17 build 220107 rel.10833n(4555)

### Using stream component

No

### Does camera work via official integrations?

N/A

### Camera has all attributes filled out in developer tools

No

### HASS Environment

Home Assistant Blue

### Search for similar issues

Yes

### Additional information

Similar to #173 but my camera is available. 

I'm not really sure what "Using stream component" is, don't think so. 

```
  - type: vertical-stack
    cards:
      - type: picture-glance
        title: Cat Cam
        camera_image: camera.cat_cam_hd
        camera_view: live
```

**Comment by JurajNyiri** [comment]
Please test your camera with https://www.home-assistant.io/integrations/onvif/ integration. It is most probably a camera / network issue.
There is nothing different happening between reboot or readding the camera. There is also an automatic retry. Maybe camera IP changes?
Once tested with onvif, and there is no problem there and the problem here persists, reopen the issue.

**Comment by dogmatic69** [comment]
Forget the camera feed for a moment, the motion detection also does not work. 

Even if there was a network issue (which I highly doubt), It's very clearly not able to recover from an issue.

For reference I'm running a full Ubiquity network with mesh Wi-fi, the C200 is the only thing using Wi-fi. According to Unifi it has a very stable connection 
![image](https://user-images.githubusercontent.com/94674/177138726-e481defb-b769-43c6-9922-cbc2c34aa19b.png)

**Comment by JurajNyiri** [comment]
We cannot move forwards until you test with onvif like I asked you.

Regarding motion detection, go and check for numerous closed issues (and even one opened one) like you said you did. Or go and read readme, especially the FAQ section.

**Comment by JurajNyiri** [comment]
Also make sure to not stress the camera, usually it can take up to 2 connections at the same time, at most. If there is more, these connection issues start happening.
It is also very flaky with too many reconnection requests (like restarting the Home Assistant too often etc.). Reboot of the camera helps.

**Comment by dogmatic69** [comment]
I've not restarted anything, simply added onvif and works out the box. Tapo integration still not loading the image.
```
  - type: vertical-stack
    cards:
      - type: picture-glance
        title: Test Cam
        camera_image: camera.c200_test_mainstream
        camera_view: live
        entities: []
      - type: picture-glance
        title: Cat Cam
        camera_image: camera.cat_cam_hd
        camera_view: live
        entities:
          ....
```

![image](https://user-images.githubusercontent.com/94674/177158048-917d33d3-c0aa-4b3f-a108-c093b46ee320.png)
![image](https://user-images.githubusercontent.com/94674/177158362-903f9610-aaf7-4c49-86ec-cfd50bf63713.png)

**Comment by dogmatic69** [comment]
> Regarding motion detection, go and check for numerous closed issues (and even one opened one) like you said you did. Or go and read readme, especially the FAQ section.

Not sure what your point is here, my point was that the entire thing stopped working. Stream and motion detection.....

**Comment by JurajNyiri** [comment]
Try following 

- Update to the latest version released today
- Remove any other integration using the camera 
- Make sure all ports are opened as described in readme
- Try different options for RTSP transport mechanism (TCP, UDP...)
- Does stream work? 
- Does control work?
- Does motion detection work?

Be as detailed as possible with all the steps you do and all the configurations.
