### ISSUE TITLE
C200 Motion Sensor not working on 1.1.18 firmware version

### ISSUE THREAD

**Issue by rodrigogbs** [JurajNyiri/HomeAssistant-Tapo-Control#202]
### Description

After updating the C200 firmware to 1.1.18 version the motion sensor stoped working on HA.

### Reproduction Steps

1. Update the C200 firmware to 1.1.18
2. Update the Tapo Integration to latest version (3.7.2)
3. Restart HA
4. The camera motion sensor will be unavailable even after detected motions

### Expected behavior

Functional motion sensor

### If applicable, add error logs.

I have an automation to e amble the motion sensor, and this error is being showed in the logs:

Logger: homeassistant.components.automation.monitoramento_habilitar_motion_detection_camera_sala
Source: custom_components/tapo_control/camera.py:427 
Integration: Automation (documentation, issues) 
First occurred: 8:40:02 AM (4 occurrences) 
Last logged: 9:45:04 AM

Monitoramento - Habilitar Motion Detection Câmera Sala: Error executing script. Unexpected error for call_service at pos 1: Error: Invalid stok value, Response: {"error_code": -40401, "result": {"data": {"code": -40407, "encrypt_type": ["1", "2"], "key": "MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQDG3p%2fEXbM28OauoRLfVDKsAGmmCbG20ci7ilSp7GFAI05IpOWx%2bbsca0KIrTwIe%2fIRl0DtzSXjBjKEM91DRomCKYyPRStOzbJrnhfHjlA5YRpVqLya%2fhljA8o0f3yX%2bG3C3pljL8gr%2b02IIoHCInXerRQiLRw9hmEbPn52f85RowIDAQAB", "nonce": "7pQVh06f"}}}
While executing automation automation.monitoramento_habilitar_motion_detection_camera_sala
Monitoramento - Habilitar Motion Detection Câmera Sala: Error executing script. Unexpected error for call_service at pos 1: Error: Invalid stok value, Response: {"error_code": -40401, "result": {"data": {"code": -40407, "encrypt_type": ["1", "2"], "key": "MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQDG3p%2fEXbM28OauoRLfVDKsAGmmCbG20ci7ilSp7GFAI05IpOWx%2bbsca0KIrTwIe%2fIRl0DtzSXjBjKEM91DRomCKYyPRStOzbJrnhfHjlA5YRpVqLya%2fhljA8o0f3yX%2bG3C3pljL8gr%2b02IIoHCInXerRQiLRw9hmEbPn52f85RowIDAQAB", "nonce": "UXrMdafX"}}}
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 447, in _async_step
    await getattr(self, handler)()
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 680, in _async_call_service_step
    await service_task
  File "/usr/src/homeassistant/homeassistant/core.py", line 1713, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1750, in _execute_service
    await cast(Callable[[ServiceCall], Awaitable[None]], handler.job.target)(
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 751, in handle_service
    await service.entity_service_call(
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 676, in entity_service_call
    future.result()  # pop exception if have
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 930, in async_request_call
    await coro
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 713, in _handle_entity_call
    await result
  File "/config/custom_components/tapo_control/camera.py", line 427, in set_motion_detection_mode
    await self.hass.async_add_executor_job(
  File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.10/site-packages/pytapo/__init__.py", line 372, in setMotionDetection
    return self.performRequest(data)
  File "/usr/local/lib/python3.10/site-packages/pytapo/__init__.py", line 112, in performRequest
    return self.performRequest(requestData, True)
  File "/usr/local/lib/python3.10/site-packages/pytapo/__init__.py", line 114, in performRequest
    raise Exception(
Exception: Error: Invalid stok value, Response: {"error_code": -40401, "result": {"data": {"code": -40407, "encrypt_type": ["1", "2"], "key": "MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQDG3p%2fEXbM28OauoRLfVDKsAGmmCbG20ci7ilSp7GFAI05IpOWx%2bbsca0KIrTwIe%2fIRl0DtzSXjBjKEM91DRomCKYyPRStOzbJrnhfHjlA5YRpVqLya%2fhljA8o0f3yX%2bG3C3pljL8gr%2b02IIoHCInXerRQiLRw9hmEbPn52f85RowIDAQAB", "nonce": "7pQVh06f"}}}

### Device Firmware

1.1.18

### Using stream component

Yes

### Does camera work via official integrations?

Yes

### Camera has all attributes filled out in developer tools

Yes

### HASS Environment

HASSOS

### Search for similar issues

Yes

**Comment by JurajNyiri** [comment]
Check faq, reboot camera and home assistant.

**Comment by rodrigogbs** [comment]
I already rebooted both and the problem persists!

**Comment by rodrigogbs** [comment]
@JurajNyiri does your camera is working on 1.1.18 FW?

**Comment by rodrigogbs** [comment]
I found the problem!

After the update the integration created an "...motion_2" entity, I've just removed the old one and renamed the new one to "...motion", everything is ok now!

But is important to understand why it happened.
