### ISSUE TITLE
Error Handling when connection is lost

### ISSUE THREAD

**Issue by CFenner** [JurajNyiri/HomeAssistant-Tapo-Control#221]
### Description

When my camera is disconnected the connection is lost  which is logged to the logs and all entities are still available.

### Reproduction Steps

pull the plug

### Expected behavior

When the camera is disconnected the entities should turn to `unavailable`.

### If applicable, add error logs.

```
Logger: homeassistant.helpers.entity
Source: custom_components/tapo_control/camera.py:217 
Integration: Tapo: Kamerasteuerung ([documentation](https://github.com/JurajNyiri/HomeAssistant-Tapo-Control), [issues](https://github.com/JurajNyiri/HomeAssistant-Tapo-Control/issues)) 
First occurred: 11:35:57 (12 occurrences) 
Last logged: 11:41:26

Update for camera.flur_hd fails
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/urllib3/connection.py", line 174, in _new_conn
    conn = connection.create_connection(
  File "/usr/local/lib/python3.10/site-packages/urllib3/util/connection.py", line 95, in create_connection
    raise err
  File "/usr/local/lib/python3.10/site-packages/urllib3/util/connection.py", line 85, in create_connection
    sock.connect(sa)
OSError: [Errno 113] Host is unreachable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
  File "/usr/local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 386, in _make_request
    self._validate_conn(conn)
  File "/usr/local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 1042, in _validate_conn
    conn.connect()
  File "/usr/local/lib/python3.10/site-packages/urllib3/connection.py", line 358, in connect
    self.sock = conn = self._new_conn()
  File "/usr/local/lib/python3.10/site-packages/urllib3/connection.py", line 186, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x7f819a7be0>: Failed to establish a new connection: [Errno 113] Host is unreachable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/requests/adapters.py", line 489, in send
    resp = conn.urlopen(
  File "/usr/local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 787, in urlopen
    retries = retries.increment(
  File "/usr/local/lib/python3.10/site-packages/urllib3/util/retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='192.168.1.187', port=443): Max retries exceeded with url: /stok=5bc42d314862c95bb2db607afb13a7e6/ds (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f819a7be0>: Failed to establish a new connection: [Errno 113] Host is unreachable'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 515, in async_update_ha_state
    await self.async_device_update()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 718, in async_device_update
    await task
  File "/config/custom_components/tapo_control/camera.py", line 217, in async_update
    data = await self._hass.async_add_executor_job(
  File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.10/site-packages/pytapo/__init__.py", line 206, in getMotionDetection
    return self.performRequest(data)["motion_detection"]["motion_det"]
  File "/usr/local/lib/python3.10/site-packages/pytapo/__init__.py", line 97, in performRequest
    res = requests.post(
  File "/usr/local/lib/python3.10/site-packages/requests/api.py", line 115, in post
    return request("post", url, data=data, json=json, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/requests/sessions.py", line 587, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.10/site-packages/requests/sessions.py", line 701, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/requests/adapters.py", line 565, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='192.168.1.187', port=443): Max retries exceeded with url: /stok=5bc42d314862c95bb2db607afb13a7e6/ds (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f819a7be0>: Failed to establish a new connection: [Errno 113] Host is unreachable'))
```

### Device Firmware

1.1.21 Build 220511 Rel.29067n(4555)

### Using stream component

Yes

### Does camera work via official integrations?

Yes

### Camera has all attributes filled out in developer tools

No

### HASS Environment

RaspberryPi with HomeAssistant OS

### Search for similar issues

Yes

**Comment by CFenner** [comment]
Camera Entity flickrs between `idle` and `unavailable`, all other entities are not shows as `unavailable`.

<img width="337" alt="Bildschirmfoto 2022-10-21 um 11 11 15" src="https://user-images.githubusercontent.com/9592452/197159622-468496e6-b805-42a6-9ac4-708f6bc98048.png">
