### ISSUE TITLE
Error noiseSensorStarted аfter updating to the version 4.1.0

### ISSUE THREAD

**Issue by e1evat** [JurajNyiri/HomeAssistant-Tapo-Control#224]
### Description

I have Tapo C110. After updating to the integration version 4.1.0, an entry began to appear in the logs of the home assistant. The sound detection option (Enable sound threshold detection) is disabled in the integration and I don't need it.

### Reproduction Steps

After updating to the integration version 4.1.0

### Expected behavior

Fix error

### If applicable, add error logs.

2022-10-21 07:15:30.451 ERROR (MainThread) [custom_components.tapo_control] Unexpected error fetching Tapo resource status data: 'noiseSensorStarted'
Traceback (most recent call last):
  File "/opt/homeassistant/lib/python3.10/site-packages/homeassistant/helpers/update_coordinator.py", line 205, in _async_refresh
    self.data = await self._async_update_data()
  File "/opt/homeassistant/lib/python3.10/site-packages/homeassistant/helpers/update_coordinator.py", line 164, in _async_update_data
    return await self.update_method()
  File "/opt/homeassistant/config/custom_components/tapo_control/__init__.py", line 251, in async_update_data
    not hass.data[DOMAIN][entry.entry_id]["noiseSensorStarted"]
KeyError: 'noiseSensorStarted'

### Device Firmware

1.1.13 Build 211209 Rel.26010n(4555)

### Using stream component

Yes

### Does camera work via official integrations?

Yes

### Camera has all attributes filled out in developer tools

Yes

### HASS Environment

Home Assistant Core 2022.9.4

### Search for similar issues

No

**Comment by aIexus** [comment]
The same error for C200 camera.

**Comment by Taomyn** [comment]
Confirmed with my C200 - I never used the noise sensor before in case that matters
