### ISSUE TITLE
Can't connect to ONVIF when camera is not in the same network

### ISSUE THREAD

**Issue by fballiano** [JurajNyiri/HomeAssistant-Tapo-Control#254]
### Description

Hi,
I've 2 TAPO cameras, one on the local network (of the home assistant instance) and one remote, the local one works perfectly, the remote one works 50%, stream works perfectly but the onvif (motion sensor) doesn't.

I get this error logs:
```
2022-11-17 21:45:48.590 ERROR (MainThread) [custom_components.tapo_control] Unexpected error fetching Tapo resource status data: All connection attempts failed
Traceback (most recent call last):
  File "/mnt/dietpi_userdata/homeassistant/deps/lib/python3.9/site-packages/anyio/_core/_sockets.py", line 164, in try_connect
    stream = await asynclib.connect_tcp(remote_host, remote_port, local_address)
  File "/mnt/dietpi_userdata/homeassistant/deps/lib/python3.9/site-packages/anyio/_backends/_asyncio.py", line 1691, in connect_tcp
    await get_running_loop().create_connection(
  File "/home/homeassistant/.pyenv/versions/3.9.15/lib/python3.9/asyncio/base_events.py", line 1065, in create_connection
    raise exceptions[0]
  File "/home/homeassistant/.pyenv/versions/3.9.15/lib/python3.9/asyncio/base_events.py", line 1050, in create_connection
    sock = await self._connect_sock(
  File "/home/homeassistant/.pyenv/versions/3.9.15/lib/python3.9/asyncio/base_events.py", line 961, in _connect_sock
    await self.sock_connect(sock, address)
  File "/home/homeassistant/.pyenv/versions/3.9.15/lib/python3.9/asyncio/selector_events.py", line 500, in sock_connect
    return await fut
  File "/home/homeassistant/.pyenv/versions/3.9.15/lib/python3.9/asyncio/selector_events.py", line 535, in _sock_connect_cb
    raise OSError(err, f'Connect call failed {address}')
OSError: [Errno 113] Connect call failed ('192.168.1.131', 2020)
```

The thing is, that IP address (192.168.1.131) is wrong since it's the remote camera (when setting it up I'm using a dyndns domain name) so it seems it's trying to connect to the "local" address (in the remote network) which I never typed anywhere and I've no idea where it got it from.

If I check the open ports all of them seem to be working fine, example:
```
fab@MBP-Fab ~ [1]> nc -vz xxx.ddns.net 2020
Connection to xxx.ddns.net port 2020 [tcp/xinupageserver] succeeded!
```

### Reproduction Steps

1. setting up a camera which is not in the same network of the home assistant

### Expected behavior

stream and onvif work

### Device Firmware

latest available

### Using stream component

Yes

### Does camera work via official integrations?

Yes

### Camera has all attributes filled out in developer tools

No

### HASS Environment

HA core on dietPi

### Search for similar issues

Yes

**Comment by JurajNyiri** [comment]
Camera does work remotely as expected. It uses the same IP or hostname you specify for 443, 2020 and rtsp. It also has no way how to get local ip of the camera. The error you see is not related to this issue and probably comes from you testing stuff or adding that IP before.

On a side note, port forwarding your camera is **really** _really_ bad idea.

**Comment by fballiano** [comment]
That is precisely why i opened this.. marking it as complete doesn’t help anybody. Also if i added that ip previously what does it mean? I can never add any other ip ever? I don’t think so.
That ip was added and deleted, the new configuration has nothing to do with that one that, as i said, was deleted and recreated from scratch.
So something is stuck somewhere.

**Comment by JurajNyiri** [comment]
The log you added is not relevant to the issue at all as it is for something completely different from the past.

**Comment by fballiano** [comment]
That log gets created the moment i hit the reconfigure button on the home assistant devices button.
Also I already grepped everywhere for that wrong IP and there’s nothing anywhere (unless it’s somewhere binary or encryped)

**Comment by JurajNyiri** [comment]
> marking it as complete doesn’t help anybody

The issue board on GitHub is for issues with the integration. So far this looks like issue with your network. Just keeping things clean. If this proves to be an integration issue I will reopen this and fix it 🙂

**Comment by JurajNyiri** [comment]
1. Uninstall the integration and remove any mention of tapo_control objects from all jsons inside .storage. 
2. Restart home assistant
3. Install integration
4. Add camera

**Comment by fballiano** [comment]
As i posted the nectat you can see the connection works fine. The only not working thing is the onvif which is the logged errors. The stream works perfect. 
to me there’s some cache based on the device id or something

**Comment by JurajNyiri** [comment]
Please follow the steps I sent above, otherwise I cannot help you.

**Comment by fballiano** [comment]
getting back, removed all the tapo devices, removed the integration, cleaned everything (tapo_control related) in .storage, restarted and readded and the error still appears :-(

```
2022-11-18 09:05:06.986 ERROR (MainThread) [custom_components.tapo_control] Unable to connect to Tapo: Cameras Control controller: All connection attempts failed
2022-11-18 09:05:10.069 ERROR (MainThread) [custom_components.tapo_control] Unexpected error fetching Tapo resource status data: All connection attempts failed
Traceback (most recent call last):
  File "/mnt/dietpi_userdata/homeassistant/deps/lib/python3.9/site-packages/anyio/_core/_sockets.py", line 164, in try_connect
    stream = await asynclib.connect_tcp(remote_host, remote_port, local_address)
  File "/mnt/dietpi_userdata/homeassistant/deps/lib/python3.9/site-packages/anyio/_backends/_asyncio.py", line 1691, in connect_tcp
    await get_running_loop().create_connection(
  File "/home/homeassistant/.pyenv/versions/3.9.15/lib/python3.9/asyncio/base_events.py", line 1065, in create_connection
    raise exceptions[0]
  File "/home/homeassistant/.pyenv/versions/3.9.15/lib/python3.9/asyncio/base_events.py", line 1050, in create_connection
    sock = await self._connect_sock(
  File "/home/homeassistant/.pyenv/versions/3.9.15/lib/python3.9/asyncio/base_events.py", line 961, in _connect_sock
    await self.sock_connect(sock, address)
  File "/home/homeassistant/.pyenv/versions/3.9.15/lib/python3.9/asyncio/selector_events.py", line 500, in sock_connect
    return await fut
  File "/home/homeassistant/.pyenv/versions/3.9.15/lib/python3.9/asyncio/selector_events.py", line 535, in _sock_connect_cb
    raise OSError(err, f'Connect call failed {address}')
OSError: [Errno 113] Connect call failed ('192.168.1.131', 2020)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/homeassistant/.pyenv/versions/3.9.15/lib/python3.9/site-packages/httpcore/_exceptions.py", line 8, in map_exceptions
    yield
  File "/home/homeassistant/.pyenv/versions/3.9.15/lib/python3.9/site-packages/httpcore/backends/asyncio.py", line 109, in connect_tcp
    stream: anyio.abc.ByteStream = await anyio.connect_tcp(
  File "/mnt/dietpi_userdata/homeassistant/deps/lib/python3.9/site-packages/anyio/_core/_sockets.py", line 222, in connect_tcp
    raise OSError("All connection attempts failed") from cause
OSError: All connection attempts failed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/homeassistant/.pyenv/versions/3.9.15/lib/python3.9/site-packages/httpx/_transports/default.py", line 60, in map_httpcore_exceptions
    yield
  File "/home/homeassistant/.pyenv/versions/3.9.15/lib/python3.9/site-packages/httpx/_transports/default.py", line 353, in handle_async_request
    resp = await self._pool.handle_async_request(req)
  File "/home/homeassistant/.pyenv/versions/3.9.15/lib/python3.9/site-packages/httpcore/_async/connection_pool.py", line 253, in handle_async_request
    raise exc
  File "/home/homeassistant/.pyenv/versions/3.9.15/lib/python3.9/site-packages/httpcore/_async/connection_pool.py", line 237, in handle_async_request
    response = await connection.handle_async_request(request)
  File "/home/homeassistant/.pyenv/versions/3.9.15/lib/python3.9/site-packages/httpcore/_async/connection.py", line 86, in handle_async_request
    raise exc
  File "/home/homeassistant/.pyenv/versions/3.9.15/lib/python3.9/site-packages/httpcore/_async/connection.py", line 63, in handle_async_request
    stream = await self._connect(request)
  File "/home/homeassistant/.pyenv/versions/3.9.15/lib/python3.9/site-packages/httpcore/_async/connection.py", line 111, in _connect
    stream = await self._network_backend.connect_tcp(**kwargs)
  File "/home/homeassistant/.pyenv/versions/3.9.15/lib/python3.9/site-packages/httpcore/backends/auto.py", line 29, in connect_tcp
    return await self._backend.connect_tcp(
  File "/home/homeassistant/.pyenv/versions/3.9.15/lib/python3.9/site-packages/httpcore/backends/asyncio.py", line 109, in connect_tcp
    stream: anyio.abc.ByteStream = await anyio.connect_tcp(
  File "/home/homeassistant/.pyenv/versions/3.9.15/lib/python3.9/contextlib.py", line 137, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/home/homeassistant/.pyenv/versions/3.9.15/lib/python3.9/site-packages/httpcore/_exceptions.py", line 12, in map_exceptions
    raise to_exc(exc)
httpcore.ConnectError: All connection attempts failed

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/homeassistant/.pyenv/versions/3.9.15/lib/python3.9/site-packages/homeassistant/helpers/update_coordinator.py", line 205, in _async_refresh
    self.data = await self._async_update_data()
  File "/home/homeassistant/.pyenv/versions/3.9.15/lib/python3.9/site-packages/homeassistant/helpers/update_coordinator.py", line 164, in _async_update_data
    return await self.update_method()
  File "/mnt/dietpi_userdata/homeassistant/custom_components/tapo_control/__init__.py", line 206, in async_update_data
    ] = await setupEvents(hass, entry)
  File "/mnt/dietpi_userdata/homeassistant/custom_components/tapo_control/utils.py", line 363, in setupEvents
    if await events.async_start():
  File "/home/homeassistant/.pyenv/versions/3.9.15/lib/python3.9/site-packages/homeassistant/components/onvif/event.py", line 81, in async_start
    if await self.device.create_pullpoint_subscription():
  File "/mnt/dietpi_userdata/homeassistant/deps/lib/python3.9/site-packages/onvif/client.py", line 311, in create_pullpoint_subscription
    pullpoint = await events.CreatePullPointSubscription()
  File "/mnt/dietpi_userdata/homeassistant/deps/lib/python3.9/site-packages/zeep/proxy.py", line 64, in __call__
    return await self._proxy._binding.send_async(
  File "/mnt/dietpi_userdata/homeassistant/deps/lib/python3.9/site-packages/zeep/wsdl/bindings/soap.py", line 156, in send_async
    response = await client.transport.post_xml(
  File "/mnt/dietpi_userdata/homeassistant/deps/lib/python3.9/site-packages/zeep/transports.py", line 234, in post_xml
    response = await self.post(address, message, headers)
  File "/mnt/dietpi_userdata/homeassistant/deps/lib/python3.9/site-packages/zeep/transports.py", line 219, in post
    response = await self.client.post(
  File "/home/homeassistant/.pyenv/versions/3.9.15/lib/python3.9/site-packages/httpx/_client.py", line 1842, in post
    return await self.request(
  File "/home/homeassistant/.pyenv/versions/3.9.15/lib/python3.9/site-packages/httpx/_client.py", line 1527, in request
    return await self.send(request, auth=auth, follow_redirects=follow_redirects)
  File "/home/homeassistant/.pyenv/versions/3.9.15/lib/python3.9/site-packages/httpx/_client.py", line 1614, in send
    response = await self._send_handling_auth(
  File "/home/homeassistant/.pyenv/versions/3.9.15/lib/python3.9/site-packages/httpx/_client.py", line 1642, in _send_handling_auth
    response = await self._send_handling_redirects(
  File "/home/homeassistant/.pyenv/versions/3.9.15/lib/python3.9/site-packages/httpx/_client.py", line 1679, in _send_handling_redirects
    response = await self._send_single_request(request)
  File "/home/homeassistant/.pyenv/versions/3.9.15/lib/python3.9/site-packages/httpx/_client.py", line 1716, in _send_single_request
    response = await transport.handle_async_request(request)
  File "/home/homeassistant/.pyenv/versions/3.9.15/lib/python3.9/site-packages/httpx/_transports/default.py", line 353, in handle_async_request
    resp = await self._pool.handle_async_request(req)
  File "/home/homeassistant/.pyenv/versions/3.9.15/lib/python3.9/contextlib.py", line 137, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/home/homeassistant/.pyenv/versions/3.9.15/lib/python3.9/site-packages/httpx/_transports/default.py", line 77, in map_httpcore_exceptions
    raise mapped_exc(message) from exc
httpx.ConnectError: All connection attempts failed
2022-11-18 09:05:23.207 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry xxxxxxxxxx.ddns.net for button
Traceback (most recent call last):
  File "/home/homeassistant/.pyenv/versions/3.9.15/lib/python3.9/site-packages/homeassistant/config_entries.py", line 365, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/home/homeassistant/.pyenv/versions/3.9.15/lib/python3.9/site-packages/homeassistant/components/button/__init__.py", line 66, in async_setup_entry
    return await component.async_setup_entry(entry)
  File "/home/homeassistant/.pyenv/versions/3.9.15/lib/python3.9/site-packages/homeassistant/helpers/entity_component.py", line 161, in async_setup_entry
    raise ValueError("Config entry has already been setup!")
ValueError: Config entry has already been setup!
2022-11-18 09:05:23.215 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry xxxxxxxxxxx.ddns.net for camera
Traceback (most recent call last):
  File "/home/homeassistant/.pyenv/versions/3.9.15/lib/python3.9/site-packages/homeassistant/config_entries.py", line 365, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/home/homeassistant/.pyenv/versions/3.9.15/lib/python3.9/site-packages/homeassistant/components/camera/__init__.py", line 410, in async_setup_entry
    return await component.async_setup_entry(entry)
  File "/home/homeassistant/.pyenv/versions/3.9.15/lib/python3.9/site-packages/homeassistant/helpers/entity_component.py", line 161, in async_setup_entry
    raise ValueError("Config entry has already been setup!")
ValueError: Config entry has already been setup!
2022-11-18 09:05:23.224 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry xxxxxxxxxxx.ddns.net for light
Traceback (most recent call last):
  File "/home/homeassistant/.pyenv/versions/3.9.15/lib/python3.9/site-packages/homeassistant/config_entries.py", line 365, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/home/homeassistant/.pyenv/versions/3.9.15/lib/python3.9/site-packages/homeassistant/components/light/__init__.py", line 618, in async_setup_entry
    return await component.async_setup_entry(entry)
  File "/home/homeassistant/.pyenv/versions/3.9.15/lib/python3.9/site-packages/homeassistant/helpers/entity_component.py", line 161, in async_setup_entry
    raise ValueError("Config entry has already been setup!")
ValueError: Config entry has already been setup!
2022-11-18 09:05:23.232 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry xxxxxxxxxxx.ddns.net for number
Traceback (most recent call last):
  File "/home/homeassistant/.pyenv/versions/3.9.15/lib/python3.9/site-packages/homeassistant/config_entries.py", line 365, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/home/homeassistant/.pyenv/versions/3.9.15/lib/python3.9/site-packages/homeassistant/components/number/__init__.py", line 117, in async_setup_entry
    return await component.async_setup_entry(entry)
  File "/home/homeassistant/.pyenv/versions/3.9.15/lib/python3.9/site-packages/homeassistant/helpers/entity_component.py", line 161, in async_setup_entry
    raise ValueError("Config entry has already been setup!")
ValueError: Config entry has already been setup!
2022-11-18 09:05:23.240 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry xxxxxxxxxxx.ddns.net for select
Traceback (most recent call last):
  File "/home/homeassistant/.pyenv/versions/3.9.15/lib/python3.9/site-packages/homeassistant/config_entries.py", line 365, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/home/homeassistant/.pyenv/versions/3.9.15/lib/python3.9/site-packages/homeassistant/components/select/__init__.py", line 62, in async_setup_entry
    return await component.async_setup_entry(entry)
  File "/home/homeassistant/.pyenv/versions/3.9.15/lib/python3.9/site-packages/homeassistant/helpers/entity_component.py", line 161, in async_setup_entry
    raise ValueError("Config entry has already been setup!")
ValueError: Config entry has already been setup!
2022-11-18 09:05:23.248 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry xxxxxxxxxxx.ddns.net for switch
Traceback (most recent call last):
  File "/home/homeassistant/.pyenv/versions/3.9.15/lib/python3.9/site-packages/homeassistant/config_entries.py", line 365, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/home/homeassistant/.pyenv/versions/3.9.15/lib/python3.9/site-packages/homeassistant/components/switch/__init__.py", line 83, in async_setup_entry
    return await component.async_setup_entry(entry)
  File "/home/homeassistant/.pyenv/versions/3.9.15/lib/python3.9/site-packages/homeassistant/helpers/entity_component.py", line 161, in async_setup_entry
    raise ValueError("Config entry has already been setup!")
ValueError: Config entry has already been setup!
2022-11-18 09:05:23.257 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry xxxxxxxxxxx.ddns.net for update
Traceback (most recent call last):
  File "/home/homeassistant/.pyenv/versions/3.9.15/lib/python3.9/site-packages/homeassistant/config_entries.py", line 365, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/home/homeassistant/.pyenv/versions/3.9.15/lib/python3.9/site-packages/homeassistant/components/update/__init__.py", line 115, in async_setup_entry
    return await component.async_setup_entry(entry)
  File "/home/homeassistant/.pyenv/versions/3.9.15/lib/python3.9/site-packages/homeassistant/helpers/entity_component.py", line 161, in async_setup_entry
    raise ValueError("Config entry has already been setup!")
ValueError: Config entry has already been setup!
2022-11-18 09:05:23.266 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry xxxxxxxxxxx.ddns.net for binary_sensor
Traceback (most recent call last):
  File "/home/homeassistant/.pyenv/versions/3.9.15/lib/python3.9/site-packages/homeassistant/config_entries.py", line 365, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/home/homeassistant/.pyenv/versions/3.9.15/lib/python3.9/site-packages/homeassistant/components/binary_sensor/__init__.py", line 169, in async_setup_entry
    return await component.async_setup_entry(entry)
  File "/home/homeassistant/.pyenv/versions/3.9.15/lib/python3.9/site-packages/homeassistant/helpers/entity_component.py", line 161, in async_setup_entry
    raise ValueError("Config entry has already been setup!")
ValueError: Config entry has already been setup!

```

<img width="309" alt="Screenshot 2022-11-18 alle 09 08 54" src="https://user-images.githubusercontent.com/909743/202664644-08b16d60-edef-4379-b37c-09e0d166eaa1.png">

i've no idea where it gets the internal ip from :-\

**Comment by JurajNyiri** [comment]
Please enable debug logs for this integration and onvif from home assistant, reboot and send logs

**Comment by JurajNyiri** [comment]
And could you check if it works as expected via the Home Assistant onvif integration?

**Comment by fballiano** [comment]
Also the onvif implementation has the same problem, but I think I found something.

there are 3 interesting logs, in the first one (http://obfuscated.ddns.net:2020/onvif/device_service) the system receives back the internal IP address.

then another call a bit later is done to the internal address:

```
2022-11-18 13:59:36.012 DEBUG (MainThread) [zeep.transports] HTTP Response from http://obfuscated.ddns.net:2020/onvif/device_service (status: 200):
b'<?xml version="1.0" encoding="UTF-8"?>
<SOAP-ENV:Envelope xmlns:SOAP-ENV="http://www.w3.org/2003/05/soap-envelope" xmlns:SOAP-ENC="http://www.w3.org/2003/05/soap-encoding" xmlns:chan="http://schemas.microsoft.com/ws/2005/02/duplex" xmlns:tan="http://www.onvif.org/ver20/analytics/wsdl" xmlns:tdn="http://www.onvif.org/ver10/network/wsdl" xmlns:tds="http://www.onvif.org/ver10/device/wsdl" xmlns:ter="http://www.onvif.org/ver10/error" xmlns:tev="http://www.onvif.org/ver10/events/wsdl" xmlns:timg="http://www.onvif.org/ver20/imaging/wsdl" xmlns:tns1="http://www.onvif.org/ver10/topics" xmlns:trp="http://www.onvif.org/ver10/replay/wsdl" xmlns:trt="http://www.onvif.org/ver10/media/wsdl" xmlns:tt="http://www.onvif.org/ver10/schema" xmlns:wsa="http://schemas.xmlsoap.org/ws/2004/08/addressing" xmlns:wsa5="http://www.w3.org/2005/08/addressing" xmlns:wsdd="http://schemas.xmlsoap.org/ws/2005/04/discovery" xmlns:wsnt="http://docs.oasis-open.org/wsn/b-2" xmlns:wsrfbf="http://docs.oasis-open.org/wsrf/bf-2" xmlns:wsrfr="http://docs.oasis-open.org/wsrf/r-2" xmlns:wsse="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-secext-1.0.xsd" xmlns:wstop="http://docs.oasis-open.org/wsn/t-1" xmlns:wsu="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd" xmlns:xmime="http://tempuri.org/xmime.xsd" xmlns:xop="http://www.w3.org/2004/08/xop/include" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
   <SOAP-ENV:Header />
   <SOAP-ENV:Body>
      <tds:GetCapabilitiesResponse>
         <tds:Capabilities>
            <tt:Analytics>
               <tt:XAddr>http://192.168.1.131:2020/onvif/service</tt:XAddr>
               <tt:RuleSupport>true</tt:RuleSupport>
               <tt:AnalyticsModuleSupport>true</tt:AnalyticsModuleSupport>
            </tt:Analytics>
            <tt:Device>
               <tt:XAddr>http://192.168.1.131:2020/onvif/service</tt:XAddr>
               <tt:Network>
                  <tt:IPFilter>false</tt:IPFilter>
                  <tt:ZeroConfiguration>false</tt:ZeroConfiguration>
                  <tt:IPVersion6>false</tt:IPVersion6>
                  <tt:DynDNS>false</tt:DynDNS>
                  <tt:Extension>
                     <tt:Dot11Configuration>true</tt:Dot11Configuration>
                  </tt:Extension>
               </tt:Network>
               <tt:System>
                  <tt:DiscoveryResolve>false</tt:DiscoveryResolve>
                  <tt:DiscoveryBye>true</tt:DiscoveryBye>
                  <tt:RemoteDiscovery>false</tt:RemoteDiscovery>
                  <tt:SystemBackup>false</tt:SystemBackup>
                  <tt:SystemLogging>false</tt:SystemLogging>
                  <tt:FirmwareUpgrade>false</tt:FirmwareUpgrade>
                  <tt:AutoRebootSupport>true</tt:AutoRebootSupport>
                  <tt:SupportedVersions>
                     <tt:Major>20</tt:Major>
                     <tt:Minor>6</tt:Minor>
                  </tt:SupportedVersions>
                  <tt:Extension>
                     <tt:HttpFirmwareUpgrade>false</tt:HttpFirmwareUpgrade>
                     <tt:HttpSystemBackup>false</tt:HttpSystemBackup>
                     <tt:HttpSystemLogging>false</tt:HttpSystemLogging>
                     <tt:HttpSupportInformation>false</tt:HttpSupportInformation>
                  </tt:Extension>
               </tt:System>
               <tt:IO />
               <tt:Security>
                  <tt:TLS1.1>false</tt:TLS1.1>
                  <tt:TLS1.2>false</tt:TLS1.2>
                  <tt:OnboardKeyGeneration>false</tt:OnboardKeyGeneration>
                  <tt:AccessPolicyConfig>false</tt:AccessPolicyConfig>
                  <tt:X.509Token>false</tt:X.509Token>
                  <tt:SAMLToken>false</tt:SAMLToken>
                  <tt:KerberosToken>false</tt:KerberosToken>
                  <tt:RELToken>false</tt:RELToken>
               </tt:Security>
            </tt:Device>
            <tt:Events>
               <tt:XAddr>http://192.168.1.131:2020/onvif/service</tt:XAddr>
               <tt:WSSubscriptionPolicySupport>true</tt:WSSubscriptionPolicySupport>
               <tt:WSPullPointSupport>true</tt:WSPullPointSupport>
               <tt:WSPausableSubscriptionManagerInterfaceSupport>false</tt:WSPausableSubscriptionManagerInterfaceSupport>
            </tt:Events>
            <tt:Imaging>
               <tt:XAddr>http://192.168.1.131:2020/onvif/service</tt:XAddr>
               <tt:WDRSupport>false</tt:WDRSupport>
               <tt:FlipSupport>false</tt:FlipSupport>
               <tt:RotateSupport>false</tt:RotateSupport>
            </tt:Imaging>
            <tt:Media>
               <tt:XAddr>http://192.168.1.131:2020/onvif/service</tt:XAddr>
               <tt:StreamingCapabilities>
                  <tt:RTPMulticast>false</tt:RTPMulticast>
                  <tt:RTP_TCP>true</tt:RTP_TCP>
                  <tt:RTP_RTSP_TCP>true</tt:RTP_RTSP_TCP>
               </tt:StreamingCapabilities>
            </tt:Media>
            <tt:Extension>
               <tt:DeviceIO>
                  <tt:XAddr />
                  <tt:VideoSources>0</tt:VideoSources>
                  <tt:VideoOutputs>0</tt:VideoOutputs>
                  <tt:AudioSources>1</tt:AudioSources>
                  <tt:AudioOutputs>0</tt:AudioOutputs>
                  <tt:RelayOutputs>0</tt:RelayOutputs>
               </tt:DeviceIO>
            </tt:Extension>
         </tds:Capabilities>
      </tds:GetCapabilitiesResponse>
   </SOAP-ENV:Body>
</SOAP-ENV:Envelope>'

--CUT--

2022-11-18 13:59:42.702 DEBUG (MainThread) [zeep.wsdl.wsdl] Adding service: MediaService
2022-11-18 13:59:42.836 DEBUG (MainThread) [zeep.transports] HTTP Post to http://192.168.1.131:2020/onvif/service:
b'<?xml version="1.0" encoding="UTF-8"?>
<soap-env:Envelope xmlns:soap-env="http://www.w3.org/2003/05/soap-envelope">
   <soap-env:Header>
      <wsse:Security xmlns:wsse="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-secext-1.0.xsd">
         <wsse:UsernameToken>
            <wsse:Username>obfuscated</wsse:Username>
            <wsse:Password Type="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-username-token-profile-1.0#PasswordDigest">B6ue6+GQ9721BuFqZlZuknB67Sg=</wsse:Password>
            <wsse:Nonce EncodingType="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-soap-message-security-1.0#Base64Binary">hTQe56z4f0pngkeiiGeISQ==</wsse:Nonce>
            <wsu:Created xmlns:wsu="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd">2022-11-18T13:59:42+00:00</wsu:Created>
         </wsse:UsernameToken>
      </wsse:Security>
   </soap-env:Header>
   <soap-env:Body>
      <ns0:GetProfiles xmlns:ns0="http://www.onvif.org/ver10/media/wsdl" />
   </soap-env:Body>
</soap-env:Envelope>'

```

I guess the `Device/XAddr` is used to make that second call?

**Comment by JurajNyiri** [comment]
This integration reuses the functionality of Home Assistant onvif for events. In this case there is nothing I can do without reimplementing the whole thing.

I recommend opening issue with home assistant onvif integration.
