### ISSUE TITLE
Unreliable camera.snapshot or camera.record

### ISSUE THREAD

**Issue by momala454** [JurajNyiri/HomeAssistant-Tapo-Control#258]
### Description

Taking camera.snapshot sometimes doesn't take anything and no error on the logs.
But i've seen on the log BEFORE i ask a snapshot :
2022-12-07 09:30:59.982 ERROR (stream_worker) [homeassistant.components.stream.stream.camera.tapo_camera_d193_hd_stream] Error from stream worker: Stream ended; no additional packets

and sometimes, using camera.record start doing a mp4.tmp file then it crashes

I have a tapo c200 and I enabled stream both on the HD stream and on the plugin options. I have restarted home assistant and the camera after the modifications.

Sometime i've saw also that with lookback, i've seen a mp4 file with some time before the event, and after, but not during, so a gap of like 2 minutes between

Here is a log where the mp4.tmp is crashed

```
2022-12-07 09:28:40.616 ERROR (stream_worker) [homeassistant.components.stream.stream.camera.tapo_camera_d193_hd_stream] Error from stream worker: Stream ended; no additional packets
2022-12-07 09:29:00.476 ERROR (MainThread) [homeassistant.core] Error executing service: <ServiceCall camera.record (c:01GKNV5AQ3EE1MB7S4CCY3TYGD): filename=Template("/media/camera/Tapo_Camera_D193/2022-12-07_09-27-45/Snapshot.mp4"), lookback=30, duration=60, entity_id=['camera.tapo_camera_d193_hd_stream']>
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/core.py", line 1762, in catch_exceptions
    await coro_or_task
  File "/usr/src/homeassistant/homeassistant/core.py", line 1781, in _execute_service
    await cast(Callable[[ServiceCall], Awaitable[None]], handler.job.target)(
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 208, in handle_service
    await service.entity_service_call(
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 678, in entity_service_call
    future.result()  # pop exception if have
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 943, in async_request_call
    await coro
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 715, in _handle_entity_call
    await result
  File "/usr/src/homeassistant/homeassistant/components/camera/__init__.py", line 981, in async_handle_record_service
    await stream.async_record(
  File "/usr/src/homeassistant/homeassistant/components/stream/__init__.py", line 528, in async_record
    await recorder.async_record()
  File "/usr/src/homeassistant/homeassistant/components/stream/recorder.py", line 195, in async_record
    await self._hass.async_add_executor_job(
  File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/src/homeassistant/homeassistant/components/stream/recorder.py", line 145, in write_segment
    output.mux(packet)
  File "av/container/output.pyx", line 212, in av.container.output.OutputContainer.mux
  File "av/container/output.pyx", line 233, in av.container.output.OutputContainer.mux_one
  File "av/container/core.pyx", line 292, in av.container.core.Container.err_check
  File "av/error.pyx", line 336, in av.error.err_check
av.error.ValueError: [Errno 22] Invalid argument: '/media/camera/Tapo_Camera_D193/2022-12-07_09-27-45/Snapshot.mp4.tmp'; last error log: [mp4] Application provided invalid, non monotonically increasing dts to muxer in stream 0: 5405401 >= 4848899

```

### Reproduction Steps

service: camera.snapshot
data:
  filename: /media/camera/Tapo_Camera_D193/2022-12-07_09-31-26/Snapshot.jpg
target:
  entity_id: camera.tapo_camera_d193_hd_stream

service: camera.record
target:
  entity_id: camera.tapo_camera_d193_hd_stream
data:
  filename: /media/camera/Tapo_Camera_D193/2022-12-07_09-31-26/Snapshot.mp4
  lookback: 30
  duration: 60

### Expected behavior

a jpg and a mp4 every time

### Device Firmware

1.1.19 Build 220627 Rel.33188n(4555)

### Using stream component

Yes

### Does camera work via official integrations?

Yes

### Camera has all attributes filled out in developer tools

Yes

### HASS Environment

docker on raspbian

### Search for similar issues

Yes

**Comment by JurajNyiri** [comment]
Not an integration issue, try it with onvif for example and then open issue with Home Assistant.
