### ISSUE TITLE
Retrying setup: None

### ISSUE THREAD

**Issue by STUKguy** [JurajNyiri/HomeAssistant-Tapo-Control#267]
### Description

Hi,

When ever i restart my HA (Developers tools > restart) my Tapo Control keeps coming up with "Retrying setup: None" it will show this for a minute then it will try initializing and then show the error again, I've tried reloading, disabling and re enabling but nothing happens the only way i can fix it is if i delete my cameras and then add them again.

### Reproduction Steps

Developers tools
Restart

### Expected behavior

All integrations to work normally?

### If applicable, add error logs.

This error originated from a custom integration.

Logger: custom_components.tapo_control
Source: custom_components/tapo_control/__init__.py:436
Integration: Tapo: Cameras Control (documentation, issues)
First occurred: 7:50:02 PM (20 occurrences)
Last logged: 7:54:04 PM

Unable to connect to Tapo: Cameras Control controller: HTTPSConnectionPool(host='192.168.68.114', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f3a7fe38fa0>: Failed to establish a new connection: [Errno 113] Host is unreachable'))
Unable to connect to Tapo: Cameras Control controller: HTTPSConnectionPool(host='192.168.68.28', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f3a72a65c90>: Failed to establish a new connection: [Errno 113] Host is unreachable'))
Unable to connect to Tapo: Cameras Control controller: HTTPSConnectionPool(host='192.168.68.114', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f3a62c31ba0>: Failed to establish a new connection: [Errno 113] Host is unreachable'))
Unable to connect to Tapo: Cameras Control controller: HTTPSConnectionPool(host='192.168.68.28', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f3a62c30e50>: Failed to establish a new connection: [Errno 113] Host is unreachable'))
Unable to connect to Tapo: Cameras Control controller: HTTPSConnectionPool(host='192.168.68.114', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f3a62c93070>: Failed to establish a new connection: [Errno 113] Host is unreachable'))

### Device Firmware

1.3.0 Build 220830 Rel. 69909n(4555)

### Using stream component

Yes

### Does camera work via official integrations?

Yes

### Camera has all attributes filled out in developer tools

Yes

### HASS Environment

Home Assistant 2022.12.8 Core

### Search for similar issues

Yes

### Additional information

I ran debugging whilst the problem was happening i also have a Bluetooth issue but apparently there is no fix for it.

`2023-01-01 19:49:50.972 WARNING (SyncWorker_1) [homeassistant.loader] We found a custom integration tapo which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2023-01-01 19:49:50.973 WARNING (SyncWorker_1) [homeassistant.loader] We found a custom integration alexa_media which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2023-01-01 19:49:50.973 WARNING (SyncWorker_1) [homeassistant.loader] We found a custom integration watchman which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2023-01-01 19:49:50.973 WARNING (SyncWorker_1) [homeassistant.loader] We found a custom integration ble_monitor which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2023-01-01 19:49:50.973 WARNING (SyncWorker_1) [homeassistant.loader] We found a custom integration hildebrandglow_dcc which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2023-01-01 19:49:50.973 WARNING (SyncWorker_1) [homeassistant.loader] We found a custom integration whatspie which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2023-01-01 19:49:50.974 WARNING (SyncWorker_1) [homeassistant.loader] We found a custom integration hacs which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2023-01-01 19:49:50.975 WARNING (SyncWorker_1) [homeassistant.loader] We found a custom integration tapo_control which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2023-01-01 19:49:50.976 WARNING (SyncWorker_1) [homeassistant.loader] We found a custom integration localtuya which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2023-01-01 19:49:50.976 WARNING (SyncWorker_1) [homeassistant.loader] We found a custom integration sonoff which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2023-01-01 19:49:50.976 WARNING (SyncWorker_1) [homeassistant.loader] We found a custom integration eufy_security which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2023-01-01 19:49:53.637 WARNING (MainThread) [homeassistant.config_entries] Config entry '48:02:83:02:89:8C' for bluetooth integration not ready yet: hci0 (48:02:83:02:89:8C): Failed to start Bluetooth: [org.bluez.Error.InProgress] Operation already in progress; Retrying in background
2023-01-01 19:49:57.923 WARNING (MainThread) [homeassistant.components.systemmonitor.sensor] Cannot read CPU / processor temperature information
2023-01-01 19:49:57.946 ERROR (SyncWorker_4) [homeassistant.components.command_line] Command failed (with return code 1): cat /sys/class/thermal/thermal_zone0/temp
2023-01-01 19:49:58.411 WARNING (MainThread) [custom_components.ble_monitor.bt_helpers] hci0 (48:02:83:02:89:8C) have no BT LE capabilities and will be ignored.
2023-01-01 19:50:00.195 ERROR (MainThread) [homeassistant.components.life360] Abba: Lost Connection: This user has lost connection to Life360. Visit our troubleshooting guide to help them reconnect.
2023-01-01 19:50:00.200 ERROR (MainThread) [homeassistant.components.life360] Amma: Lost Connection: This user has lost connection to Life360. Visit our troubleshooting guide to help them reconnect.
2023-01-01 19:50:02.812 ERROR (MainThread) [custom_components.tapo_control] Unable to connect to Tapo: Cameras Control controller: HTTPSConnectionPool(host='192.168.68.28', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f3a6b8170a0>: Failed to establish a new connection: [Errno 113] Host is unreachable'))
2023-01-01 19:50:02.816 WARNING (MainThread) [homeassistant.config_entries] Config entry '192.168.68.28' for tapo_control integration not ready yet: None; Retrying in background
2023-01-01 19:50:02.818 ERROR (MainThread) [custom_components.tapo_control] Unable to connect to Tapo: Cameras Control controller: HTTPSConnectionPool(host='192.168.68.114', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f3a6b816890>: Failed to establish a new connection: [Errno 113] Host is unreachable'))
2023-01-01 19:50:02.819 WARNING (MainThread) [homeassistant.config_entries] Config entry '192.168.68.114' for tapo_control integration not ready yet: None; Retrying in background
2023-01-01 19:50:11.450 ERROR (MainThread) [custom_components.tapo_control] Unable to connect to Tapo: Cameras Control controller: HTTPSConnectionPool(host='192.168.68.114', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f3a646c62f0>: Failed to establish a new connection: [Errno 113] Host is unreachable'))
2023-01-01 19:50:11.453 ERROR (MainThread) [custom_components.tapo_control] Unable to connect to Tapo: Cameras Control controller: HTTPSConnectionPool(host='192.168.68.28', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f3a646c5960>: Failed to establish a new connection: [Errno 113] Host is unreachable'))
2023-01-01 19:50:16.122 WARNING (MainThread) [homeassistant.config_entries] Config entry '48:02:83:02:89:8C' for bluetooth integration not ready yet: hci0 (48:02:83:02:89:8C): Failed to start Bluetooth: [org.bluez.Error.InProgress] Operation already in progress; Retrying in background
2023-01-01 19:50:24.571 ERROR (MainThread) [custom_components.tapo_control] Unable to connect to Tapo: Cameras Control controller: HTTPSConnectionPool(host='192.168.68.28', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f3a62c30970>: Failed to establish a new connection: [Errno 113] Host is unreachable'))
2023-01-01 19:50:24.574 ERROR (MainThread) [custom_components.tapo_control] Unable to connect to Tapo: Cameras Control controller: HTTPSConnectionPool(host='192.168.68.114', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f3a62c30f70>: Failed to establish a new connection: [Errno 113] Host is unreachable'))
2023-01-01 19:50:32.873 WARNING (MainThread) [bluetooth_auto_recovery.recover] Bluetooth adapter hci0 [48:02:83:02:89:8C] successfully turned back ON
2023-01-01 19:50:47.675 ERROR (MainThread) [custom_components.tapo_control] Unable to connect to Tapo: Cameras Control controller: HTTPSConnectionPool(host='192.168.68.28', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f3a62c30d30>: Failed to establish a new connection: [Errno 113] Host is unreachable'))
2023-01-01 19:50:47.679 ERROR (MainThread) [custom_components.tapo_control] Unable to connect to Tapo: Cameras Control controller: HTTPSConnectionPool(host='192.168.68.114', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f3a62c337f0>: Failed to establish a new connection: [Errno 113] Host is unreachable'))
2023-01-01 19:50:58.029 ERROR (SyncWorker_7) [homeassistant.components.command_line] Command failed (with return code 1): cat /sys/class/thermal/thermal_zone0/temp
2023-01-01 19:51:30.747 ERROR (MainThread) [custom_components.tapo_control] Unable to connect to Tapo: Cameras Control controller: HTTPSConnectionPool(host='192.168.68.28', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f3a72a65f90>: Failed to establish a new connection: [Errno 113] Host is unreachable'))
2023-01-01 19:51:30.750 ERROR (MainThread) [custom_components.tapo_control] Unable to connect to Tapo: Cameras Control controller: HTTPSConnectionPool(host='192.168.68.114', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f3a62d68580>: Failed to establish a new connection: [Errno 113] Host is unreachable'))
2023-01-01 19:51:58.027 ERROR (SyncWorker_2) [homeassistant.components.command_line] Command failed (with return code 1): cat /sys/class/thermal/thermal_zone0/temp
2023-01-01 19:52:27.638 ERROR (MainThread) [homeassistant.components.bluetooth.scanner] hci0 (48:02:83:02:89:8C): Failed to restart Bluetooth scanner: hci0 (48:02:83:02:89:8C): Failed to start Bluetooth: [org.bluez.Error.InProgress] Operation already in progress
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/bluetooth/scanner.py", line 229, in _async_start
    await self.scanner.start()  # type: ignore[no-untyped-call]
  File "/usr/local/lib/python3.10/site-packages/bleak/__init__.py", line 156, in start
    await self._backend.start()
  File "/usr/local/lib/python3.10/site-packages/bleak/backends/bluezdbus/scanner.py", line 191, in start
    self._stop = await manager.active_scan(
  File "/usr/local/lib/python3.10/site-packages/bleak/backends/bluezdbus/manager.py", line 368, in active_scan
    assert_reply(reply)
  File "/usr/local/lib/python3.10/site-packages/bleak/backends/bluezdbus/utils.py", line 20, in assert_reply
    raise BleakDBusError(reply.error_name, reply.body)
bleak.exc.BleakDBusError: [org.bluez.Error.InProgress] Operation already in progress

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/bluetooth/scanner.py", line 364, in _async_scanner_watchdog
    await self._async_start()
  File "/usr/src/homeassistant/homeassistant/components/bluetooth/scanner.py", line 310, in _async_start
    raise ScannerStartError(
homeassistant.components.bluetooth.scanner.ScannerStartError: hci0 (48:02:83:02:89:8C): Failed to start Bluetooth: [org.bluez.Error.InProgress] Operation already in progress
2023-01-01 19:52:35.898 ERROR (MainThread) [custom_components.tapo_control] Unable to connect to Tapo: Cameras Control controller: HTTPSConnectionPool(host='192.168.68.28', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f3a72a64910>: Failed to establish a new connection: [Errno 113] Host is unreachable'))
2023-01-01 19:52:35.901 WARNING (MainThread) [homeassistant.config_entries] Config entry '192.168.68.28' for tapo_control integration not ready yet: None; Retrying in background
2023-01-01 19:52:37.562 ERROR (MainThread) [custom_components.tapo_control] Unable to connect to Tapo: Cameras Control controller: HTTPSConnectionPool(host='192.168.68.114', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f3a62eca7a0>: Failed to establish a new connection: [Errno 113] Host is unreachable'))
2023-01-01 19:52:37.565 WARNING (MainThread) [homeassistant.config_entries] Config entry '192.168.68.114' for tapo_control integration not ready yet: None; Retrying in background
2023-01-01 19:52:43.963 ERROR (MainThread) [custom_components.tapo_control] Unable to connect to Tapo: Cameras Control controller: HTTPSConnectionPool(host='192.168.68.28', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f3a62e23e20>: Failed to establish a new connection: [Errno 113] Host is unreachable'))
2023-01-01 19:52:45.626 ERROR (MainThread) [custom_components.tapo_control] Unable to connect to Tapo: Cameras Control controller: HTTPSConnectionPool(host='192.168.68.114', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f3a6550fb80>: Failed to establish a new connection: [Errno 113] Host is unreachable'))
2023-01-01 19:52:57.082 ERROR (MainThread) [custom_components.tapo_control] Unable to connect to Tapo: Cameras Control controller: HTTPSConnectionPool(host='192.168.68.28', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f3a62b96470>: Failed to establish a new connection: [Errno 113] Host is unreachable'))
2023-01-01 19:52:57.632 ERROR (MainThread) [homeassistant.components.bluetooth.scanner] hci0 (48:02:83:02:89:8C): Failed to restart Bluetooth scanner: hci0 (48:02:83:02:89:8C): Failed to start Bluetooth: [org.bluez.Error.InProgress] Operation already in progress
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/bluetooth/scanner.py", line 229, in _async_start
    await self.scanner.start()  # type: ignore[no-untyped-call]
  File "/usr/local/lib/python3.10/site-packages/bleak/__init__.py", line 156, in start
    await self._backend.start()
  File "/usr/local/lib/python3.10/site-packages/bleak/backends/bluezdbus/scanner.py", line 191, in start
    self._stop = await manager.active_scan(
  File "/usr/local/lib/python3.10/site-packages/bleak/backends/bluezdbus/manager.py", line 368, in active_scan
    assert_reply(reply)
  File "/usr/local/lib/python3.10/site-packages/bleak/backends/bluezdbus/utils.py", line 20, in assert_reply
    raise BleakDBusError(reply.error_name, reply.body)
bleak.exc.BleakDBusError: [org.bluez.Error.InProgress] Operation already in progress

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/bluetooth/scanner.py", line 364, in _async_scanner_watchdog
    await self._async_start()
  File "/usr/src/homeassistant/homeassistant/components/bluetooth/scanner.py", line 310, in _async_start
    raise ScannerStartError(
homeassistant.components.bluetooth.scanner.ScannerStartError: hci0 (48:02:83:02:89:8C): Failed to start Bluetooth: [org.bluez.Error.InProgress] Operation already in progress
2023-01-01 19:52:58.029 ERROR (SyncWorker_2) [homeassistant.components.command_line] Command failed (with return code 1): cat /sys/class/thermal/thermal_zone0/temp
2023-01-01 19:52:58.747 ERROR (MainThread) [custom_components.tapo_control] Unable to connect to Tapo: Cameras Control controller: HTTPSConnectionPool(host='192.168.68.114', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f3a7fe38fa0>: Failed to establish a new connection: [Errno 113] Host is unreachable'))
2023-01-01 19:53:20.186 ERROR (MainThread) [custom_components.tapo_control] Unable to connect to Tapo: Cameras Control controller: HTTPSConnectionPool(host='192.168.68.28', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f3a72a65c90>: Failed to establish a new connection: [Errno 113] Host is unreachable'))
2023-01-01 19:53:21.850 ERROR (MainThread) [custom_components.tapo_control] Unable to connect to Tapo: Cameras Control controller: HTTPSConnectionPool(host='192.168.68.114', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f3a62c31ba0>: Failed to establish a new connection: [Errno 113] Host is unreachable'))
2023-01-01 19:53:27.627 ERROR (MainThread) [homeassistant.components.bluetooth.scanner] hci0 (48:02:83:02:89:8C): Failed to restart Bluetooth scanner: hci0 (48:02:83:02:89:8C): Failed to start Bluetooth: [org.bluez.Error.InProgress] Operation already in progress
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/bluetooth/scanner.py", line 229, in _async_start
    await self.scanner.start()  # type: ignore[no-untyped-call]
  File "/usr/local/lib/python3.10/site-packages/bleak/__init__.py", line 156, in start
    await self._backend.start()
  File "/usr/local/lib/python3.10/site-packages/bleak/backends/bluezdbus/scanner.py", line 191, in start
    self._stop = await manager.active_scan(
  File "/usr/local/lib/python3.10/site-packages/bleak/backends/bluezdbus/manager.py", line 368, in active_scan
    assert_reply(reply)
  File "/usr/local/lib/python3.10/site-packages/bleak/backends/bluezdbus/utils.py", line 20, in assert_reply
    raise BleakDBusError(reply.error_name, reply.body)
bleak.exc.BleakDBusError: [org.bluez.Error.InProgress] Operation already in progress

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/bluetooth/scanner.py", line 364, in _async_scanner_watchdog
    await self._async_start()
  File "/usr/src/homeassistant/homeassistant/components/bluetooth/scanner.py", line 310, in _async_start
    raise ScannerStartError(
homeassistant.components.bluetooth.scanner.ScannerStartError: hci0 (48:02:83:02:89:8C): Failed to start Bluetooth: [org.bluez.Error.InProgress] Operation already in progress
2023-01-01 19:53:57.651 ERROR (MainThread) [homeassistant.components.bluetooth.scanner] hci0 (48:02:83:02:89:8C): Failed to restart Bluetooth scanner: hci0 (48:02:83:02:89:8C): Failed to start Bluetooth: [org.bluez.Error.InProgress] Operation already in progress
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/bluetooth/scanner.py", line 229, in _async_start
    await self.scanner.start()  # type: ignore[no-untyped-call]
  File "/usr/local/lib/python3.10/site-packages/bleak/__init__.py", line 156, in start
    await self._backend.start()
  File "/usr/local/lib/python3.10/site-packages/bleak/backends/bluezdbus/scanner.py", line 191, in start
    self._stop = await manager.active_scan(
  File "/usr/local/lib/python3.10/site-packages/bleak/backends/bluezdbus/manager.py", line 368, in active_scan
    assert_reply(reply)
  File "/usr/local/lib/python3.10/site-packages/bleak/backends/bluezdbus/utils.py", line 20, in assert_reply
    raise BleakDBusError(reply.error_name, reply.body)
bleak.exc.BleakDBusError: [org.bluez.Error.InProgress] Operation already in progress

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/bluetooth/scanner.py", line 364, in _async_scanner_watchdog
    await self._async_start()
  File "/usr/src/homeassistant/homeassistant/components/bluetooth/scanner.py", line 310, in _async_start
    raise ScannerStartError(
homeassistant.components.bluetooth.scanner.ScannerStartError: hci0 (48:02:83:02:89:8C): Failed to start Bluetooth: [org.bluez.Error.InProgress] Operation already in progress
2023-01-01 19:53:58.031 ERROR (SyncWorker_0) [homeassistant.components.command_line] Command failed (with return code 1): cat /sys/class/thermal/thermal_zone0/temp
2023-01-01 19:54:03.258 ERROR (MainThread) [custom_components.tapo_control] Unable to connect to Tapo: Cameras Control controller: HTTPSConnectionPool(host='192.168.68.28', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f3a62c30e50>: Failed to establish a new connection: [Errno 113] Host is unreachable'))
2023-01-01 19:54:04.922 ERROR (MainThread) [custom_components.tapo_control] Unable to connect to Tapo: Cameras Control controller: HTTPSConnectionPool(host='192.168.68.114', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f3a62c93070>: Failed to establish a new connection: [Errno 113] Host is unreachable'))
`

**Comment by JurajNyiri** [comment]
Errors show your camera being unreachable. Probably the environment, network or camera needs to be fixed.

**Comment by STUKguy** [comment]
> Errors show your camera being unreachable. Probably the environment, network or camera needs to be fixed.

Let me explain again. There is no change in the environment it is the same as it was yesterday and the day before that, the network and camera are fine. i only have this issue when ever i restart my HA
