### ISSUE TITLE
Pressing movement buttons result in a KeyError for "movement_angle"

### ISSUE THREAD

**Issue by lennart-bader** [JurajNyiri/HomeAssistant-Tapo-Control#268]
### Description

When you use the movement buttons (e.g., `button.camXY_move_right`), a click will result in a KeyError, since the  `movement_angle` is unavailable / unset.
This occurs for both cases:
1. When you click on the entity and press the "Press" button / action
2. When you manually call the `button.press` service

The camera position does not change.

### Reproduction Steps

1. Select a movement entity button for your camera
2. Press the "Press" button

### Expected behavior

No error message and a camera movement in the selected direction.

### If applicable, add error logs.

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 193, in handle_call_service
    await hass.services.async_call(
  File "/usr/src/homeassistant/homeassistant/core.py", line 1704, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1741, in _execute_service
    await cast(Callable[[ServiceCall], Awaitable[None]], handler.job.target)(
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 204, in handle_service
    await service.entity_service_call(
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 680, in entity_service_call
    future.result()  # pop exception if have
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 964, in async_request_call
    await coro
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 717, in _handle_entity_call
    await result
  File "/usr/src/homeassistant/homeassistant/components/button/__init__.py", line 114, in _async_press_action
    await self.async_press()
  File "/config/custom_components/tapo_control/button.py", line 176, in async_press
    degrees = self._entry["movement_angle"]
KeyError: 'movement_angle'

### Device Firmware

1.1.15 Build 211111 Rel.34670n(4555)

### Using stream component

Yes

### Does camera work via official integrations?

Yes

### Camera has all attributes filled out in developer tools

Yes

### HASS Environment

Docker on Synology NAS

### Search for similar issues

Yes

**Comment by JurajNyiri** [comment]
Which camera do you have?

**Comment by JurajNyiri** [comment]
Does the issue persists through restart? Is the entity movement number not created at all?

**Comment by lennart-bader** [comment]
It's a C200.
Restarts do not solve the issue.

And no, there is no entity with "movement" in its name, unfortunately.

I just upgraded from 3.X to version 4 of your integration.

**Comment by lennart-bader** [comment]
I'm sorry for the report, it's actually not an issue with the integration, but my fault as I missed to reset the docker container after the latest update - hence, I ran an outdated version of HomeAssistant (2022.06), while this integration requires the `RestoreNumber` which has been added to HomeAssistant's core in June 2022.

After upgrading to 2023.1.0, the issue is resolved - maybe you could add the (minimum) required version to the README?

Sorry again for the misleading bug report, thanks for your great integration!

**Comment by JurajNyiri** [comment]
Thank you, I have updated the minimum required version in hacs.json.
