### ISSUE TITLE
Tapo C225 causes excessive logging

### ISSUE THREAD

**Issue by MatsNorin** [JurajNyiri/HomeAssistant-Tapo-Control#294]
### Description

Every 10-20 seconds the Tapo-Control component logs an exception

### Reproduction Steps

1. Go to HA Settings - Logs - Home assistant core
2. "Unexpected error fetching Tapo resource data: illegal status line:..." is shown
3. Download full logs
4. Lots of errors as seen below

### Expected behavior

Handling of the exception in code with one error/warning in log

### If applicable, add error logs.

This error originated from a custom integration.

Logger: custom_components.tapo_control
Source: components/onvif/event.py:82
Integration: Tapo: Cameras Control (documentation, issues)
First occurred: 11:39:55 (1047 occurrences)
Last logged: 16:01:36

Unexpected error fetching Tapo resource status data: illegal status line: bytearray(b'POST /onvif/service\x00HTTP/1.1\x00\x00Host\x00 192.168.0.178:2020\x00\x00Accept\x00 */*\x00\x00Accept-Encoding\x00 gzip, deflate, br\x00\x00Connection\x00 keep-alive\x00\x00User-Agent\x00 ZeHTTP/1.1 500 Internal Server Error')
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/httpcore/_exceptions.py", line 10, in map_exceptions
    yield
  File "/usr/local/lib/python3.10/site-packages/httpcore/_async/http11.py", line 188, in _receive_event
    event = self._h11_state.next_event()
  File "/usr/local/lib/python3.10/site-packages/h11/_connection.py", line 487, in next_event
    exc._reraise_as_remote_protocol_error()
  File "/usr/local/lib/python3.10/site-packages/h11/_util.py", line 77, in _reraise_as_remote_protocol_error
    raise self
  File "/usr/local/lib/python3.10/site-packages/h11/_connection.py", line 469, in next_event
    event = self._extract_next_receive_event()
  File "/usr/local/lib/python3.10/site-packages/h11/_connection.py", line 411, in _extract_next_receive_event
    event = self._reader(self._receive_buffer)
  File "/usr/local/lib/python3.10/site-packages/h11/_readers.py", line 104, in maybe_read_from_SEND_RESPONSE_server
    matches = validate(status_line_re, lines[0], "illegal status line: {!r}", lines[0])
  File "/usr/local/lib/python3.10/site-packages/h11/_util.py", line 91, in validate
    raise LocalProtocolError(msg)
h11._util.RemoteProtocolError: illegal status line: bytearray(b'POST /onvif/service\x00HTTP/1.1\x00\x00Host\x00 192.168.0.178:2020\x00\x00Accept\x00 */*\x00\x00Accept-Encoding\x00 gzip, deflate, br\x00\x00Connection\x00 keep-alive\x00\x00User-Agent\x00 ZeHTTP/1.1 500 Internal Server Error')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/httpx/_transports/default.py", line 60, in map_httpcore_exceptions
    yield
  File "/usr/local/lib/python3.10/site-packages/httpx/_transports/default.py", line 353, in handle_async_request
    resp = await self._pool.handle_async_request(req)
  File "/usr/local/lib/python3.10/site-packages/httpcore/_async/connection_pool.py", line 253, in handle_async_request
    raise exc
  File "/usr/local/lib/python3.10/site-packages/httpcore/_async/connection_pool.py", line 237, in handle_async_request
    response = await connection.handle_async_request(request)
  File "/usr/local/lib/python3.10/site-packages/httpcore/_async/connection.py", line 90, in handle_async_request
    return await self._connection.handle_async_request(request)
  File "/usr/local/lib/python3.10/site-packages/httpcore/_async/http11.py", line 112, in handle_async_request
    raise exc
  File "/usr/local/lib/python3.10/site-packages/httpcore/_async/http11.py", line 91, in handle_async_request
    ) = await self._receive_response_headers(**kwargs)
  File "/usr/local/lib/python3.10/site-packages/httpcore/_async/http11.py", line 155, in _receive_response_headers
    event = await self._receive_event(timeout=timeout)
  File "/usr/local/lib/python3.10/site-packages/httpcore/_async/http11.py", line 187, in _receive_event
    with map_exceptions({h11.RemoteProtocolError: RemoteProtocolError}):
  File "/usr/local/lib/python3.10/contextlib.py", line 153, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/usr/local/lib/python3.10/site-packages/httpcore/_exceptions.py", line 14, in map_exceptions
    raise to_exc(exc)
httpcore.RemoteProtocolError: illegal status line: bytearray(b'POST /onvif/service\x00HTTP/1.1\x00\x00Host\x00 192.168.0.178:2020\x00\x00Accept\x00 */*\x00\x00Accept-Encoding\x00 gzip, deflate, br\x00\x00Connection\x00 keep-alive\x00\x00User-Agent\x00 ZeHTTP/1.1 500 Internal Server Error')

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 239, in _async_refresh
    self.data = await self._async_update_data()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 195, in _async_update_data
    return await self.update_method()
  File "/config/custom_components/tapo_control/__init__.py", line 221, in async_update_data
    ] = await setupEvents(hass, entry)
  File "/config/custom_components/tapo_control/utils.py", line 441, in setupEvents
    if await events.async_start():
  File "/usr/src/homeassistant/homeassistant/components/onvif/event.py", line 82, in async_start
    if await self.device.create_pullpoint_subscription():
  File "/usr/local/lib/python3.10/site-packages/onvif/client.py", line 311, in create_pullpoint_subscription
    pullpoint = await events.CreatePullPointSubscription()
  File "/usr/local/lib/python3.10/site-packages/zeep/proxy.py", line 64, in __call__
    return await self._proxy._binding.send_async(
  File "/usr/local/lib/python3.10/site-packages/zeep/wsdl/bindings/soap.py", line 156, in send_async
    response = await client.transport.post_xml(
  File "/usr/local/lib/python3.10/site-packages/zeep/transports.py", line 235, in post_xml
    response = await self.post(address, message, headers)
  File "/usr/local/lib/python3.10/site-packages/zeep/transports.py", line 220, in post
    response = await self.client.post(
  File "/usr/local/lib/python3.10/site-packages/httpx/_client.py", line 1848, in post
    return await self.request(
  File "/usr/local/lib/python3.10/site-packages/httpx/_client.py", line 1533, in request
    return await self.send(request, auth=auth, follow_redirects=follow_redirects)
  File "/usr/local/lib/python3.10/site-packages/httpx/_client.py", line 1620, in send
    response = await self._send_handling_auth(
  File "/usr/local/lib/python3.10/site-packages/httpx/_client.py", line 1648, in _send_handling_auth
    response = await self._send_handling_redirects(
  File "/usr/local/lib/python3.10/site-packages/httpx/_client.py", line 1685, in _send_handling_redirects
    response = await self._send_single_request(request)
  File "/usr/local/lib/python3.10/site-packages/httpx/_client.py", line 1722, in _send_single_request
    response = await transport.handle_async_request(request)
  File "/usr/local/lib/python3.10/site-packages/httpx/_transports/default.py", line 352, in handle_async_request
    with map_httpcore_exceptions():
  File "/usr/local/lib/python3.10/contextlib.py", line 153, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/usr/local/lib/python3.10/site-packages/httpx/_transports/default.py", line 77, in map_httpcore_exceptions
    raise mapped_exc(message) from exc
httpx.RemoteProtocolError: illegal status line: bytearray(b'POST /onvif/service\x00HTTP/1.1\x00\x00Host\x00 192.168.0.178:2020\x00\x00Accept\x00 */*\x00\x00Accept-Encoding\x00 gzip, deflate, br\x00\x00Connection\x00 keep-alive\x00\x00User-Agent\x00 ZeHTTP/1.1 500 Internal Server Error')

Enabled debug logging and got:
2023-02-25 16:34:36.931 DEBUG (MainThread) [custom_components.tapo_control] async_update_data - entry
2023-02-25 16:34:36.931 DEBUG (MainThread) [custom_components.tapo_control] Motion sensor or time sync is enabled.
2023-02-25 16:34:36.932 DEBUG (MainThread) [custom_components.tapo_control] Setting up subcription to motion sensor events...
2023-02-25 16:34:36.932 DEBUG (MainThread) [custom_components.tapo_control] setupEvents - entry
2023-02-25 16:34:36.932 DEBUG (MainThread) [custom_components.tapo_control] Setting up events...

...Exception as above...

2023-02-25 16:34:36.992 DEBUG (MainThread) [custom_components.tapo_control] Finished fetching Tapo resource status data in 0.061 seconds (success: False)

### Device Firmware

1.0.14 Build 220922 Rel.76344n

### Using stream component

Yes

### Does camera work via official integrations?

N/A

### Camera has all attributes filled out in developer tools

Yes

### HASS Environment

Raspberry Pi 4

### Search for similar issues

Yes

### Additional information

Tapo-Control integration works fine. Processor and memory on the Pi is fine. Assume the "Internal Server Error" means a problem on the C255? Can Tapo-Control handle the error so it don't flood the log with exceptions?

Edit:
Based on the debug log I unchecked the "Enable motion sensor" in the integration config and the exceptions stopped

**Comment by JurajNyiri** [comment]
We want this error, it is camera issue and it needs to be fixed on the camera. Nothing we can do about it.

**Comment by MatsNorin** [comment]
No doubt it's a camera issue causing the error. Tapo-Control writing a (long) log entry every 10 seconds is not.
Catching the exception, writing one log entry and then shutting down the attempts seems the friendly thing to do.

**Comment by JurajNyiri** [comment]
Please test with https://github.com/JurajNyiri/HomeAssistant-Tapo-Control/releases/tag/5.1.0 .

**Comment by MatsNorin** [comment]
Tested with 5.1.0 and it looks good. There is still an error but now it only logs two messages, and only one copy of each:

2023-04-18 15:58:19.698 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry 192.168.0.178 for sensor
<...>
ValueError: Config entry has already been setup!

2023-04-18 15:58:35.492 ERROR (MainThread) [custom_components.tapo_control] Unexpected error fetching Tapo resource status data: Server disconnected without sending a response.
<...>
httpx.RemoteProtocolError: Server disconnected without sending a response.

**Comment by JurajNyiri** [comment]
Thank you for confirming!

The errors you described are unrelated to this issue, so closing. Feel free to open new issues for those errors.
