### ISSUE TITLE
Invalid Config

### ISSUE THREAD

**Issue by msaphoto** [JurajNyiri/HomeAssistant-Tapo-Control#3]
Hello

I'm this message

"The following integrations and platforms could not be set up:

tapo_control
Please check your config."

My config is

tapo_control:
  - host: 192.168.0.102
    username: mxxxxxxxx
    password: Kxxxxxxxxx

Thank you

**Comment by JurajNyiri** [comment]
Hello,

please go to your log in Configuration -> Logs and see if there is some error message in there. 

Paste it here and we can see how to resolve this.

**Comment by msaphoto** [comment]
Logger: homeassistant.setup
Source: core.py:783
First occurred: 14:45:53 (1 occurrences)
Last logged: 14:45:53

Error during setup of component tapo_control
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 213, in _async_setup_component
    result = await task
  File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/tapo_control/__init__.py", line 345, in setup
    manualUpdate(entity_id, tapoConnector)
  File "/config/custom_components/tapo_control/__init__.py", line 62, in manualUpdate
    hass.states.set(entity_id, tapoData[entity_id]['state'], tapoData[entity_id]['attributes'])
  File "/usr/src/homeassistant/homeassistant/core.py", line 1006, in set
    run_callback_threadsafe(
  File "/usr/local/lib/python3.8/concurrent/futures/_base.py", line 439, in result
    return self.__get_result()
  File "/usr/local/lib/python3.8/concurrent/futures/_base.py", line 388, in __get_result
    raise self._exception
  File "/usr/src/homeassistant/homeassistant/util/async_.py", line 53, in run_callback
    future.set_result(callback(*args))
  File "/usr/src/homeassistant/homeassistant/core.py", line 1053, in async_set
    state = State(entity_id, new_state, attributes, last_changed, None, context)
  File "/usr/src/homeassistant/homeassistant/core.py", line 783, in __init__
    raise InvalidEntityFormatError(
homeassistant.exceptions.InvalidEntityFormatError: Invalid entity id encountered: tapo_control.chambre_thaã¯s. Format should be <domain>.<object_id>

**Comment by JurajNyiri** [comment]
Thank you this is helpful, what is your camera name in the app please? 
Use all the accents etc exactly like it is named in your app so that I can write a fix.

**Comment by msaphoto** [comment]
Thaïs

I removed the ï, and it's ok

thank you very much

**Comment by msaphoto** [comment]
I have a same problem when add my 2nd cam. (C100)

tapo_control:
  - host: 192.168.0.102
    username: ms....
    password: Ki....
  - host: 192.168.0.101
    username: ms.....
    password: Ki....

Name of cam is Salon

Logger: homeassistant.setup
Source: custom_components/tapo_control/__init__.py:335
First occurred: 16:44:07 (1 occurrences)
Last logged: 16:44:07

Error during setup of component tapo_control
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 213, in _async_setup_component
    result = await task
  File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/tapo_control/__init__.py", line 335, in setup
    tapoConnector = Tapo(host, username, password)
  File "/usr/local/lib/python3.8/site-packages/pytapo/__init__.py", line 28, in __init__
    self.presets = self.getPresets()
  File "/usr/local/lib/python3.8/site-packages/pytapo/__init__.py", line 384, in getPresets
    return self.getPresets()
  File "/usr/local/lib/python3.8/site-packages/pytapo/__init__.py", line 384, in getPresets
    return self.getPresets()
  File "/usr/local/lib/python3.8/site-packages/pytapo/__init__.py", line 384, in getPresets
    return self.getPresets()
  [Previous line repeated 965 more times]
  File "/usr/local/lib/python3.8/site-packages/pytapo/__init__.py", line 383, in getPresets
    self.refreshStok()
  File "/usr/local/lib/python3.8/site-packages/pytapo/__init__.py", line 48, in refreshStok
    res = requests.post(url, data = json.dumps(data), headers=self.headers, verify=False)
  File "/usr/local/lib/python3.8/site-packages/requests/api.py", line 119, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/requests/sessions.py", line 530, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.8/site-packages/requests/sessions.py", line 643, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/usr/local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 670, in urlopen
    httplib_response = self._make_request(
  File "/usr/local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 426, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/usr/local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 421, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/local/lib/python3.8/http/client.py", line 1347, in getresponse
    response.begin()
  File "/usr/local/lib/python3.8/http/client.py", line 331, in begin
    self.headers = self.msg = parse_headers(self.fp)
  File "/usr/local/lib/python3.8/http/client.py", line 225, in parse_headers
    return email.parser.Parser(_class=_class).parsestr(hstring)
  File "/usr/local/lib/python3.8/email/parser.py", line 67, in parsestr
    return self.parse(StringIO(text), headersonly=headersonly)
  File "/usr/local/lib/python3.8/email/parser.py", line 56, in parse
    feedparser.feed(data)
  File "/usr/local/lib/python3.8/email/feedparser.py", line 176, in feed
    self._call_parse()
  File "/usr/local/lib/python3.8/email/feedparser.py", line 180, in _call_parse
    self._parse()
  File "/usr/local/lib/python3.8/email/feedparser.py", line 295, in _parsegen
    if self._cur.get_content_maintype() == 'message':
  File "/usr/local/lib/python3.8/email/message.py", line 594, in get_content_maintype
    ctype = self.get_content_type()
  File "/usr/local/lib/python3.8/email/message.py", line 578, in get_content_type
    value = self.get('content-type', missing)
  File "/usr/local/lib/python3.8/email/message.py", line 471, in get
    return self.policy.header_fetch_parse(k, v)
  File "/usr/local/lib/python3.8/email/_policybase.py", line 316, in header_fetch_parse
    return self._sanitize_header(name, value)
  File "/usr/local/lib/python3.8/email/_policybase.py", line 287, in _sanitize_header
    if _has_surrogates(value):
  File "/usr/local/lib/python3.8/email/utils.py", line 57, in _has_surrogates
    s.encode()
RecursionError: maximum recursion depth exceeded while calling a Python object

**Comment by JurajNyiri** [comment]
Please create a new issue for this, it is a different issue. I will look into it after I deploy a fix for this one.
Please also specify camera model in the title there.

**Comment by JurajNyiri** [comment]
Accents bug was fixed in version 1.1.

https://github.com/JurajNyiri/HomeAssistant-Tapo-Control/releases/tag/1.1
