### ISSUE TITLE
Unexpected error fetching Tapo resource status data: ONVIFCamera.create_pullpoint_subscription() takes 1 positional argument but 2 were given

### ISSUE THREAD

**Issue by tjorim** [JurajNyiri/HomeAssistant-Tapo-Control#314]
### Description

Updated to Home Assistant 2023.4.5, now getting errors.

### Reproduction Steps

1. Update HA
2. Check error log

### Expected behavior

No errors

### If applicable, add error logs.

This error originated from a custom integration.

Logger: custom_components.tapo_control
Source: components/onvif/event.py:96
Integration: Tapo: Cameras Control (documentation, issues)
First occurred: 09:18:57 (34 occurrences)
Last logged: 09:27:14

Unexpected error fetching Tapo resource status data: ONVIFCamera.create_pullpoint_subscription() takes 1 positional argument but 2 were given
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 250, in _async_refresh
    self.data = await self._async_update_data()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 206, in _async_update_data
    return await self.update_method()
  File "/config/custom_components/tapo_control/__init__.py", line 235, in async_update_data
    await setupOnvif(hass, entry)
  File "/config/custom_components/tapo_control/utils.py", line 691, in setupOnvif
    hass.data[DOMAIN][entry.entry_id]["eventsSetup"] = await setupEvents(
  File "/config/custom_components/tapo_control/utils.py", line 701, in setupEvents
    if await events.async_start():
  File "/usr/src/homeassistant/homeassistant/components/onvif/event.py", line 96, in async_start
    if not await self.device.create_pullpoint_subscription(
TypeError: ONVIFCamera.create_pullpoint_subscription() takes 1 positional argument but 2 were given

### Device Firmware

1.3.0 Build 220830 Rel.69909n(4555)

### Using stream component

Yes

### Does camera work via official integrations?

N/A

### Camera has all attributes filled out in developer tools

Yes

### HASS Environment

Home Assistant Operating System

### Search for similar issues

Yes

## System Information

version | core-2023.4.5
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.10.10
os_name | Linux
os_version | 6.1.21-v8
arch | aarch64
timezone | Europe/Brussels
config_dir | /config

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
GitHub API Calls Remaining | 4974
Installed Version | 1.32.1
Stage | running
Available Repositories | 1272
Downloaded Repositories | 70
HACS Data | ok

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 10.0
-- | --
update_channel | beta
supervisor_version | supervisor-2023.04.0
agent_version | 1.5.1
docker_version | 23.0.3
disk_total | 458.4 GB
disk_used | 39.9 GB
healthy | true
supported | true
board | yellow
supervisor_api | ok
version_api | ok
installed_addons | AirCast (3.5.2), Spotify Connect (0.12.3), SSH & Web Terminal (13.1.0), File editor (5.5.0), Studio Code Server (5.5.6), Zigbee2MQTT (1.30.3-1), Home Assistant Google Drive Backup (0.110.3), MariaDB (2.5.2), phpMyAdmin (0.8.5), The Lounge (0.17.1), Glances (0.18.1), Tailscale (0.11.1), ZeroTier One (0.16.2), Nginx Proxy Manager (0.12.3), Uptime Kuma (0.7.2), WireGuard (0.8.0), CUPS Print Server (2.0.2), ESPHome (2023.3.2), Music Assistant BETA (2.0.0b27), Mosquitto broker (6.2.0)

</details>

<details><summary>Dashboards</summary>

dashboards | 3
-- | --
resources | 30
views | 14
mode | storage

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | June 11, 2022 at 07:18
-- | --
current_recorder_run | April 18, 2023 at 09:14
estimated_db_size | 7232.77 MiB
database_engine | mysql
database_version | 10.6.10

</details>

<details><summary>Spotify</summary>

api_endpoint_reachable | ok
-- | --

</details>

**Comment by aIexus** [comment]
The same issue after updating to HA Core 4.5

**Comment by JurajNyiri** [comment]
Please test with https://github.com/JurajNyiri/HomeAssistant-Tapo-Control/releases/tag/5.1.0 .

**Comment by aIexus** [comment]
Fixed!
Thanks!
