### ISSUE TITLE
button.*_manual_alarm_start and button.*_reboot are unavailable

### ISSUE THREAD

**Issue by jjvelar** [JurajNyiri/HomeAssistant-Tapo-Control#325]
### Description

Everything works OK but button.*_manual_alarm_start and button.*_reboot, as they appear as "unavailable".
Happens to C200 and C210 models

### Reproduction Steps

Just checking the status of these two buttons.

### Expected behavior

They should be available

### Device Firmware

1.3.5 (C200) / 1.3.3 (C210)

### Using stream component

Yes

### Does camera work via official integrations?

Yes

### Camera has all attributes filled out in developer tools

Yes

### HASS Environment

HASOS

### Search for similar issues

Yes

**Comment by JurajNyiri** [comment]
Are there any errors in the logs?

**Comment by jjvelar** [comment]
Thanks for replying. I am getting this error:

This error originated from a custom integration.

Logger: custom_components.tapo_control
Source: custom_components/tapo_control/utils.py:723
Integration: Tapo: Cameras Control (documentation, issues)
First occurred: 8:46:40 AM (13812 occurrences)
Last logged: 7:26:29 PM

Unexpected error fetching Tapo resource status data:
EventManager.async_start() missing 2 required positional arguments:
'try_pullpoint' and 'try_webhook'
Traceback (most recent call last):
  File
"/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line
258, in _async_refresh
    self.data = await self._async_update_data()
  File
"/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line
217, in _async_update_data
    return await self.update_method()
  File "/config/custom_components/tapo_control/__init__.py", line 229, in
async_update_data
    await setupOnvif(hass, entry)
  File "/config/custom_components/tapo_control/utils.py", line 713, in
setupOnvif
    hass.data[DOMAIN][entry.entry_id]["eventsSetup"] = await setupEvents(
  File "/config/custom_components/tapo_control/utils.py", line 723, in
setupEvents
    if await events.async_start():
TypeError: EventManager.async_start() missing 2 required positional
arguments: 'try_pullpoint' and 'try_webhook'

**Comment by JurajNyiri** [comment]
Use version https://github.com/JurajNyiri/HomeAssistant-Tapo-Control/releases/tag/5.1.6 with HA 2023.05.x
Use version https://github.com/JurajNyiri/HomeAssistant-Tapo-Control/releases/tag/5.1.2 with HA 2023.04.x

**Comment by jjvelar** [comment]
Hi, thanks for your quick response.

I am in HA 2023.06 beta so updated integration to 5.1.6.

I got this error so I had to manually install 5.1.6:

*You are running Home Assistant version '2023.5.0b6', but this repository
requires minimum version '2023.5.0' to be installed.*


After rebooting HA, these two entities are still unavailable/unknown.

Any other suggestions?

Thanks

**Comment by JurajNyiri** [comment]
There were breaking changes introduced yesterday to beta 6. Use beta 5 or stable for now until I fix this.

**Comment by jjvelar** [comment]
Ok, thanks for the update.

**Comment by jjvelar** [comment]
Hi
I am afraid it is not solved in my end.
Updated to 5.1.7 but these entities are still unavailable.
HA is in 2023.05 stable version.
Do you need anything else from my side? Can I provide any additional
information?
Thanks and best regards,

José

**Comment by JurajNyiri** [comment]
Yes, please send logs and make sure you actually updated properly.

**Comment by jjvelar** [comment]
I can confirm 5.1.7 is installed. Attached screen capture. And got these
two errors from Core log:

[image: image.png]

############# ERROR 1 ################
Logger: homeassistant.helpers.integration_platform
Source: loader.py:850
First occurred: 7:45:34 AM (7 occurrences)
Last logged: 10:37:23 AM

Unexpected error importing tapo_control/significant_change.py
Unexpected error importing tapo_control/system_health.py
Unexpected error importing tapo_control/logbook.py
Unexpected error importing tapo_control/group.py
Unexpected error importing tapo_control/hardware.py
Traceback (most recent call last):
  File
"/usr/src/homeassistant/homeassistant/helpers/integration_platform.py",
line 50, in _async_process_single_integration_platform_component
    platform = integration.get_platform(platform_name)
  File "/usr/src/homeassistant/homeassistant/loader.py", line 833, in
get_platform
    cache[full_name] = self._import_platform(platform_name)
  File "/usr/src/homeassistant/homeassistant/loader.py", line 850, in
_import_platform
    return importlib.import_module(f"{self.pkg_path}.{platform_name}")
  File "/usr/local/lib/python3.10/importlib/__init__.py", line 126, in
import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1004, in
_find_and_load_unlocked
ModuleNotFoundError: No module named 'custom_components.tapo_control -
copia.diagnostics'

############# ERROR 2 ################
This error originated from a custom integration.

Logger: custom_components.tapo_control
Source: custom_components/tapo_control - copia/utils.py:723
Integration: tapo_control (documentation, issues)
First occurred: 7:46:04 AM (3436 occurrences)
Last logged: 10:37:15 AM

Unexpected error fetching Tapo resource status data:
EventManager.async_start() missing 2 required positional arguments:
'try_pullpoint' and 'try_webhook'
Traceback (most recent call last):
  File
"/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line
258, in _async_refresh
    self.data = await self._async_update_data()
  File
"/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line
217, in _async_update_data
    return await self.update_method()
  File "/config/custom_components/tapo_control - copia/__init__.py", line
229, in async_update_data
    await setupOnvif(hass, entry)
  File "/config/custom_components/tapo_control - copia/utils.py", line 713,
in setupOnvif
    hass.data[DOMAIN][entry.entry_id]["eventsSetup"] = await setupEvents(
  File "/config/custom_components/tapo_control - copia/utils.py", line 723,
in setupEvents
    if await events.async_start():
TypeError: EventManager.async_start() missing 2 required positional
arguments: 'try_pullpoint' and 'try_webhook'

**Comment by JurajNyiri** [comment]
############# ERROR 2 ################

You have not installed 5.1.7, this error is fixed in it.

```
Unexpected error importing tapo_control/significant_change.py
Unexpected error importing tapo_control/system_health.py
Unexpected error importing tapo_control/logbook.py
Unexpected error importing tapo_control/group.py
Unexpected error importing tapo_control/hardware.py
```

I do not know what you have added to tapo_control folder, but these files are not part of this integration. Install it properly, ideally using HACS.

**Comment by jjvelar** [comment]
me neither because I checked the /config/custom_components/tapo_contro
folder and, as an example, "logbook.py" file is not there!
should I delete the whole folder and install the integration again? and, if
that's the case, is there any way I can keep all my cameras configuration?

[image: image.png]

**Comment by jjvelar** [comment]
remove all cameras
uninstalled integration
verified folder was deleted
reboot HA
installed integration
reboot HA
installed cameras

still same issue---

get these two errors in log:

This error originated from a custom integration.

Logger: custom_components.tapo_control
Source: custom_components/tapo_control/__init__.py:324
Integration: Tapo: Cameras Control (documentation, issues)
First occurred: 9:27:17 PM (54 occurrences)
Last logged: 9:30:41 PM

Unexpected error fetching Tapo resource status data: <pytapo.Tapo object at
0x7feb6cf11570>
Unexpected error fetching Tapo resource status data: <pytapo.Tapo object at
0x7feb356ec7f0>
Unexpected error fetching Tapo resource status data: <pytapo.Tapo object at
0x7feb72c00af0>
Unexpected error fetching Tapo resource status data: <pytapo.Tapo object at
0x7feb666d08b0>
Unexpected error fetching Tapo resource status data: <pytapo.Tapo object at
0x7feb72127d90>
Traceback (most recent call last):
  File
"/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line
258, in _async_refresh
    self.data = await self._async_update_data()
  File
"/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line
217, in _async_update_data
    return await self.update_method()
  File "/config/custom_components/tapo_control/__init__.py", line 324, in
async_update_data
    entity["camData"] = updateDataForAllControllers[
KeyError: <pytapo.Tapo object at 0x7feb6cf11570>



This error originated from a custom integration.

Logger: homeassistant
Source: custom_components/tapo_control/utils.py:642
Integration: Tapo: Cameras Control (documentation, issues)
First occurred: 9:27:16 PM (5 occurrences)
Last logged: 9:28:17 PM

Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/config/custom_components/tapo_control/utils.py", line 642, in
update_listener
    entity._host = host
AttributeError: 'dict' object has no attribute '_host'

**Comment by JurajNyiri** [comment]
It is a completely different issue now, the logs you posted are different. You need to fix your environment -- delete everything related to tapo from jsons in .storage. Make sure to create backup. 

If you have backup before you updated and all this started it might be easier to restore. Then simply update to the newest version.
