### ISSUE TITLE
{"message":"Invalid handler specified"}

### ISSUE THREAD

**Issue by ThreeSixty123** [JurajNyiri/HomeAssistant-Tapo-Control#339]
### Description

Exception in _async_prefs_updated called from File "/usr/local/lib/python3.10/runpy.py", line 196, in _run_module_as_main return _run_code(code, main_globals, None, File "/usr/local/lib/python3.10/runpy.py", line 86, in _run_code exec(code, run_globals) File "/usr/src/homeassistant/homeassistant/__main__.py", line 226, in <module> sys.exit(main()) File "/usr/src/homeassistant/homeassistant/__main__.py", line 214, in main exit_code = runner.run(runtime_conf) File "/usr/src/homeassistant/homeassistant/runner.py", line 179, in run return loop.run_until_complete(setup_and_run_hass(runtime_config)) File "/usr/local/lib/python3.10/asyncio/base_events.py", line 636, in run_until_complete self.run_forever() File "/usr/local/lib/python3.10/asyncio/base_events.py", line 603, in run_forever self._run_once() File "/usr/local/lib/python3.10/asyncio/base_events.py", line 1909, in _run_once handle._run() File "/usr/local/lib/python3.10/asyncio/events.py", line 80, in _run self._context.run(self._callback, *self._args) File "/usr/src/homeassistant/homeassistant/components/cloud/__init__.py", line 309, in _on_initialized await prefs.async_update(remote_domain=cloud.remote.instance_domain) File "/usr/src/homeassistant/homeassistant/components/cloud/prefs.py", line 132, in async_update await self._save_prefs(prefs) File "/usr/src/homeassistant/homeassistant/components/cloud/prefs.py", line 293, in _save_prefs self._hass.async_create_task(async_create_catching_coro(listener(self))) Traceback (most recent call last): File "/usr/src/homeassistant/homeassistant/components/cloud/alexa_config.py", line 353, in _async_prefs_updated await self.async_disable_proactive_mode() File "/usr/src/homeassistant/homeassistant/components/alexa/config.py", line 83, in async_disable_proactive_mode if unsub_func := await self._unsub_proactive_report: homeassistant.components.alexa.errors.RequireRelink

### Reproduction Steps

During HA Startup 

### Expected behavior

Startup of Tapo Controll

### Device Firmware

1.3.0

### Using stream component

Yes

### Does camera work via official integrations?

Yes

### Camera has all attributes filled out in developer tools

Yes

### HASS Environment

Raspberry Pi

### Search for similar issues

Yes

### Additional information

(=)

**Comment by ThreeSixty123** [comment]
solved be updating Tapo camera control :)
