### ISSUE TITLE
C320WS HW 2.0 FW 1.0.5 Build 230316 Rel.55457n Error on service all

### ISSUE THREAD

**Issue by fuzzybear62** [JurajNyiri/HomeAssistant-Tapo-Control#368]
### Description

I have 4 c320ws hw 1.0 and 1 with hw 2.0, and these functions does'n work con hw 2.0:

Manual Alarm Start, Manual Alarm Stop, Siren as soon as pressed gave back an error invoking the service (connection lost)

Floodlight light switch is not present

Let me known how can I help for debugging

### Reproduction Steps

Camera Resource

### Expected behavior

.

### If applicable, add error logs.

Logger: homeassistant.components.websocket_api.http.connection
Source: custom_components/tapo_control/button.py:120
Integration: Home Assistant WebSocket API (documentation, issues)
First occurred: 15:05:16 (1 occurrences)
Last logged: 15:05:16

[1268491056] Error: Parameter to get/do does not exist, Response: {"error_code": -40106}
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 205, in handle_call_service
    await hass.services.async_call(
  File "/usr/src/homeassistant/homeassistant/core.py", line 1965, in async_call
    response_data = await coro
                    ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2005, in _execute_service
    return await cast(
           ^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 235, in handle_service
    return await service.entity_service_call(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 848, in entity_service_call
    response_data = task.result()  # pop exception if have
                    ^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1192, in async_request_call
    return await coro
           ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 892, in _handle_entity_call
    result = await task
             ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/button/__init__.py", line 124, in _async_press_action
    await self.async_press()
  File "/config/custom_components/tapo_control/button.py", line 120, in async_press
    await self._hass.async_add_executor_job(self._controller.startManualAlarm)
  File "/usr/local/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/pytapo/__init__.py", line 964, in startManualAlarm
    return self.performRequest(
           ^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/pytapo/__init__.py", line 184, in performRequest
    raise Exception(
Exception: Error: Parameter to get/do does not exist, Response: {"error_code": -40106}

### Device Firmware

1.0.5 Build 230316 Rel.55457n

### Using stream component

Yes

### Does camera work via official integrations?

Yes

### Camera has all attributes filled out in developer tools

Yes

### HASS Environment

 Home Assistant 2023.7.2 Supervisor 2023.07.1 Operating System 10.3 Frontend 20230705.1 - latest (RPI)

### Search for similar issues

Yes

**Comment by JurajNyiri** [comment]
Please fill out the template properly and update title to something meaningful then I can look at it and reopen.
