### ISSUE TITLE
Tapo integration is flooding the system logs when the camera is offline

### ISSUE THREAD

**Issue by denischupau** [JurajNyiri/HomeAssistant-Tapo-Control#382]
### Description

Hi,

I have a Tapo IP Wifi camera that is ON only when I'm not at home: a relay is physically switching it OFF when I'm home (Alarm Away OFF).

So, when the camera is physically switched OFF (unplugged), the integration is trying to connect to the camera several times a minute, and several attempts each time.

Each attempt to connect generates about a 100 lines or more of python error logs.
This is generating MB and MB of system logs, filling up the server's disk space, leading to more important problems.

### Reproduction Steps

- install and activate the Tapo control integration from HACS
- switch the Tapo IP camera (such as C200) ON
- configure a Tapo IP camera, such as C200 in the Tapo integration,
- check that everything is working (video feed, movements, etc.),
- unplug the camera (physically switch OFF)
- observe the system logs filling up with 100s of lines of python errors several times every minute.

### Expected behavior

When the Tapo Integration detects a failed connection to the camera, log 1 line or so.

Maybe increase the time between connection retries after the connexion failed N times in a row? like once every minute after five failed connection attempts in a row.

Maybe add an option to disable the camera device if it is impossible to connect to it for a few minutes (or user-defined amount of time), as is the case for cameras that are not ON 24/7?
And send a message via the App when it is disabled, so the admin knows (doable by the admin in an automation).

### If applicable, add error logs.

ago 14 20:41:18 serv.local hass[13333]: 2023-08-14 20:41:18.166 ERROR (MainThread) [custom_components.tapo_control] Unexpected error fetching Tapo resource status data: All connection attempts failed
ago 14 20:41:18 serv.local hass[13333]: Traceback (most recent call last):
ago 14 20:41:18 serv.local hass[13333]:   File "/srv/homeassistant/lib/python3.11/site-packages/anyio/_core/_sockets.py", line 167, in try_connect
ago 14 20:41:18 serv.local hass[13333]:     stream = await asynclib.connect_tcp(remote_host, remote_port, local_address)
ago 14 20:41:18 serv.local hass[13333]:              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ago 14 20:41:18 serv.local hass[13333]:   File "/srv/homeassistant/lib/python3.11/site-packages/anyio/_backends/_asyncio.py", line 1627, in connect_tcp
ago 14 20:41:18 serv.local hass[13333]:     await get_running_loop().create_connection(
ago 14 20:41:18 serv.local hass[13333]:   File "/usr/lib/python3.11/asyncio/base_events.py", line 1085, in create_connection
ago 14 20:41:18 serv.local hass[13333]:     raise exceptions[0]
ago 14 20:41:18 serv.local hass[13333]:   File "/usr/lib/python3.11/asyncio/base_events.py", line 1069, in create_connection
ago 14 20:41:18 serv.local hass[13333]:     sock = await self._connect_sock(
ago 14 20:41:18 serv.local hass[13333]:            ^^^^^^^^^^^^^^^^^^^^^^^^^
ago 14 20:41:18 serv.local hass[13333]:   File "/usr/lib/python3.11/asyncio/base_events.py", line 973, in _connect_sock
ago 14 20:41:18 serv.local hass[13333]:     await self.sock_connect(sock, address)
ago 14 20:41:18 serv.local hass[13333]:   File "/usr/lib/python3.11/asyncio/selector_events.py", line 634, in sock_connect
ago 14 20:41:18 serv.local hass[13333]:     return await fut
ago 14 20:41:18 serv.local hass[13333]:            ^^^^^^^^^
ago 14 20:41:18 serv.local hass[13333]:   File "/usr/lib/python3.11/asyncio/selector_events.py", line 674, in _sock_connect_cb
ago 14 20:41:18 serv.local hass[13333]:     raise OSError(err, f'Connect call failed {address}')
ago 14 20:41:18 serv.local hass[13333]: OSError: [Errno 113] Connect call failed ('192.168.xxx.xxx', 2020)
ago 14 20:41:18 serv.local hass[13333]: The above exception was the direct cause of the following exception:
ago 14 20:41:18 serv.local hass[13333]: Traceback (most recent call last):
ago 14 20:41:18 serv.local hass[13333]:   File "/srv/homeassistant/lib/python3.11/site-packages/httpcore/_exceptions.py", line 10, in map_exceptions
ago 14 20:41:18 serv.local hass[13333]:     yield
ago 14 20:41:18 serv.local hass[13333]:   File "/srv/homeassistant/lib/python3.11/site-packages/httpcore/_backends/anyio.py", line 114, in connect_tcp
ago 14 20:41:18 serv.local hass[13333]:   File "/srv/homeassistant/lib/python3.11/site-packages/anyio/_core/_sockets.py", line 225, in connect_tcp
ago 14 20:41:18 serv.local hass[13333]:     raise OSError("All connection attempts failed") from cause
ago 14 20:41:18 serv.local hass[13333]: OSError: All connection attempts failed
ago 14 20:41:18 serv.local hass[13333]: The above exception was the direct cause of the following exception:
ago 14 20:41:18 serv.local hass[13333]: Traceback (most recent call last):
ago 14 20:41:18 serv.local hass[13333]:   File "/srv/homeassistant/lib/python3.11/site-packages/httpx/_transports/default.py", line 60, in map_httpcore_exceptions
ago 14 20:41:18 serv.local hass[13333]:     yield
ago 14 20:41:18 serv.local hass[13333]:   File "/srv/homeassistant/lib/python3.11/site-packages/httpx/_transports/default.py", line 353, in handle_async_request
ago 14 20:41:18 serv.local hass[13333]:     resp = await self._pool.handle_async_request(req)
ago 14 20:41:18 serv.local hass[13333]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ago 14 20:41:18 serv.local hass[13333]:   File "/srv/homeassistant/lib/python3.11/site-packages/httpcore/_async/connection_pool.py", line 262, in handle_async_request
ago 14 20:41:18 serv.local hass[13333]:     else:
ago 14 20:41:18 serv.local hass[13333]:         ^^
ago 14 20:41:18 serv.local hass[13333]:   File "/srv/homeassistant/lib/python3.11/site-packages/httpcore/_async/connection_pool.py", line 245, in handle_async_request
ago 14 20:41:18 serv.local hass[13333]:     response = await connection.handle_async_request(request)
ago 14 20:41:18 serv.local hass[13333]:                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ago 14 20:41:18 serv.local hass[13333]:   File "/srv/homeassistant/lib/python3.11/site-packages/httpcore/_async/connection.py", line 92, in handle_async_request
ago 14 20:41:18 serv.local hass[13333]:     raise exc
ago 14 20:41:18 serv.local hass[13333]:   File "/srv/homeassistant/lib/python3.11/site-packages/httpcore/_async/connection.py", line 69, in handle_async_request
ago 14 20:41:18 serv.local hass[13333]:     stream = await self._connect(request)
ago 14 20:41:18 serv.local hass[13333]:              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ago 14 20:41:18 serv.local hass[13333]:   File "/srv/homeassistant/lib/python3.11/site-packages/httpcore/_async/connection.py", line 117, in _connect
ago 14 20:41:18 serv.local hass[13333]:     stream = await self._network_backend.connect_tcp(**kwargs)
ago 14 20:41:18 serv.local hass[13333]:              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ago 14 20:41:18 serv.local hass[13333]:   File "/srv/homeassistant/lib/python3.11/site-packages/httpcore/_backends/auto.py", line 31, in connect_tcp
ago 14 20:41:18 serv.local hass[13333]:   File "/srv/homeassistant/lib/python3.11/site-packages/httpcore/_backends/anyio.py", line 112, in connect_tcp
ago 14 20:41:18 serv.local hass[13333]:   File "/usr/lib/python3.11/contextlib.py", line 155, in __exit__
ago 14 20:41:18 serv.local hass[13333]:     self.gen.throw(typ, value, traceback)
ago 14 20:41:18 serv.local hass[13333]:   File "/srv/homeassistant/lib/python3.11/site-packages/httpcore/_exceptions.py", line 14, in map_exceptions
ago 14 20:41:18 serv.local hass[13333]:     raise to_exc(exc) from exc
ago 14 20:41:18 serv.local hass[13333]: httpcore.ConnectError: All connection attempts failed
ago 14 20:41:18 serv.local hass[13333]: The above exception was the direct cause of the following exception:
ago 14 20:41:18 serv.local hass[13333]: Traceback (most recent call last):
ago 14 20:41:18 serv.local hass[13333]:   File "/srv/homeassistant/lib/python3.11/site-packages/homeassistant/helpers/update_coordinator.py", line 283, in _async_refresh
ago 14 20:41:18 serv.local hass[13333]:     self.data = await self._async_update_data()
ago 14 20:41:18 serv.local hass[13333]:                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ago 14 20:41:18 serv.local hass[13333]:   File "/srv/homeassistant/lib/python3.11/site-packages/homeassistant/helpers/update_coordinator.py", line 242, in _async_update_data
ago 14 20:41:18 serv.local hass[13333]:     return await self.update_method()
ago 14 20:41:18 serv.local hass[13333]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^
ago 14 20:41:18 serv.local hass[13333]:   File "/home/homeassistant/.homeassistant/custom_components/tapo_control/__init__.py", line 277, in async_update_data
ago 14 20:41:18 serv.local hass[13333]:     await syncTime(hass, entry.entry_id)
ago 14 20:41:18 serv.local hass[13333]:   File "/home/homeassistant/.homeassistant/custom_components/tapo_control/utils.py", line 712, in syncTime
ago 14 20:41:18 serv.local hass[13333]:     await device_mgmt.SetSystemDateAndTime(time_params)
ago 14 20:41:18 serv.local hass[13333]:   File "/srv/homeassistant/lib/python3.11/site-packages/zeep/proxy.py", line 64, in __call__
ago 14 20:41:18 serv.local hass[13333]:     return await self._proxy._binding.send_async(
ago 14 20:41:18 serv.local hass[13333]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ago 14 20:41:18 serv.local hass[13333]:   File "/srv/homeassistant/lib/python3.11/site-packages/zeep/wsdl/bindings/soap.py", line 156, in send_async
ago 14 20:41:18 serv.local hass[13333]:     response = await client.transport.post_xml(
ago 14 20:41:18 serv.local hass[13333]:                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ago 14 20:41:18 serv.local hass[13333]:   File "/srv/homeassistant/lib/python3.11/site-packages/zeep/transports.py", line 235, in post_xml
ago 14 20:41:18 serv.local hass[13333]:     response = await self.post(address, message, headers)
ago 14 20:41:18 serv.local hass[13333]:                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ago 14 20:41:18 serv.local hass[13333]:   File "/srv/homeassistant/lib/python3.11/site-packages/zeep/transports.py", line 220, in post
ago 14 20:41:18 serv.local hass[13333]:     response = await self.client.post(
ago 14 20:41:18 serv.local hass[13333]:                ^^^^^^^^^^^^^^^^^^^^^^^
ago 14 20:41:18 serv.local hass[13333]:   File "/srv/homeassistant/lib/python3.11/site-packages/httpx/_client.py", line 1848, in post
ago 14 20:41:18 serv.local hass[13333]:     return await self.request(
ago 14 20:41:18 serv.local hass[13333]:            ^^^^^^^^^^^^^^^^^^^
ago 14 20:41:18 serv.local hass[13333]:   File "/srv/homeassistant/lib/python3.11/site-packages/httpx/_client.py", line 1530, in request
ago 14 20:41:18 serv.local hass[13333]:     return await self.send(request, auth=auth, follow_redirects=follow_redirects)
ago 14 20:41:18 serv.local hass[13333]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ago 14 20:41:18 serv.local hass[13333]:   File "/srv/homeassistant/lib/python3.11/site-packages/httpx/_client.py", line 1617, in send
ago 14 20:41:18 serv.local hass[13333]:     response = await self._send_handling_auth(
ago 14 20:41:18 serv.local hass[13333]:                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ago 14 20:41:18 serv.local hass[13333]:   File "/srv/homeassistant/lib/python3.11/site-packages/httpx/_client.py", line 1645, in _send_handling_auth
ago 14 20:41:18 serv.local hass[13333]:     response = await self._send_handling_redirects(
ago 14 20:41:18 serv.local hass[13333]:                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ago 14 20:41:18 serv.local hass[13333]:   File "/srv/homeassistant/lib/python3.11/site-packages/httpx/_client.py", line 1682, in _send_handling_redirects
ago 14 20:41:18 serv.local hass[13333]:     response = await self._send_single_request(request)
ago 14 20:41:18 serv.local hass[13333]:                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ago 14 20:41:18 serv.local hass[13333]:   File "/srv/homeassistant/lib/python3.11/site-packages/httpx/_client.py", line 1719, in _send_single_request
ago 14 20:41:18 serv.local hass[13333]:     response = await transport.handle_async_request(request)
ago 14 20:41:18 serv.local hass[13333]:                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ago 14 20:41:18 serv.local hass[13333]:   File "/srv/homeassistant/lib/python3.11/site-packages/httpx/_transports/default.py", line 352, in handle_async_request
ago 14 20:41:18 serv.local hass[13333]:     with map_httpcore_exceptions():
ago 14 20:41:18 serv.local hass[13333]:   File "/usr/lib/python3.11/contextlib.py", line 155, in __exit__
ago 14 20:41:18 serv.local hass[13333]:     self.gen.throw(typ, value, traceback)
ago 14 20:41:18 serv.local hass[13333]:   File "/srv/homeassistant/lib/python3.11/site-packages/httpx/_transports/default.py", line 77, in map_httpcore_exceptions
ago 14 20:41:18 serv.local hass[13333]:     raise mapped_exc(message) from exc
ago 14 20:41:18 serv.local hass[13333]: httpx.ConnectError: All connection attempts failed

### Device Firmware

Latest

### Using stream component

Yes

### Does camera work via official integrations?

Yes

### Camera has all attributes filled out in developer tools

Yes

### HASS Environment

HASS on Debian 12

### Search for similar issues

Yes

**Comment by JurajNyiri** [comment]
This is expected and wanted. If you do not wish to receive logs, you can disable them via configuration and logger integration.

**Comment by denischupau** [comment]
> This is expected and wanted. If you do not wish to receive logs, you can disable them via configuration and logger integration.

Hi, I did try this:
```
logger:
  default: warning
  logs:
    custom_components.tapo_control: critical
```

It seems the "critical" log level is the maximum, to my knowledge, it can not be completely disabled.

Now, I nearly don't have any log entries anymore, but some messages when a camera is connecting or disconnecting.

BUT, after watching the stream of a camera, if this camera gets disconnected (even when not watching the stream), the flood still happens every 1 or 2 minutes, until the camera reconnects, or the Tapo integration is disabled, then re-enabled.

Here is the log entries that appear every 1 or 2 minutes (100+ lines each time):
```
aug 23 17:55:25 serv.local hass[11111]: 2023-08-23 17:55:25.226 ERROR (SyncWorker_0) [homeassistant] Error doing job: Task exception was never retrieved
aug 23 17:55:25 serv.local hass[11111]: Traceback (most recent call last):
aug 23 17:55:25 serv.local hass[11111]:   File "/srv/homeassistant/lib/python3.11/site-packages/anyio/_core/_sockets.py", line 167, in try_connect
aug 23 17:55:25 serv.local hass[11111]:     stream = await asynclib.connect_tcp(remote_host, remote_port, local_address)
aug 23 17:55:25 serv.local hass[11111]:              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
aug 23 17:55:25 serv.local hass[11111]:   File "/srv/homeassistant/lib/python3.11/site-packages/anyio/_backends/_asyncio.py", line 1627, in connect_tcp
aug 23 17:55:25 serv.local hass[11111]:     await get_running_loop().create_connection(
aug 23 17:55:25 serv.local hass[11111]:   File "/usr/lib/python3.11/asyncio/base_events.py", line 1085, in create_connection
aug 23 17:55:25 serv.local hass[11111]:     raise exceptions[0]
aug 23 17:55:25 serv.local hass[11111]:   File "/usr/lib/python3.11/asyncio/base_events.py", line 1069, in create_connection
aug 23 17:55:25 serv.local hass[11111]:     sock = await self._connect_sock(
aug 23 17:55:25 serv.local hass[11111]:            ^^^^^^^^^^^^^^^^^^^^^^^^^
aug 23 17:55:25 serv.local hass[11111]:   File "/usr/lib/python3.11/asyncio/base_events.py", line 973, in _connect_sock
aug 23 17:55:25 serv.local hass[11111]:     await self.sock_connect(sock, address)
aug 23 17:55:25 serv.local hass[11111]:   File "/usr/lib/python3.11/asyncio/selector_events.py", line 634, in sock_connect
aug 23 17:55:25 serv.local hass[11111]:     return await fut
aug 23 17:55:25 serv.local hass[11111]:            ^^^^^^^^^
aug 23 17:55:25 serv.local hass[11111]:   File "/usr/lib/python3.11/asyncio/selector_events.py", line 674, in _sock_connect_cb
aug 23 17:55:25 serv.local hass[11111]:     raise OSError(err, f'Connect call failed {address}')
aug 23 17:55:25 serv.local hass[11111]: OSError: [Errno 113] Connect call failed ('192.168.xxx.xxx', 2020)
aug 23 17:55:25 serv.local hass[11111]: The above exception was the direct cause of the following exception:
aug 23 17:55:25 serv.local hass[11111]: Traceback (most recent call last):
aug 23 17:55:25 serv.local hass[11111]:   File "/srv/homeassistant/lib/python3.11/site-packages/httpcore/_exceptions.py", line 10, in map_exceptions
aug 23 17:55:25 serv.local hass[11111]:     yield
aug 23 17:55:25 serv.local hass[11111]:   File "/srv/homeassistant/lib/python3.11/site-packages/httpcore/_backends/anyio.py", line 114, in connect_tcp
aug 23 17:55:25 serv.local hass[11111]:     stream: anyio.abc.ByteStream = await anyio.connect_tcp(
aug 23 17:55:25 serv.local hass[11111]:                                    ^^^^^^^^^^^^^^^^^^^^^^^^
aug 23 17:55:25 serv.local hass[11111]:   File "/srv/homeassistant/lib/python3.11/site-packages/anyio/_core/_sockets.py", line 225, in connect_tcp
aug 23 17:55:25 serv.local hass[11111]:     raise OSError("All connection attempts failed") from cause
aug 23 17:55:25 serv.local hass[11111]: OSError: All connection attempts failed
aug 23 17:55:25 serv.local hass[11111]: The above exception was the direct cause of the following exception:
aug 23 17:55:25 serv.local hass[11111]: Traceback (most recent call last):
aug 23 17:55:25 serv.local hass[11111]:   File "/srv/homeassistant/lib/python3.11/site-packages/httpx/_transports/default.py", line 60, in map_httpcore_exceptions
aug 23 17:55:25 serv.local hass[11111]:     yield
aug 23 17:55:25 serv.local hass[11111]:   File "/srv/homeassistant/lib/python3.11/site-packages/httpx/_transports/default.py", line 353, in handle_async_request
aug 23 17:55:25 serv.local hass[11111]:     resp = await self._pool.handle_async_request(req)
aug 23 17:55:25 serv.local hass[11111]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
aug 23 17:55:25 serv.local hass[11111]:   File "/srv/homeassistant/lib/python3.11/site-packages/httpcore/_async/connection_pool.py", line 262, in handle_async_request
aug 23 17:55:25 serv.local hass[11111]:     raise exc
aug 23 17:55:25 serv.local hass[11111]:   File "/srv/homeassistant/lib/python3.11/site-packages/httpcore/_async/connection_pool.py", line 245, in handle_async_request
aug 23 17:55:25 serv.local hass[11111]:     response = await connection.handle_async_request(request)
aug 23 17:55:25 serv.local hass[11111]:                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
aug 23 17:55:25 serv.local hass[11111]:   File "/srv/homeassistant/lib/python3.11/site-packages/httpcore/_async/connection.py", line 92, in handle_async_request
aug 23 17:55:25 serv.local hass[11111]:     raise exc
aug 23 17:55:25 serv.local hass[11111]:   File "/srv/homeassistant/lib/python3.11/site-packages/httpcore/_async/connection.py", line 69, in handle_async_request
aug 23 17:55:25 serv.local hass[11111]:     stream = await self._connect(request)
aug 23 17:55:25 serv.local hass[11111]:              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
aug 23 17:55:25 serv.local hass[11111]:   File "/srv/homeassistant/lib/python3.11/site-packages/httpcore/_async/connection.py", line 117, in _connect
aug 23 17:55:25 serv.local hass[11111]:     stream = await self._network_backend.connect_tcp(**kwargs)
aug 23 17:55:25 serv.local hass[11111]:              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
aug 23 17:55:25 serv.local hass[11111]:   File "/srv/homeassistant/lib/python3.11/site-packages/httpcore/_backends/auto.py", line 31, in connect_tcp
aug 23 17:55:25 serv.local hass[11111]:     return await self._backend.connect_tcp(
aug 23 17:55:25 serv.local hass[11111]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
aug 23 17:55:25 serv.local hass[11111]:   File "/srv/homeassistant/lib/python3.11/site-packages/httpcore/_backends/anyio.py", line 112, in connect_tcp
aug 23 17:55:25 serv.local hass[11111]:     with map_exceptions(exc_map):
aug 23 17:55:25 serv.local hass[11111]:   File "/usr/lib/python3.11/contextlib.py", line 155, in __exit__
aug 23 17:55:25 serv.local hass[11111]:     self.gen.throw(typ, value, traceback)
aug 23 17:55:25 serv.local hass[11111]:   File "/srv/homeassistant/lib/python3.11/site-packages/httpcore/_exceptions.py", line 14, in map_exceptions
aug 23 17:55:25 serv.local hass[11111]:     raise to_exc(exc) from exc
aug 23 17:55:25 serv.local hass[11111]: httpcore.ConnectError: All connection attempts failed
aug 23 17:55:25 serv.local hass[11111]: The above exception was the direct cause of the following exception:
aug 23 17:55:25 serv.local hass[11111]: Traceback (most recent call last):
aug 23 17:55:25 serv.local hass[11111]:   File "/srv/homeassistant/lib/python3.11/site-packages/onvif/managers.py", line 189, in _renew_or_restart_subscription
aug 23 17:55:25 serv.local hass[11111]:     await self._renew_subscription() or await self._restart_subscription()
aug 23 17:55:25 serv.local hass[11111]:                                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
aug 23 17:55:25 serv.local hass[11111]:   File "/srv/homeassistant/lib/python3.11/site-packages/onvif/managers.py", line 154, in _restart_subscription
aug 23 17:55:25 serv.local hass[11111]:     return await self._start()
aug 23 17:55:25 serv.local hass[11111]:            ^^^^^^^^^^^^^^^^^^^
aug 23 17:55:25 serv.local hass[11111]:   File "/srv/homeassistant/lib/python3.11/site-packages/onvif/managers.py", line 298, in _start
aug 23 17:55:25 serv.local hass[11111]:     result = await events_service.CreatePullPointSubscription(
aug 23 17:55:25 serv.local hass[11111]:              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
aug 23 17:55:25 serv.local hass[11111]:   File "/srv/homeassistant/lib/python3.11/site-packages/zeep/proxy.py", line 64, in __call__
aug 23 17:55:25 serv.local hass[11111]:     return await self._proxy._binding.send_async(
aug 23 17:55:25 serv.local hass[11111]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
aug 23 17:55:25 serv.local hass[11111]:   File "/srv/homeassistant/lib/python3.11/site-packages/zeep/wsdl/bindings/soap.py", line 156, in send_async
aug 23 17:55:25 serv.local hass[11111]:     response = await client.transport.post_xml(
aug 23 17:55:25 serv.local hass[11111]:                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
aug 23 17:55:25 serv.local hass[11111]:   File "/srv/homeassistant/lib/python3.11/site-packages/zeep/transports.py", line 235, in post_xml
aug 23 17:55:25 serv.local hass[11111]:     response = await self.post(address, message, headers)
aug 23 17:55:25 serv.local hass[11111]:                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
aug 23 17:55:25 serv.local hass[11111]:   File "/srv/homeassistant/lib/python3.11/site-packages/zeep/transports.py", line 220, in post
aug 23 17:55:25 serv.local hass[11111]:     response = await self.client.post(
aug 23 17:55:25 serv.local hass[11111]:                ^^^^^^^^^^^^^^^^^^^^^^^
aug 23 17:55:25 serv.local hass[11111]:   File "/srv/homeassistant/lib/python3.11/site-packages/httpx/_client.py", line 1848, in post
aug 23 17:55:25 serv.local hass[11111]:     return await self.request(
aug 23 17:55:25 serv.local hass[11111]:            ^^^^^^^^^^^^^^^^^^^
aug 23 17:55:25 serv.local hass[11111]:   File "/srv/homeassistant/lib/python3.11/site-packages/httpx/_client.py", line 1530, in request
aug 23 17:55:25 serv.local hass[11111]:     return await self.send(request, auth=auth, follow_redirects=follow_redirects)
aug 23 17:55:25 serv.local hass[11111]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
aug 23 17:55:25 serv.local hass[11111]:   File "/srv/homeassistant/lib/python3.11/site-packages/httpx/_client.py", line 1617, in send
aug 23 17:55:25 serv.local hass[11111]:     response = await self._send_handling_auth(
aug 23 17:55:25 serv.local hass[11111]:                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
aug 23 17:55:25 serv.local hass[11111]:   File "/srv/homeassistant/lib/python3.11/site-packages/httpx/_client.py", line 1645, in _send_handling_auth
aug 23 17:55:25 serv.local hass[11111]:     response = await self._send_handling_redirects(
aug 23 17:55:25 serv.local hass[11111]:                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
aug 23 17:55:25 serv.local hass[11111]:   File "/srv/homeassistant/lib/python3.11/site-packages/httpx/_client.py", line 1682, in _send_handling_redirects
aug 23 17:55:25 serv.local hass[11111]:     response = await self._send_single_request(request)
aug 23 17:55:25 serv.local hass[11111]:                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
aug 23 17:55:25 serv.local hass[11111]:   File "/srv/homeassistant/lib/python3.11/site-packages/httpx/_client.py", line 1719, in _send_single_request
aug 23 17:55:25 serv.local hass[11111]:     response = await transport.handle_async_request(request)
aug 23 17:55:25 serv.local hass[11111]:                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
aug 23 17:55:25 serv.local hass[11111]:   File "/srv/homeassistant/lib/python3.11/site-packages/httpx/_transports/default.py", line 352, in handle_async_request
aug 23 17:55:25 serv.local hass[11111]:     with map_httpcore_exceptions():
aug 23 17:55:25 serv.local hass[11111]:   File "/usr/lib/python3.11/contextlib.py", line 155, in __exit__
aug 23 17:55:25 serv.local hass[11111]:     self.gen.throw(typ, value, traceback)
aug 23 17:55:25 serv.local hass[11111]:   File "/srv/homeassistant/lib/python3.11/site-packages/httpx/_transports/default.py", line 77, in map_httpcore_exceptions
aug 23 17:55:25 serv.local hass[11111]:     raise mapped_exc(message) from exc
aug 23 17:55:25 serv.local hass[11111]: httpx.ConnectError: All connection attempts failed
```

I hope it can be usefull.
Denis

**Comment by JurajNyiri** [comment]
Hi, that error message is not coming out of this integration but Home Assistant itself. Try disabling also for https://www.home-assistant.io/integrations/onvif/
