### ISSUE TITLE
Invalid Config ( C100 )

### ISSUE THREAD

**Issue by msaphoto** [JurajNyiri/HomeAssistant-Tapo-Control#4]
Hello

I have a Inval Config when add my 2nd cam. (C100)

tapo_control:
  - host: 192.168.0.102    ( C200 )
    username: ms....
    password: Ki....
  - host: 192.168.0.101     ( C100 )
    username: ms.....
    password: Ki....

Name of cam is Salon

Logger: homeassistant.setup
Source: custom_components/tapo_control/__init__.py:335
First occurred: 16:44:07 (1 occurrences)
Last logged: 16:44:07

Error during setup of component tapo_control
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 213, in _async_setup_component
    result = await task
  File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/tapo_control/__init__.py", line 335, in setup
    tapoConnector = Tapo(host, username, password)
  File "/usr/local/lib/python3.8/site-packages/pytapo/__init__.py", line 28, in __init__
    self.presets = self.getPresets()
  File "/usr/local/lib/python3.8/site-packages/pytapo/__init__.py", line 384, in getPresets
    return self.getPresets()
  File "/usr/local/lib/python3.8/site-packages/pytapo/__init__.py", line 384, in getPresets
    return self.getPresets()
  File "/usr/local/lib/python3.8/site-packages/pytapo/__init__.py", line 384, in getPresets
    return self.getPresets()
  [Previous line repeated 965 more times]
  File "/usr/local/lib/python3.8/site-packages/pytapo/__init__.py", line 383, in getPresets
    self.refreshStok()
  File "/usr/local/lib/python3.8/site-packages/pytapo/__init__.py", line 48, in refreshStok
    res = requests.post(url, data = json.dumps(data), headers=self.headers, verify=False)
  File "/usr/local/lib/python3.8/site-packages/requests/api.py", line 119, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/requests/sessions.py", line 530, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.8/site-packages/requests/sessions.py", line 643, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/usr/local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 670, in urlopen
    httplib_response = self._make_request(
  File "/usr/local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 426, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/usr/local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 421, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/local/lib/python3.8/http/client.py", line 1347, in getresponse
    response.begin()
  File "/usr/local/lib/python3.8/http/client.py", line 331, in begin
    self.headers = self.msg = parse_headers(self.fp)
  File "/usr/local/lib/python3.8/http/client.py", line 225, in parse_headers
    return email.parser.Parser(_class=_class).parsestr(hstring)
  File "/usr/local/lib/python3.8/email/parser.py", line 67, in parsestr
    return self.parse(StringIO(text), headersonly=headersonly)
  File "/usr/local/lib/python3.8/email/parser.py", line 56, in parse
    feedparser.feed(data)
  File "/usr/local/lib/python3.8/email/feedparser.py", line 176, in feed
    self._call_parse()
  File "/usr/local/lib/python3.8/email/feedparser.py", line 180, in _call_parse
    self._parse()
  File "/usr/local/lib/python3.8/email/feedparser.py", line 295, in _parsegen
    if self._cur.get_content_maintype() == 'message':
  File "/usr/local/lib/python3.8/email/message.py", line 594, in get_content_maintype
    ctype = self.get_content_type()
  File "/usr/local/lib/python3.8/email/message.py", line 578, in get_content_type
    value = self.get('content-type', missing)
  File "/usr/local/lib/python3.8/email/message.py", line 471, in get
    return self.policy.header_fetch_parse(k, v)
  File "/usr/local/lib/python3.8/email/_policybase.py", line 316, in header_fetch_parse
    return self._sanitize_header(name, value)
  File "/usr/local/lib/python3.8/email/_policybase.py", line 287, in _sanitize_header
    if _has_surrogates(value):
  File "/usr/local/lib/python3.8/email/utils.py", line 57, in _has_surrogates
    s.encode()
RecursionError: maximum recursion depth exceeded while calling a Python object

**Comment by JurajNyiri** [comment]
I will need to implement better error handling to debug this one via logs only.

Until then, if you would like to help speed up the resolution of this issue, please:
1.) install python3, pip3
2.) Install pytapo and requests through pip3
3.) Run python3 script below and post results:

```
from pytapo import Tapo
import requests
import json

user = "" # user you set in Advanced Settings -> Camera Account
password = "" # password you set in Advanced Settings -> Camera Account
host = "" # ip of the camera, example: 192.168.1.52

tapo = Tapo(host, user, password)

stok = tapo.refreshStok()

print(stok)

data = {
    "method": "get",
    "preset": {
        "name": ["preset"]
    }
}
res = requests.post(tapo.getHostURL(), data = json.dumps(data), headers=tapo.headers, verify=False)
data = json.loads(res.text)
print(res)
print(data)
```

**Comment by JurajNyiri** [comment]
Do you have any presets set for that camera? I didn't test a camera without any presets set, that might be the issue.

**Comment by msaphoto** [comment]
no preset. the C100 is a fixed camera

**Comment by JurajNyiri** [comment]
Working on a better error handling that will get us closer to a solution.

I do not have the C100 so I cannot test it at all. 

Update should be available in a while.

**Comment by msaphoto** [comment]
Ok thanks

**Comment by JurajNyiri** [comment]
@msaphoto Please update to 1.2 and paste new error from the log here.

**Comment by msaphoto** [comment]
Logger: homeassistant.setup
Source: custom_components/tapo_control/__init__.py:341
First occurred: 18:08:58 (1 occurrences)
Last logged: 18:08:58

Error during setup of component tapo_control
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 213, in _async_setup_component
    result = await task
  File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/tapo_control/__init__.py", line 341, in setup
    tapoConnector = Tapo(host, username, password)
  File "/usr/local/lib/python3.8/site-packages/pytapo/__init__.py", line 29, in __init__
    self.presets = self.getPresets()
  File "/usr/local/lib/python3.8/site-packages/pytapo/__init__.py", line 430, in getPresets
    return self.getPresets(True)
  File "/usr/local/lib/python3.8/site-packages/pytapo/__init__.py", line 427, in getPresets
    raise Exception("Error: "+self.getErrorMessage(data['error_code'])+" Response:" + json.dumps(data))
Exception: Error: -40106 Response:{"preset": {}, "error_code": -40106}

**Comment by JurajNyiri** [comment]
Your first camera was C200, so this only happens on C100? 
I could disable presets for C100, maybe thats what that error message is for.

**Comment by msaphoto** [comment]
Yes, my first cam is C200 with preset.

**Comment by JurajNyiri** [comment]
Hey, try with 1.3... includes fix for C100. 

Please let me know how it goes.

**Comment by msaphoto** [comment]
Logger: homeassistant.setup
Source: custom_components/tapo_control/__init__.py:345
First occurred: 19:24:15 (1 occurrences)
Last logged: 19:24:15

Error during setup of component tapo_control
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 213, in _async_setup_component
    result = await task
  File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/tapo_control/__init__.py", line 345, in setup
    tapoConnector = Tapo(host, username, password)
  File "/usr/local/lib/python3.8/site-packages/pytapo/__init__.py", line 29, in __init__
    self.presets = self.getPresets()
  File "/usr/local/lib/python3.8/site-packages/pytapo/__init__.py", line 397, in getPresets
    return self.getPresets(True)
  File "/usr/local/lib/python3.8/site-packages/pytapo/__init__.py", line 394, in getPresets
    raise Exception("Error: "+self.getErrorMessage(data['error_code'])+" Response:" + json.dumps(data))
Exception: Error: Parameter to get/do does not exist Response:{"preset": {}, "error_code": -40106}

**Comment by JurajNyiri** [comment]
Hey,

please try with 1.3.1, should work now.

**Comment by msaphoto** [comment]
Yes

C100 it's Ok

**Comment by JurajNyiri** [comment]
Glad to hear that! Thank you for the assistance 👍
