### ISSUE TITLE
Error communicating with Tapo Camera. Status code: 500 (C210)

### ISSUE THREAD

**Issue by rark-ha** [JurajNyiri/HomeAssistant-Tapo-Control#442]
### Description

Restarting Home Assistant I suddenly had two cameras not working in the integration. I am getting a Migration Error in the integrations GUI, with the log showing the error;

`Error communicating with Tapo Camera. Status code: 500`

Trying to set up one of these cameras on my test system I can get the IP and Camera Account done, but the Cloud account step fails (even though the password is the same as the Camera Account, and works for the other 6 cameras still).

The two devices are C210, but I have another couple of these models that are working as expected.

### Reproduction Steps

1. Restart Home Assistant
2. Two camera's not loading from the integration (6 other camera's loading as expected)
3. Error Migrating Entry for _IP-Address_ for Tapo Control show in log (full log from main HA system below)

### Expected behavior

Device expected to setup as normal.

### If applicable, add error logs.

Traceback (most recent call last):
  File "/config/custom_components/tapo_control/__init__.py", line 196, in async_migrate_entry
    tapoController = await hass.async_add_executor_job(
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/tapo_control/utils.py", line 81, in registerController
    return Tapo(host, username, password, password_cloud, super_secret_key, device_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/pytapo/__init__.py", line 66, in __init__
    self.basicInfo = self.getBasicInfo()
                     ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/pytapo/__init__.py", line 743, in getBasicInfo
    return self.executeFunction(
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/pytapo/__init__.py", line 296, in executeFunction
    data = self.performRequest(
           ^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/pytapo/__init__.py", line 335, in performRequest
    self.ensureAuthenticated()
  File "/usr/local/lib/python3.11/site-packages/pytapo/__init__.py", line 86, in ensureAuthenticated
    return self.refreshStok()
           ^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/pytapo/__init__.py", line 265, in refreshStok
    raise Exception("Invalid authentication data")
Exception: Invalid authentication data

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 633, in async_migrate
    result = await component.async_migrate_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/tapo_control/__init__.py", line 225, in async_migrate_entry
    raise ConfigEntryNotReady
homeassistant.exceptions.ConfigEntryNotReady: None

### Device Firmware

1.3.9 Build 231019 Rel.31045n(4555)

### Using stream component

Yes

### Does camera work via official integrations?

Yes

### Camera has all attributes filled out in developer tools

No

### HASS Environment

Docker on Synology NAS

### Search for similar issues

Yes

**Comment by kobrata0912** [comment]
@rark-ha Try using "admin" as a user, regardless of your actual username setup in your camera settings.

**Comment by rark-ha** [comment]
> @rark-ha Try using "admin" as a user, regardless of your actual username setup in your camera settings.

No. That gives me an error when trying to update the config on the main HA instance, and fails with a similar username error when trying to setup the device on my test HA.

**Comment by JurajNyiri** [comment]
Update to latest version of integration.
