### ISSUE TITLE
Media Sync not working with network storage on HA

### ISSUE THREAD

**Issue by arturolaz** [JurajNyiri/HomeAssistant-Tapo-Control#499]
### Description

I created a network storage share in HA with the name "HomeAssistantTapoMedia" and I'm trying to get the TapoControl integration to save the synced media there but it doesn't seem to be working

![image](https://github.com/JurajNyiri/HomeAssistant-Tapo-Control/assets/929297/27e94500-33ad-4630-ad1f-303ae9b9bb18)

I tried the "df -a -T -h" in the ssh terminal to be sure I was making reference to the correct mounted drive, there I can see "/media/HomeAssistantTapoMedia" which I'm making reference to in the cold storage field but I've had no luck with it.

![image](https://github.com/JurajNyiri/HomeAssistant-Tapo-Control/assets/929297/49058858-4d5c-4b9b-aea8-f64c7841cbe3)

### Reproduction Steps

1. Add a network storage drive to HA
2. Reference your path in the cold storage field for the Tapo Control integration

### Expected behavior

I expect to see files being transfered from the Tapo Camera to the selected network drive

### Device Firmware

Firmware: 1.1.7 Build 231122 Rel.55299n

### Integration Version

5.4.13

### Using stream component

Yes

### Does camera work via official integrations?

Yes

### Camera has all attributes filled out in developer tools

Yes

### HASS Environment

RPi4

### Search for similar issues

Yes

**Comment by JurajNyiri** [comment]
Hi, i had the same setup and it was downloading properly. Check the logs and see if it is actually downloading and if there are any errors.

**Comment by arturolaz** [comment]
Yesterday I made more tests and it worked, the problem was that I have quite a large amount of videos in the camera and the initial media scan was taking too long for me to notice an immediate start of sync after a reset.

Now I noticed another issue. No more than 4 videos are synced at the network drive before getting deleted and transfering another different 4 files. I have set the "number of hours to keep syncronized" to 24 just in case but made no difference.

**Comment by arturolaz** [comment]
I have tried setting different levels of permission to the folder but that also is not helping. I tried formating the SD card from the camera to be sure videos were newer than the "number of hours to keep syncronized" but also didn't work

I just saw this in the log:

2024-01-19 23:14:03.308 WARNING (MainThread) [pytapo.media_stream.session] Received response with no or invalid session information (sequence None, session None), can't be delivered
2024-01-19 23:16:27.638 WARNING (MainThread) [pytapo.media_stream.session] Received response with no or invalid session information (sequence None, session None), can't be delivered
2024-01-19 23:17:49.188 ERROR (MainThread) [custom_components.tapo_control] Invalid authentication data
2024-01-19 23:20:50.269 ERROR (MainThread) [custom_components.tapo_control] Unexpected error fetching Tapo resource status data: [Errno 2] No such file or directory: '/media/HomeAssistantTapoMedia//videos/1705727527-1705727592.mp4'
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 300, in _async_refresh
    self.data = await self._async_update_data()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 256, in _async_update_data
    return await self.update_method()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/tapo_control/__init__.py", line 508, in async_update_data
    await mediaCleanup(hass, entry)
  File "/config/custom_components/tapo_control/utils.py", line 355, in mediaCleanup
    deleteFilesNoLongerPresentInCamera(hass, entry_id, ".mp4", "videos")
  File "/config/custom_components/tapo_control/utils.py", line 290, in deleteFilesNoLongerPresentInCamera
    os.remove(filePath)
FileNotFoundError: [Errno 2] No such file or directory: '/media/HomeAssistantTapoMedia//videos/1705727527-1705727592.mp4'


Could you guide me on how to resolve this issue?
