### ISSUE TITLE
tapo control broken on latest HA 2024.2.0 version

### ISSUE THREAD

**Issue by aginies** [JurajNyiri/HomeAssistant-Tapo-Control#514]
### Description

Since latest HA update: Core 2024.2.0; Interface utilisateur 202420207.0, tapo control is not working anymore.

### Reproduction Steps

update the HA to latest version 2024.2.0

### Expected behavior

tapo control should work

### If applicable, add error logs.

2024-02-08 00:14:29.755 ERROR (MainThread) [homeassistant.setup] Setup failed for custom integration 'tapo_control': Unable to import component: No module named 'pytapo'
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 251, in _async_setup_component
    component = integration.get_component()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 827, in get_component
    ComponentProtocol, importlib.import_module(self.pkg_path)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 994, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/config/custom_components/tapo_control/__init__.py", line 50, in <module>
    from .utils import (
  File "/config/custom_components/tapo_control/utils.py", line 15, in <module>
    from pytapo.media_stream.downloader import Downloader
ModuleNotFoundError: No module named 'pytapo'

### Device Firmware

1.3.11

### Integration Version

2024.2.0

### Using stream component

Yes

### Does camera work via official integrations?

Yes

### Camera has all attributes filled out in developer tools

Yes

### HASS Environment

container

### Search for similar issues

Yes

**Comment by aginies** [comment]
Sounds like a full restart of HA has solved the issue.

**Comment by aginies** [comment]
closing as INVALID
