### ISSUE TITLE
New warning mesage

### ISSUE THREAD

**Issue by joe7045** [JurajNyiri/HomeAssistant-Tapo-Control#533]
### Description

After updating to 5.4.17 I started to receive this message:
Error while setting up tapo_control platform for sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 350, in _async_setup_platform
    await asyncio.shield(awaitable)
  File "/config/custom_components/tapo_control/sensor.py", line 84, in async_setup_entry
    sensors = await setupEntities(entry)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/tapo_control/sensor.py", line 43, in setupEntities
    and "ssid" in entry["camData"]["connectionInformation"]
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: argument of type 'bool' is not iterable

### Reproduction Steps

It appears after every restart of HA

### Expected behavior

Do not receive the message

### If applicable, add error logs.

Error while setting up tapo_control platform for sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 350, in _async_setup_platform
    await asyncio.shield(awaitable)
  File "/config/custom_components/tapo_control/sensor.py", line 84, in async_setup_entry
    sensors = await setupEntities(entry)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/tapo_control/sensor.py", line 43, in setupEntities
    and "ssid" in entry["camData"]["connectionInformation"]
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: argument of type 'bool' is not iterable

### Device Firmware

1.3.11 build 231117

### Integration Version

5.4.17

### Using stream component

Yes

### Does camera work via official integrations?

Yes

### Camera has all attributes filled out in developer tools

Yes

### HASS Environment

Core 2024.3.1 

### Search for similar issues

Yes

**Comment by JurajNyiri** [comment]
Please post debug logs of when this error happens

**Comment by joe7045** [comment]
Error has gone.
Now I have 
Tapo 5.4.17
Core 2024.4.0
Supervisor 2024.03.1
Operating System 12.1

Thank you. Next time I´ll try to provide you debug logs
