### ISSUE TITLE
Every update required to delete and add all cameras

### ISSUE THREAD

**Issue by brunohoff** [JurajNyiri/HomeAssistant-Tapo-Control#560]
### Description

I have 15 cameras (C200, C100 and C300) and every time that I update the tapo extension on Home Assistant all sensors stop working and the log is flooded with errors. Usually removing all cameras and adding it again fix the problem, however it also change the name of all sensors and require work to redo all the automation and integrations.

There is something that I can do to solve this?

Example of the current log:
```
2024-04-20 13:49:34.139 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry 10.1.4.13 for light
Traceback (most recent call last):
File "/srv/homeassistant/lib/python3.12/site-packages/homeassistant/config_entries.py", line 551, in async_setup
result = await component.async_setup_entry(hass, self)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/srv/homeassistant/lib/python3.12/site-packages/homeassistant/components/light/__init__.py", line 679, in async_setup_entry
return await component.async_setup_entry(entry)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/srv/homeassistant/lib/python3.12/site-packages/homeassistant/helpers/entity_component.py", line 187, in async_setup_entry
raise ValueError("Config entry has already been setup!")
ValueError: Config entry has already been setup!
2024-04-20 13:49:34.143 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry 10.1.4.13 for number
Traceback (most recent call last):
File "/srv/homeassistant/lib/python3.12/site-packages/homeassistant/config_entries.py", line 551, in async_setup
result = await component.async_setup_entry(hass, self)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/srv/homeassistant/lib/python3.12/site-packages/homeassistant/components/number/__init__.py", line 120, in async_setup_entry
return await component.async_setup_entry(entry)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/srv/homeassistant/lib/python3.12/site-packages/homeassistant/helpers/entity_component.py", line 187, in async_setup_entry
raise ValueError("Config entry has already been setup!")
ValueError: Config entry has already been setup!
2024-04-20 13:49:34.144 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry 10.1.4.13 for select
Traceback (most recent call last):
File "/srv/homeassistant/lib/python3.12/site-packages/homeassistant/config_entries.py", line 551, in async_setup
result = await component.async_setup_entry(hass, self)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/srv/homeassistant/lib/python3.12/site-packages/homeassistant/components/select/__init__.py", line 110, in async_setup_entry
return await component.async_setup_entry(entry)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/srv/homeassistant/lib/python3.12/site-packages/homeassistant/helpers/entity_component.py", line 187, in async_setup_entry
raise ValueError("Config entry has already been setup!")
ValueError: Config entry has already been setup!
```

### Reproduction Steps

Update the Tapo Extension

### Expected behavior

Camera and sensor continues to work without requiring to all all again

### If applicable, add error logs.

https://pastebin.com/NciPv4Pd

### Device Firmware

1.3.11 Build 231116

### Integration Version

Multiple versions, current the latest

### Using stream component

Yes

### Does camera work via official integrations?

Yes

### Camera has all attributes filled out in developer tools

Yes

### HASS Environment

Ubunto on NAC

### Search for similar issues

Yes

**Comment by JurajNyiri** [comment]
Environment is corrupted remove all mentions of tapo_control from .storage json files and restart ha. Then add cameras. Make sure to create backup in case you corrupt the files.

**Comment by brunohoff** [comment]
Thank you @JurajNyiri . I did that, restarted the HA, added all cameras and everything was working as expected. Restarted HA again and some Tapo cameras stop working the binary sensor with lots of error in the log ValueError: Config entry has already been setup!

I already tried this procedure in the past reading from other issues. Maybe something specific in my setup is corrupting the devices. There is something that I can do?

**Comment by JurajNyiri** [comment]
Hi is the error only for binary sensors or other entities as well? Do the binary sensors work even after that message?

**Comment by brunohoff** [comment]
Hello @JurajNyiri, apparently not all entities give this error and I'm not sure what buttons should stop working by the log, but the streaming of those cameras are still working. The binary sensor doesn't.

```
2024-04-21 02:33:51.788 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry 10.2.3.9 for camera
Traceback (most recent call last):
File "/srv/homeassistant/lib/python3.12/site-packages/homeassistant/config_entries.py", line 551, in async_setup
result = await component.async_setup_entry(hass, self)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/srv/homeassistant/lib/python3.12/site-packages/homeassistant/components/camera/__init__.py", line 470, in async_setup_entry
return await component.async_setup_entry(entry)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/srv/homeassistant/lib/python3.12/site-packages/homeassistant/helpers/entity_component.py", line 187, in async_setup_entry
raise ValueError("Config entry has already been setup!")
ValueError: Config entry has already been setup!
2024-04-21 02:33:51.794 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry 10.2.3.9 for switch
Traceback (most recent call last):
File "/srv/homeassistant/lib/python3.12/site-packages/homeassistant/config_entries.py", line 551, in async_setup
result = await component.async_setup_entry(hass, self)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/srv/homeassistant/lib/python3.12/site-packages/homeassistant/components/switch/__init__.py", line 100, in async_setup_entry
return await component.async_setup_entry(entry)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/srv/homeassistant/lib/python3.12/site-packages/homeassistant/helpers/entity_component.py", line 187, in async_setup_entry
raise ValueError("Config entry has already been setup!")
ValueError: Config entry has already been setup!
2024-04-21 02:33:51.796 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry 10.2.3.9 for button
Traceback (most recent call last):
File "/srv/homeassistant/lib/python3.12/site-packages/homeassistant/config_entries.py", line 551, in async_setup
result = await component.async_setup_entry(hass, self)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/srv/homeassistant/lib/python3.12/site-packages/homeassistant/components/button/__init__.py", line 73, in async_setup_entry
return await component.async_setup_entry(entry)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/srv/homeassistant/lib/python3.12/site-packages/homeassistant/helpers/entity_component.py", line 187, in async_setup_entry
raise ValueError("Config entry has already been setup!")
ValueError: Config entry has already been setup!
2024-04-21 02:33:51.798 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry 10.2.3.9 for light
Traceback (most recent call last):
File "/srv/homeassistant/lib/python3.12/site-packages/homeassistant/config_entries.py", line 551, in async_setup
result = await component.async_setup_entry(hass, self)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/srv/homeassistant/lib/python3.12/site-packages/homeassistant/components/light/__init__.py", line 679, in async_setup_entry
return await component.async_setup_entry(entry)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/srv/homeassistant/lib/python3.12/site-packages/homeassistant/helpers/entity_component.py", line 187, in async_setup_entry
raise ValueError("Config entry has already been setup!")
ValueError: Config entry has already been setup!
2024-04-21 02:33:51.799 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry 10.2.3.9 for number
Traceback (most recent call last):
File "/srv/homeassistant/lib/python3.12/site-packages/homeassistant/config_entries.py", line 551, in async_setup
result = await component.async_setup_entry(hass, self)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/srv/homeassistant/lib/python3.12/site-packages/homeassistant/components/number/__init__.py", line 120, in async_setup_entry
return await component.async_setup_entry(entry)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/srv/homeassistant/lib/python3.12/site-packages/homeassistant/helpers/entity_component.py", line 187, in async_setup_entry
raise ValueError("Config entry has already been setup!")
ValueError: Config entry has already been setup!
2024-04-21 02:33:51.801 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry 10.2.3.9 for select
Traceback (most recent call last):
File "/srv/homeassistant/lib/python3.12/site-packages/homeassistant/config_entries.py", line 551, in async_setup
result = await component.async_setup_entry(hass, self)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/srv/homeassistant/lib/python3.12/site-packages/homeassistant/components/select/__init__.py", line 110, in async_setup_entry
return await component.async_setup_entry(entry)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/srv/homeassistant/lib/python3.12/site-packages/homeassistant/helpers/entity_component.py", line 187, in async_setup_entry
raise ValueError("Config entry has already been setup!")
ValueError: Config entry has already been setup!
2024-04-21 02:33:51.803 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry 10.2.3.9 for siren
Traceback (most recent call last):
File "/srv/homeassistant/lib/python3.12/site-packages/homeassistant/config_entries.py", line 551, in async_setup
result = await component.async_setup_entry(hass, self)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/srv/homeassistant/lib/python3.12/site-packages/homeassistant/components/siren/__init__.py", line 154, in async_setup_entry
return await component.async_setup_entry(entry)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/srv/homeassistant/lib/python3.12/site-packages/homeassistant/helpers/entity_component.py", line 187, in async_setup_entry
raise ValueError("Config entry has already been setup!")
ValueError: Config entry has already been setup!
2024-04-21 02:33:51.805 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry 10.2.3.9 for update
Traceback (most recent call last):
File "/srv/homeassistant/lib/python3.12/site-packages/homeassistant/config_entries.py", line 551, in async_setup
result = await component.async_setup_entry(hass, self)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/srv/homeassistant/lib/python3.12/site-packages/homeassistant/components/update/__init__.py", line 123, in async_setup_entry
return await component.async_setup_entry(entry)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/srv/homeassistant/lib/python3.12/site-packages/homeassistant/helpers/entity_component.py", line 187, in async_setup_entry
raise ValueError("Config entry has already been setup!")
ValueError: Config entry has already been setup!
2024-04-21 02:33:51.806 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry 10.2.3.9 for binary_sensor
Traceback (most recent call last):
File "/srv/homeassistant/lib/python3.12/site-packages/homeassistant/config_entries.py", line 551, in async_setup
result = await component.async_setup_entry(hass, self)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/srv/homeassistant/lib/python3.12/site-packages/homeassistant/components/binary_sensor/__init__.py", line 239, in async_setup_entry
return await component.async_setup_entry(entry)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/srv/homeassistant/lib/python3.12/site-packages/homeassistant/helpers/entity_component.py", line 187, in async_setup_entry
raise ValueError("Config entry has already been setup!")
ValueError: Config entry has already been setup!
2024-04-21 02:33:51.808 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry 10.2.3.9 for sensor
Traceback (most recent call last):
File "/srv/homeassistant/lib/python3.12/site-packages/homeassistant/config_entries.py", line 551, in async_setup
result = await component.async_setup_entry(hass, self)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/srv/homeassistant/lib/python3.12/site-packages/homeassistant/components/sensor/__init__.py", line 139, in async_setup_entry
return await component.async_setup_entry(entry)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/srv/homeassistant/lib/python3.12/site-packages/homeassistant/helpers/entity_component.py", line 187, in async_setup_entry
raise ValueError("Config entry has already been setup!")
ValueError: Config entry has already been setup!
2024-04-21 02:33:53.780 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry 10.1.4.4 for camera
Traceback (most recent call last):
File "/srv/homeassistant/lib/python3.12/site-packages/homeassistant/config_entries.py", line 551, in async_setup
result = await component.async_setup_entry(hass, self)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/srv/homeassistant/lib/python3.12/site-packages/homeassistant/components/camera/__init__.py", line 470, in async_setup_entry
return await component.async_setup_entry(entry)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/srv/homeassistant/lib/python3.12/site-packages/homeassistant/helpers/entity_component.py", line 187, in async_setup_entry
raise ValueError("Config entry has already been setup!")
ValueError: Config entry has already been setup!
2024-04-21 02:33:53.782 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry 10.1.4.4 for switch
Traceback (most recent call last):
File "/srv/homeassistant/lib/python3.12/site-packages/homeassistant/config_entries.py", line 551, in async_setup
result = await component.async_setup_entry(hass, self)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/srv/homeassistant/lib/python3.12/site-packages/homeassistant/components/switch/__init__.py", line 100, in async_setup_entry
return await component.async_setup_entry(entry)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/srv/homeassistant/lib/python3.12/site-packages/homeassistant/helpers/entity_component.py", line 187, in async_setup_entry
raise ValueError("Config entry has already been setup!")
ValueError: Config entry has already been setup!
2024-04-21 02:33:53.784 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry 10.1.4.4 for button
Traceback (most recent call last):
File "/srv/homeassistant/lib/python3.12/site-packages/homeassistant/config_entries.py", line 551, in async_setup
result = await component.async_setup_entry(hass, self)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/srv/homeassistant/lib/python3.12/site-packages/homeassistant/components/button/__init__.py", line 73, in async_setup_entry
return await component.async_setup_entry(entry)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/srv/homeassistant/lib/python3.12/site-packages/homeassistant/helpers/entity_component.py", line 187, in async_setup_entry
raise ValueError("Config entry has already been setup!")
ValueError: Config entry has already been setup!
2024-04-21 02:33:53.787 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry 10.1.4.4 for light
Traceback (most recent call last):
File "/srv/homeassistant/lib/python3.12/site-packages/homeassistant/config_entries.py", line 551, in async_setup
result = await component.async_setup_entry(hass, self)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/srv/homeassistant/lib/python3.12/site-packages/homeassistant/components/light/__init__.py", line 679, in async_setup_entry
return await component.async_setup_entry(entry)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/srv/homeassistant/lib/python3.12/site-packages/homeassistant/helpers/entity_component.py", line 187, in async_setup_entry
raise ValueError("Config entry has already been setup!")
ValueError: Config entry has already been setup!
2024-04-21 02:33:53.788 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry 10.1.4.4 for number
Traceback (most recent call last):
File "/srv/homeassistant/lib/python3.12/site-packages/homeassistant/config_entries.py", line 551, in async_setup
result = await component.async_setup_entry(hass, self)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/srv/homeassistant/lib/python3.12/site-packages/homeassistant/components/number/__init__.py", line 120, in async_setup_entry
return await component.async_setup_entry(entry)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/srv/homeassistant/lib/python3.12/site-packages/homeassistant/helpers/entity_component.py", line 187, in async_setup_entry
raise ValueError("Config entry has already been setup!")
ValueError: Config entry has already been setup!
2024-04-21 02:33:53.789 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry 10.1.4.4 for select
Traceback (most recent call last):
File "/srv/homeassistant/lib/python3.12/site-packages/homeassistant/config_entries.py", line 551, in async_setup
result = await component.async_setup_entry(hass, self)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/srv/homeassistant/lib/python3.12/site-packages/homeassistant/components/select/__init__.py", line 110, in async_setup_entry
return await component.async_setup_entry(entry)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/srv/homeassistant/lib/python3.12/site-packages/homeassistant/helpers/entity_component.py", line 187, in async_setup_entry
raise ValueError("Config entry has already been setup!")
ValueError: Config entry has already been setup!
2024-04-21 02:33:53.791 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry 10.1.4.4 for siren
Traceback (most recent call last):
File "/srv/homeassistant/lib/python3.12/site-packages/homeassistant/config_entries.py", line 551, in async_setup
result = await component.async_setup_entry(hass, self)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/srv/homeassistant/lib/python3.12/site-packages/homeassistant/components/siren/__init__.py", line 154, in async_setup_entry
return await component.async_setup_entry(entry)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/srv/homeassistant/lib/python3.12/site-packages/homeassistant/helpers/entity_component.py", line 187, in async_setup_entry
raise ValueError("Config entry has already been setup!")
ValueError: Config entry has already been setup!
2024-04-21 02:33:53.793 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry 10.1.4.4 for update
Traceback (most recent call last):
File "/srv/homeassistant/lib/python3.12/site-packages/homeassistant/config_entries.py", line 551, in async_setup
result = await component.async_setup_entry(hass, self)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/srv/homeassistant/lib/python3.12/site-packages/homeassistant/components/update/__init__.py", line 123, in async_setup_entry
return await component.async_setup_entry(entry)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/srv/homeassistant/lib/python3.12/site-packages/homeassistant/helpers/entity_component.py", line 187, in async_setup_entry
raise ValueError("Config entry has already been setup!")
ValueError: Config entry has already been setup!
2024-04-21 02:33:53.794 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry 10.1.4.4 for binary_sensor
Traceback (most recent call last):
File "/srv/homeassistant/lib/python3.12/site-packages/homeassistant/config_entries.py", line 551, in async_setup
result = await component.async_setup_entry(hass, self)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/srv/homeassistant/lib/python3.12/site-packages/homeassistant/components/binary_sensor/__init__.py", line 239, in async_setup_entry
return await component.async_setup_entry(entry)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/srv/homeassistant/lib/python3.12/site-packages/homeassistant/helpers/entity_component.py", line 187, in async_setup_entry
raise ValueError("Config entry has already been setup!")
ValueError: Config entry has already been setup!
2024-04-21 02:33:53.795 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry 10.1.4.4 for sensor
Traceback (most recent call last):
File "/srv/homeassistant/lib/python3.12/site-packages/homeassistant/config_entries.py", line 551, in async_setup
result = await component.async_setup_entry(hass, self)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/srv/homeassistant/lib/python3.12/site-packages/homeassistant/components/sensor/__init__.py", line 139, in async_setup_entry
return await component.async_setup_entry(entry)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/srv/homeassistant/lib/python3.12/site-packages/homeassistant/helpers/entity_component.py", line 187, in async_setup_entry
raise ValueError("Config entry has already been setup!")
ValueError: Config entry has already been setup!
2024-04-21 02:33:54.578 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry 10.1.4.11 for camera
Traceback (most recent call last):
File "/srv/homeassistant/lib/python3.12/site-packages/homeassistant/config_entries.py", line 551, in async_setup
result = await component.async_setup_entry(hass, self)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/srv/homeassistant/lib/python3.12/site-packages/homeassistant/components/camera/__init__.py", line 470, in async_setup_entry
return await component.async_setup_entry(entry)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/srv/homeassistant/lib/python3.12/site-packages/homeassistant/helpers/entity_component.py", line 187, in async_setup_entry
raise ValueError("Config entry has already been setup!")
ValueError: Config entry has already been setup!
2024-04-21 02:33:54.579 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry 10.1.4.11 for switch
Traceback (most recent call last):
File "/srv/homeassistant/lib/python3.12/site-packages/homeassistant/config_entries.py", line 551, in async_setup
result = await component.async_setup_entry(hass, self)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/srv/homeassistant/lib/python3.12/site-packages/homeassistant/components/switch/__init__.py", line 100, in async_setup_entry
return await component.async_setup_entry(entry)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/srv/homeassistant/lib/python3.12/site-packages/homeassistant/helpers/entity_component.py", line 187, in async_setup_entry
raise ValueError("Config entry has already been setup!")
ValueError: Config entry has already been setup!
2024-04-21 02:33:54.580 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry 10.1.4.11 for button
Traceback (most recent call last):
File "/srv/homeassistant/lib/python3.12/site-packages/homeassistant/config_entries.py", line 551, in async_setup
result = await component.async_setup_entry(hass, self)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/srv/homeassistant/lib/python3.12/site-packages/homeassistant/components/button/__init__.py", line 73, in async_setup_entry
return await component.async_setup_entry(entry)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/srv/homeassistant/lib/python3.12/site-packages/homeassistant/helpers/entity_component.py", line 187, in async_setup_entry
raise ValueError("Config entry has already been setup!")
ValueError: Config entry has already been setup!
2024-04-21 02:33:54.585 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry 10.1.4.11 for light
Traceback (most recent call last):
File "/srv/homeassistant/lib/python3.12/site-packages/homeassistant/config_entries.py", line 551, in async_setup
result = await component.async_setup_entry(hass, self)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/srv/homeassistant/lib/python3.12/site-packages/homeassistant/components/light/__init__.py", line 679, in async_setup_entry
return await component.async_setup_entry(entry)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/srv/homeassistant/lib/python3.12/site-packages/homeassistant/helpers/entity_component.py", line 187, in async_setup_entry
raise ValueError("Config entry has already been setup!")
ValueError: Config entry has already been setup!
2024-04-21 02:33:54.587 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry 10.1.4.11 for number
Traceback (most recent call last):
File "/srv/homeassistant/lib/python3.12/site-packages/homeassistant/config_entries.py", line 551, in async_setup
result = await component.async_setup_entry(hass, self)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/srv/homeassistant/lib/python3.12/site-packages/homeassistant/components/number/__init__.py", line 120, in async_setup_entry
return await component.async_setup_entry(entry)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/srv/homeassistant/lib/python3.12/site-packages/homeassistant/helpers/entity_component.py", line 187, in async_setup_entry
raise ValueError("Config entry has already been setup!")
ValueError: Config entry has already been setup!
2024-04-21 02:33:54.588 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry 10.1.4.11 for select
Traceback (most recent call last):
File "/srv/homeassistant/lib/python3.12/site-packages/homeassistant/config_entries.py", line 551, in async_setup
result = await component.async_setup_entry(hass, self)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/srv/homeassistant/lib/python3.12/site-packages/homeassistant/components/select/__init__.py", line 110, in async_setup_entry
return await component.async_setup_entry(entry)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/srv/homeassistant/lib/python3.12/site-packages/homeassistant/helpers/entity_component.py", line 187, in async_setup_entry
raise ValueError("Config entry has already been setup!")
ValueError: Config entry has already been setup!
2024-04-21 02:33:54.590 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry 10.1.4.11 for siren
Traceback (most recent call last):
File "/srv/homeassistant/lib/python3.12/site-packages/homeassistant/config_entries.py", line 551, in async_setup
result = await component.async_setup_entry(hass, self)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/srv/homeassistant/lib/python3.12/site-packages/homeassistant/components/siren/__init__.py", line 154, in async_setup_entry
return await component.async_setup_entry(entry)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/srv/homeassistant/lib/python3.12/site-packages/homeassistant/helpers/entity_component.py", line 187, in async_setup_entry
raise ValueError("Config entry has already been setup!")
ValueError: Config entry has already been setup!
2024-04-21 02:33:54.592 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry 10.1.4.11 for update
Traceback (most recent call last):
File "/srv/homeassistant/lib/python3.12/site-packages/homeassistant/config_entries.py", line 551, in async_setup
result = await component.async_setup_entry(hass, self)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/srv/homeassistant/lib/python3.12/site-packages/homeassistant/components/update/__init__.py", line 123, in async_setup_entry
return await component.async_setup_entry(entry)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/srv/homeassistant/lib/python3.12/site-packages/homeassistant/helpers/entity_component.py", line 187, in async_setup_entry
raise ValueError("Config entry has already been setup!")
ValueError: Config entry has already been setup!
2024-04-21 02:33:54.593 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry 10.1.4.11 for binary_sensor
Traceback (most recent call last):
File "/srv/homeassistant/lib/python3.12/site-packages/homeassistant/config_entries.py", line 551, in async_setup
result = await component.async_setup_entry(hass, self)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/srv/homeassistant/lib/python3.12/site-packages/homeassistant/components/binary_sensor/__init__.py", line 239, in async_setup_entry
return await component.async_setup_entry(entry)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/srv/homeassistant/lib/python3.12/site-packages/homeassistant/helpers/entity_component.py", line 187, in async_setup_entry
raise ValueError("Config entry has already been setup!")
ValueError: Config entry has already been setup!
2024-04-21 02:33:54.595 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry 10.1.4.11 for sensor
Traceback (most recent call last):
File "/srv/homeassistant/lib/python3.12/site-packages/homeassistant/config_entries.py", line 551, in async_setup
result = await component.async_setup_entry(hass, self)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/srv/homeassistant/lib/python3.12/site-packages/homeassistant/components/sensor/__init__.py", line 139, in async_setup_entry
return await component.async_setup_entry(entry)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/srv/homeassistant/lib/python3.12/site-packages/homeassistant/helpers/entity_component.py", line 187, in async_setup_entry
raise ValueError("Config entry has already been setup!")
ValueError: Config entry has already been setup!
```

I only use the streaming and the binary sensor. If you like to consider creating an option when adding a Tapo device to not create all the other controllers, will be very helpful for my usage. Less entities, cleaner UI, less logs and quicker HA startup.
