### ISSUE TITLE
FFMPEG ERROR

### ISSUE THREAD

**Issue by whiteNsky** [JurajNyiri/HomeAssistant-Tapo-Control#566]
### Description

Newbie here, how to bypass this one

### Reproduction Steps

HA logs

### Expected behavior

Want to stream via HA

### If applicable, add error logs.

-----LOGS-----

2024-05-08 14:08:06.330 ERROR (MainThread) [homeassistant.components.camera] Error while setting up ffmpeg platform for camera
Traceback (most recent call last):
  File "C:\Users\Jordan\Desktop\HassWP_2024.4.3\python-3.12.3.amd64\Lib\site-packages\homeassistant\helpers\entity_platform.py", line 356, in _async_setup_platform
    await asyncio.shield(awaitable)
  File "C:\Users\Jordan\Desktop\HassWP_2024.4.3\python-3.12.3.amd64\Lib\site-packages\homeassistant\components\ffmpeg\camera.py", line 47, in async_setup_platform
    async_add_entities([FFmpegCamera(hass, config)])
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Jordan\Desktop\HassWP_2024.4.3\python-3.12.3.amd64\Lib\site-packages\homeassistant\components\ffmpeg\camera.py", line 59, in __init__
    self._manager: FFmpegManager = hass.data[DATA_FFMPEG]
                                   ~~~~~~~~~^^^^^^^^^^^^^
KeyError: 'ffmpeg'

### Device Firmware

latest build

### Integration Version

latest version

### Using stream component

Yes

### Does camera work via official integrations?

Yes

### Camera has all attributes filled out in developer tools

Yes

### HASS Environment

Home Assistant Windows 10 OS

### Search for similar issues

Yes

### Additional information

_No response_

**Comment by JurajNyiri** [comment]
Not an integration isssue.

**Comment by JurajNyiri** [comment]
You are probably missing ffmpeg and are running unsupported install method for ha.

**Comment by whiteNsky** [comment]
How to fix this problem?
Should I need to install the HA os on raspberry pi. As of now I am using HA
on windows 10

**Comment by JurajNyiri** [comment]
Using [supported installation](https://www.home-assistant.io/installation/) method will fix it automatically, like the proper install of HA OS.

Or just install ffmpeg, but you need to be able to google and find solutions to your issues if you are using unsupported HA install.
