### ISSUE TITLE
Reconfigure Integration Prompt: temporary_suspension error

### ISSUE THREAD

**Issue by dalgibbard** [JurajNyiri/HomeAssistant-Tapo-Control#609]
### Description

In HA today I noticed it was prompting me to reconfigure the integration for both of my cameras; when following the reconfigure flow, on getting to the login step (local credentials) I get a 'temporary_suspension' error.

![Screenshot_20240613_184447_Home Assistant](https://github.com/JurajNyiri/HomeAssistant-Tapo-Control/assets/1159620/35390fda-486c-4121-8ca4-0e7a347d0636)

![Screenshot_20240613_184411_Home Assistant](https://github.com/JurajNyiri/HomeAssistant-Tapo-Control/assets/1159620/afba8139-f246-42b7-8128-3be86a76f65e)

![Screenshot_20240613_183749_Home Assistant](https://github.com/JurajNyiri/HomeAssistant-Tapo-Control/assets/1159620/aaa39961-2bd4-4921-bc84-147f21064141)

### Reproduction Steps

Follow reconfiguration prompts, complete login info, get error.

### Expected behavior

Shouldn't need to reconfigure when no account information has changed, and when needing to change account information, it should work.

### If applicable, add error logs.

```
This error originated from a custom integration.

Logger: custom_components.tapo.coordinators
Source: helpers/update_coordinator.py:344
integration: TP-Link Tapo (documentation, issues)
First occurred: 12 June 2024 at 20:23:12 (191 occurrences)
Last logged: 18:37:04

Error fetching tapo data: Unexpected exception:
```
```
This error originated from a custom integration.

Logger: custom_components.tapo_control
Source: helpers/update_coordinator.py:312
integration: Tapo: Cameras Control (documentation, issues)
First occurred: 18:32:12 (6 occurrences)
Last logged: 18:39:43

Unexpected error fetching Tapo resource status data
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 312, in _async_refresh
    self.data = await self._async_update_data()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 268, in _async_update_data
    return await self.update_method()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/tapo_control/__init__.py", line 455, in async_update_data
    raise e
  File "/config/custom_components/tapo_control/__init__.py", line 446, in async_update_data
    updateDataForAllControllers[controller] = await getCamData(
                                              ^^^^^^^^^^^^^^^^^
  File "/config/custom_components/tapo_control/utils.py", line 627, in getCamData
    data = await hass.async_add_executor_job(controller.getMost)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/pytapo/__init__.py", line 1845, in getMost
    results = self.performRequest(requestData)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/pytapo/__init__.py", line 618, in performRequest
    self.refreshStok()
  File "/usr/local/lib/python3.12/site-packages/pytapo/__init__.py", line 423, in refreshStok
    raise Exception("Invalid authentication data")
Exception: Invalid authentication data
```
```
Logger: homeassistant
Source: /usr/src/homeassistant/homeassistant/runner.py:148
First occurred: 18:40:21 (10 occurrences)
Last logged: 18:41:08

Error doing job: Task exception was never retrieved (None)
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/onvif/managers.py", line 189, in _renew_or_restart_subscription
    await self._renew_subscription() or await self._restart_subscription()
                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/onvif/managers.py", line 154, in _restart_subscription
    return await self._start()
           ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/onvif/managers.py", line 298, in _start
    result = await events_service.CreatePullPointSubscription(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/zeep/proxy.py", line 64, in __call__
    return await self._proxy._binding.send_async(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/zeep/wsdl/bindings/soap.py", line 164, in send_async
    return self.process_reply(client, operation_obj, response)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/zeep/wsdl/bindings/soap.py", line 229, in process_reply
    return self.process_error(doc, operation)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/zeep/wsdl/bindings/soap.py", line 391, in process_error
    raise Fault(
zeep.exceptions.Fault: Authority failure
```

### Device Firmware

Version:1.2.1 Build 240401 Rel.61067n

### Integration Version

5.4.18

### Using stream component

Yes

### Does camera work via official integrations?

Yes

### Camera has all attributes filled out in developer tools

Yes

### HASS Environment

Docker on physical host

### Search for similar issues

Yes

**Comment by dalgibbard** [comment]
Apologies, didn't see this one : https://github.com/JurajNyiri/HomeAssistant-Tapo-Control/issues/551
