### ISSUE TITLE
error_code: -40106. Manual Alarm Start C125

### ISSUE THREAD

**Issue by loganbrooks25** [JurajNyiri/HomeAssistant-Tapo-Control#628]
### Description

Cannot use the 'Manual Alarm Start' and "Stop' option for C125. 
Get the following error: 
"Failed to call service button/press. Error: Parameter to get/do does not exist, Response: {"error_code": -40106}"
Otherwise works great on C110 devices, just not C125. 

### Reproduction Steps

1. Go to controls. 
2. Click on "Manual Alarm Start". Get error "Failed to call service button/press. Error: Parameter to get/do does not exist, Response: {"error_code": -40106}"

### Expected behavior

Alarm to start manually. 

### If applicable, add error logs.

2024-07-19 19:04:24.104 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [140734350921872] Unexpected exception
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 241, in handle_call_service
response = await hass.services.async_call(
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/src/homeassistant/homeassistant/core.py", line 2731, in async_call
response_data = await coro
^^^^^^^^^^
File "/usr/src/homeassistant/homeassistant/core.py", line 2774, in _execute_service
return await target(service_call)
^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 999, in entity_service_call
single_response = await _handle_entity_call(
^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 1071, in _handle_entity_call
result = await task
^^^^^^^^^^
File "/usr/src/homeassistant/homeassistant/components/button/__init__.py", line 132, in _async_press_action
await self.async_press()
File "/config/custom_components/tapo_control/button.py", line 125, in async_press
await self._hass.async_add_executor_job(self._controller.startManualAlarm)
File "/usr/local/lib/python3.12/concurrent/futures/thread.py", line 58, in run
result = self.fn(*self.args, **self.kwargs)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.12/site-packages/pytapo/__init__.py", line 1647, in startManualAlarm
return self.performRequest(
^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.12/site-packages/pytapo/__init__.py", line 621, in performRequest
raise Exception(
Exception: Error: Parameter to get/do does not exist, Response: {"error_code": -40106}

### Device Firmware

1.1.12 Build 240604 Rel.64460n

### Integration Version

5.4.26

### Using stream component

Yes

### Does camera work via official integrations?

Yes

### Camera has all attributes filled out in developer tools

Yes

### HASS Environment

Docker

### Search for similar issues

Yes

**Comment by JurajNyiri** [comment]
https://github.com/JurajNyiri/HomeAssistant-Tapo-Control/issues/545

**Comment by JurajNyiri** [comment]
This PR might help once finished https://github.com/JurajNyiri/HomeAssistant-Tapo-Control/pull/559
