### ISSUE TITLE
D230 privacy mode (switch.doorbell_privacy) missing in HA (available in Tapo app)

### ISSUE THREAD

**Issue by RedNo7** [JurajNyiri/HomeAssistant-Tapo-Control#629]
### Description

I had power outage resulting in most of my doorbell entities being permanently `unavailabel` - I was unable to remove the device so pulled the plug on the hub, restarted HA and re-added the hub - all good.

However, the doorbell camera privacy mode no longer exists in HA (and the doorbell night vision is unable to be set to `auto` but this ticket is about the privacy mode).

### Reproduction Steps

1. goto TP-link and add hub
2. Hub  is added and doorbell becomes available
3. doorbell privacy mode is missing as an entity.

### Expected behavior

I expect doorbell privacy mode switch to exist (it exists in mu phone's Tapo app).

The privacy mode switch was available in HA prior to my outage.

### If applicable, add error logs.

Not sure is this log entry is relevant:

```
This error originated from a custom integration.

Logger: custom_components.tapo_control
Source: helpers/update_coordinator.py:312
integration: Tapo: Cameras Control (documentation, issues)
First occurred: 10:55:43 (1 occurrences)
Last logged: 10:55:43

Unexpected error fetching Tapo resource status data
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 312, in _async_refresh
    self.data = await self._async_update_data()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 268, in _async_update_data
    return await self.update_method()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/tapo_control/__init__.py", line 463, in async_update_data
    raise e
  File "/config/custom_components/tapo_control/__init__.py", line 454, in async_update_data
    updateDataForAllControllers[controller] = await getCamData(
                                              ^^^^^^^^^^^^^^^^^
  File "/config/custom_components/tapo_control/utils.py", line 639, in getCamData
    data = await hass.async_add_executor_job(controller.getMost)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/pytapo/__init__.py", line 1871, in getMost
    results = self.performRequest(requestData)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/pytapo/__init__.py", line 618, in performRequest
    self.refreshStok()
  File "/usr/local/lib/python3.12/site-packages/pytapo/__init__.py", line 423, in refreshStok
    raise Exception("Invalid authentication data")
Exception: Invalid authentication data
```

### Device Firmware

1.1.16 build 20240617 rel. 65780

### Integration Version

5.4.26

### Using stream component

No

### Does camera work via official integrations?

Yes

### Camera has all attributes filled out in developer tools

Yes

### HASS Environment

Docker on RPi-4

### Search for similar issues

Yes

### Additional information

I wasn't sure if https://github.com/JurajNyiri/HomeAssistant-Tapo-Control/issues/540 is related or not.  It has an `invalid` label.

I also mentioned my issue with being unable to select `auto` for night vision as not sure if it is relevant or not.  Selecting `on` or `off` works.  This ticket is not about that though (keeping it to one topic). However, for info, When I select 'auto' or `off` in the UI, I get the following error:
![Screenshot 2024-07-20 at 11 07 25](https://github.com/user-attachments/assets/995a31fe-5aaa-44c6-b25f-894d04f20f8d)

**Comment by JurajNyiri** [comment]
Hello try to remove the camera and add it back again

**Comment by RedNo7** [comment]
thanks for such a fast reply!

Doing it now.  The already better news is that I was able to remove it this time (without switching the hub off).  Will update in a few...

**Comment by RedNo7** [comment]
Hi - still missing
![Screenshot 2024-07-20 at 11 25 35](https://github.com/user-attachments/assets/0b138b1f-3d56-4bac-8305-3d2def92d302)

**Comment by JurajNyiri** [comment]
- Are there any errors in the log?
- Did you change anything else? Update integration or anything?

**Comment by RedNo7** [comment]
I did update HA from 2024.7.2 to 2024.7.3 - I can downgrade if you';d like me to try that?

I restarted after removing the hub/doorbell, so here are the logs since then...

```
2024-07-20 11:22:50.773 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration tapo_control which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2024-07-20 11:22:50.775 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration dyson_local which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2024-07-20 11:22:50.777 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration sun2 which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2024-07-20 11:22:50.778 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration hypervolt_charger which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2024-07-20 11:22:50.780 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration feedparser which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2024-07-20 11:22:50.782 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration hacs which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2024-07-20 11:23:05.103 WARNING (MainThread) [homeassistant.helpers.frame] Detected that custom integration 'hacs' calls hass.http.register_static_path which is deprecated because it does blocking I/O in the event loop, instead call `await hass.http.async_register_static_paths([StaticPathConfig("/hacsfiles/frontend", "/config/custom_components/hacs/hacs_frontend", False)])`; This function will be removed in 2025.7 at custom_components/hacs/frontend.py, line 54: hass.http.register_static_path(f"{URL_BASE}/frontend", locate_dir(), cache_headers=False), please create a bug report at https://github.com/hacs/integration/issues
2024-07-20 11:23:05.126 WARNING (MainThread) [homeassistant.helpers.frame] Detected that custom integration 'hacs' calls hass.http.register_static_path which is deprecated because it does blocking I/O in the event loop, instead call `await hass.http.async_register_static_paths([StaticPathConfig("/hacsfiles/iconset.js", "/config/custom_components/hacs/iconset.js", True)])`; This function will be removed in 2025.7 at custom_components/hacs/frontend.py, line 57: hass.http.register_static_path(, please create a bug report at https://github.com/hacs/integration/issues
2024-07-20 11:23:05.135 WARNING (MainThread) [homeassistant.helpers.frame] Detected that custom integration 'hacs' accesses hass.components.frontend. This is deprecated and will stop working in Home Assistant 2024.9, it should be updated to import functions used from frontend directly at custom_components/hacs/frontend.py, line 68: hass.components.frontend.async_register_built_in_panel(, please create a bug report at https://github.com/hacs/integration/issues
2024-07-20 11:23:05.151 WARNING (MainThread) [homeassistant.helpers.frame] Detected that custom integration 'hacs' calls hass.http.register_static_path which is deprecated because it does blocking I/O in the event loop, instead call `await hass.http.async_register_static_paths([StaticPathConfig("/hacsfiles", "/config/www/community", False)])`; This function will be removed in 2025.7 at custom_components/hacs/base.py, line 1162: self.hass.http.register_static_path(, please create a bug report at https://github.com/hacs/integration/issues
2024-07-20 11:23:08.494 WARNING (MainThread) [homeassistant.helpers.frame] Detected that custom integration 'dyson_local' calls async_forward_entry_setup for integration, dyson_local with title: Pure Cool and entry_id: 1c3f95d046f740418d0b03b4d2504fdc, which is deprecated and will stop working in Home Assistant 2025.6, await async_forward_entry_setups instead at custom_components/dyson_local/__init__.py, line 137: hass.async_create_task(, please create a bug report at https://github.com/libdyson-wg/ha-dyson/issues
2024-07-20 11:23:08.772 WARNING (MainThread) [homeassistant.helpers.frame] Detected code that calls async_forward_entry_setup for integration dyson_local with title: Pure Cool and entry_id: 1c3f95d046f740418d0b03b4d2504fdc, during setup without awaiting async_forward_entry_setup, which can cause the setup lock to be released before the setup is done. This will stop working in Home Assistant 2025.1. Please report this issue.
Stack (most recent call last):
File "<frozen runpy>", line 198, in _run_module_as_main
File "<frozen runpy>", line 88, in _run_code
File "/usr/src/homeassistant/homeassistant/__main__.py", line 223, in <module>
sys.exit(main())
File "/usr/src/homeassistant/homeassistant/__main__.py", line 209, in main
exit_code = runner.run(runtime_conf)
File "/usr/src/homeassistant/homeassistant/runner.py", line 190, in run
return loop.run_until_complete(setup_and_run_hass(runtime_config))
File "/usr/local/lib/python3.12/asyncio/base_events.py", line 674, in run_until_complete
self.run_forever()
File "/usr/local/lib/python3.12/asyncio/base_events.py", line 641, in run_forever
self._run_once()
File "/usr/local/lib/python3.12/asyncio/base_events.py", line 1990, in _run_once
handle._run()
File "/usr/local/lib/python3.12/asyncio/events.py", line 88, in _run
self._context.run(self._callback, *self._args)
File "/usr/src/homeassistant/homeassistant/config_entries.py", line 2122, in async_forward_entry_setup
_report_non_awaited_platform_forwards(entry, "async_forward_entry_setup")
File "/usr/src/homeassistant/homeassistant/config_entries.py", line 1175, in _report_non_awaited_platform_forwards
report(
File "/usr/src/homeassistant/homeassistant/helpers/frame.py", line 151, in report
_LOGGER.warning(msg, stack_info=True)
2024-07-20 11:23:08.888 WARNING (MainThread) [homeassistant.helpers.frame] Detected code that calls async_forward_entry_setup for integration dyson_local with title: Pure Cool and entry_id: 1c3f95d046f740418d0b03b4d2504fdc, during setup without awaiting async_forward_entry_setup, which can cause the setup lock to be released before the setup is done. This will stop working in Home Assistant 2025.1. Please report this issue.
Stack (most recent call last):
File "<frozen runpy>", line 198, in _run_module_as_main
File "<frozen runpy>", line 88, in _run_code
File "/usr/src/homeassistant/homeassistant/__main__.py", line 223, in <module>
sys.exit(main())
File "/usr/src/homeassistant/homeassistant/__main__.py", line 209, in main
exit_code = runner.run(runtime_conf)
File "/usr/src/homeassistant/homeassistant/runner.py", line 190, in run
return loop.run_until_complete(setup_and_run_hass(runtime_config))
File "/usr/local/lib/python3.12/asyncio/base_events.py", line 674, in run_until_complete
self.run_forever()
File "/usr/local/lib/python3.12/asyncio/base_events.py", line 641, in run_forever
self._run_once()
File "/usr/local/lib/python3.12/asyncio/base_events.py", line 1990, in _run_once
handle._run()
File "/usr/local/lib/python3.12/asyncio/events.py", line 88, in _run
self._context.run(self._callback, *self._args)
File "/usr/src/homeassistant/homeassistant/config_entries.py", line 2122, in async_forward_entry_setup
_report_non_awaited_platform_forwards(entry, "async_forward_entry_setup")
File "/usr/src/homeassistant/homeassistant/config_entries.py", line 1175, in _report_non_awaited_platform_forwards
report(
File "/usr/src/homeassistant/homeassistant/helpers/frame.py", line 151, in report
_LOGGER.warning(msg, stack_info=True)
2024-07-20 11:23:08.906 WARNING (MainThread) [homeassistant.helpers.frame] Detected code that calls async_forward_entry_setup for integration dyson_local with title: Pure Cool and entry_id: 1c3f95d046f740418d0b03b4d2504fdc, during setup without awaiting async_forward_entry_setup, which can cause the setup lock to be released before the setup is done. This will stop working in Home Assistant 2025.1. Please report this issue.
Stack (most recent call last):
File "<frozen runpy>", line 198, in _run_module_as_main
File "<frozen runpy>", line 88, in _run_code
File "/usr/src/homeassistant/homeassistant/__main__.py", line 223, in <module>
sys.exit(main())
File "/usr/src/homeassistant/homeassistant/__main__.py", line 209, in main
exit_code = runner.run(runtime_conf)
File "/usr/src/homeassistant/homeassistant/runner.py", line 190, in run
return loop.run_until_complete(setup_and_run_hass(runtime_config))
File "/usr/local/lib/python3.12/asyncio/base_events.py", line 674, in run_until_complete
self.run_forever()
File "/usr/local/lib/python3.12/asyncio/base_events.py", line 641, in run_forever
self._run_once()
File "/usr/local/lib/python3.12/asyncio/base_events.py", line 1990, in _run_once
handle._run()
File "/usr/local/lib/python3.12/asyncio/events.py", line 88, in _run
self._context.run(self._callback, *self._args)
File "/usr/src/homeassistant/homeassistant/config_entries.py", line 2122, in async_forward_entry_setup
_report_non_awaited_platform_forwards(entry, "async_forward_entry_setup")
File "/usr/src/homeassistant/homeassistant/config_entries.py", line 1175, in _report_non_awaited_platform_forwards
report(
File "/usr/src/homeassistant/homeassistant/helpers/frame.py", line 151, in report
_LOGGER.warning(msg, stack_info=True)
2024-07-20 11:23:08.920 WARNING (MainThread) [homeassistant.helpers.frame] Detected code that calls async_forward_entry_setup for integration dyson_local with title: Pure Cool and entry_id: 1c3f95d046f740418d0b03b4d2504fdc, during setup without awaiting async_forward_entry_setup, which can cause the setup lock to be released before the setup is done. This will stop working in Home Assistant 2025.1. Please report this issue.
Stack (most recent call last):
File "<frozen runpy>", line 198, in _run_module_as_main
File "<frozen runpy>", line 88, in _run_code
File "/usr/src/homeassistant/homeassistant/__main__.py", line 223, in <module>
sys.exit(main())
File "/usr/src/homeassistant/homeassistant/__main__.py", line 209, in main
exit_code = runner.run(runtime_conf)
File "/usr/src/homeassistant/homeassistant/runner.py", line 190, in run
return loop.run_until_complete(setup_and_run_hass(runtime_config))
File "/usr/local/lib/python3.12/asyncio/base_events.py", line 674, in run_until_complete
self.run_forever()
File "/usr/local/lib/python3.12/asyncio/base_events.py", line 641, in run_forever
self._run_once()
File "/usr/local/lib/python3.12/asyncio/base_events.py", line 1990, in _run_once
handle._run()
File "/usr/local/lib/python3.12/asyncio/events.py", line 88, in _run
self._context.run(self._callback, *self._args)
File "/usr/src/homeassistant/homeassistant/config_entries.py", line 2122, in async_forward_entry_setup
_report_non_awaited_platform_forwards(entry, "async_forward_entry_setup")
File "/usr/src/homeassistant/homeassistant/config_entries.py", line 1175, in _report_non_awaited_platform_forwards
report(
File "/usr/src/homeassistant/homeassistant/helpers/frame.py", line 151, in report
_LOGGER.warning(msg, stack_info=True)
2024-07-20 11:23:09.998 ERROR (MainThread) [homeassistant.helpers.event] Error while processing template: Template<template=({% from 'met_office_codes.jinja' import code2ha %} {% set dh = state_attr('sensor.local_datahub_3_hourly','timeSeries') %} {% set ns = namespace(forecast=[]) %} {% for ts in dh -%}
{% if 'T00' in ts['time'] or 'T12' in ts['time'] and ts['time']|as_datetime > now() -%}
{% set index = (dh|map(attribute='time')|list).index(ts['time']) -%}
{% set dhr = dh[((0,index-1,dh|count)|sort)[1]:((0,index+2,dh|count)|sort)[1]] %}
{% set tsd = { 'datetime': (ts['time']|as_datetime).isoformat(),
'is_daytime': 'T12' in ts['time'],
'condition': code2ha(ts['significantWeatherCode']),
'humidity': dhr|map(attribute='screenRelativeHumidity')|average|round(0),
'pressure': dhr|map(attribute='mslp')|average|round(0),
'temperature': dhr|map(attribute='maxScreenAirTemp')|max|round(0),
'templow': dhr|map(attribute='minScreenAirTemp')|min|round(0),
'precipitation_probability': dhr|map(attribute='probOfPrecipitation')|average|round(0),
'wind_speed': dhr|map(attribute='windSpeed10m')|average|round(0) } -%}
{% set ns.forecast = ns.forecast + [tsd] -%}
{% endif -%}
{% endfor %} {{ ns.forecast }}) renders=2>
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/helpers/template.py", line 604, in async_render
render_result = _render_with_context(self.template, compiled, **kwargs)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/src/homeassistant/homeassistant/helpers/template.py", line 2639, in _render_with_context
return template.render(**kwargs)
^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.12/site-packages/jinja2/environment.py", line 1304, in render
self.environment.handle_exception()
File "/usr/local/lib/python3.12/site-packages/jinja2/environment.py", line 939, in handle_exception
raise rewrite_traceback_stack(source=source)
File "<template>", line 1, in top-level template code
TypeError: 'NoneType' object is not iterable
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/helpers/template.py", line 716, in async_render_to_info
render_info._result = self.async_render( # noqa: SLF001
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/src/homeassistant/homeassistant/helpers/template.py", line 606, in async_render
raise TemplateError(err) from err
homeassistant.exceptions.TemplateError: TypeError: 'NoneType' object is not iterable
2024-07-20 11:23:10.037 ERROR (MainThread) [homeassistant.components.template.template_entity] TemplateError('TypeError: 'NoneType' object is not iterable') while processing template 'Template<template=({% from 'met_office_codes.jinja' import code2ha %} {% set dh = state_attr('sensor.local_datahub_3_hourly','timeSeries') %} {% set ns = namespace(forecast=[]) %} {% for ts in dh -%}
{% if 'T00' in ts['time'] or 'T12' in ts['time'] and ts['time']|as_datetime > now() -%}
{% set index = (dh|map(attribute='time')|list).index(ts['time']) -%}
{% set dhr = dh[((0,index-1,dh|count)|sort)[1]:((0,index+2,dh|count)|sort)[1]] %}
{% set tsd = { 'datetime': (ts['time']|as_datetime).isoformat(),
'is_daytime': 'T12' in ts['time'],
'condition': code2ha(ts['significantWeatherCode']),
'humidity': dhr|map(attribute='screenRelativeHumidity')|average|round(0),
'pressure': dhr|map(attribute='mslp')|average|round(0),
'temperature': dhr|map(attribute='maxScreenAirTemp')|max|round(0),
'templow': dhr|map(attribute='minScreenAirTemp')|min|round(0),
'precipitation_probability': dhr|map(attribute='probOfPrecipitation')|average|round(0),
'wind_speed': dhr|map(attribute='windSpeed10m')|average|round(0) } -%}
{% set ns.forecast = ns.forecast + [tsd] -%}
{% endif -%}
{% endfor %} {{ ns.forecast }}) renders=4>' for attribute '_forecast_twice_daily' in entity 'weather.met_office_datahub'
2024-07-20 11:23:10.359 WARNING (MainThread) [homeassistant.helpers.frame] Detected that custom integration 'hacs' accesses hass.helpers.event. This is deprecated and will stop working in Home Assistant 2024.11, it should be updated to import functions used from event directly at custom_components/hacs/base.py, line 630: self.hass.helpers.event.async_track_time_interval(, please create a bug report at https://github.com/hacs/integration/issues
2024-07-20 11:24:30.668 ERROR (MainThread) [homeassistant.components.switch] Error while setting up tapo_control platform for switch
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 364, in _async_setup_platform
await asyncio.shield(awaitable)
File "/config/custom_components/tapo_control/switch.py", line 166, in async_setup_entry
switches = await setupEntities(entry)
^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/config/custom_components/tapo_control/switch.py", line 144, in setupEntities
and "video_capability" in entry["camData"]["videoCapability"]
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: argument of type 'bool' is not iterable
2024-07-20 11:24:31.555 WARNING (MainThread) [homeassistant.components.select] Setup of select platform tapo_control is taking over 10 seconds.
2024-07-20 11:25:20.635 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [548047419664] Unexpected exception
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 241, in handle_call_service
response = await hass.services.async_call(
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/src/homeassistant/homeassistant/core.py", line 2731, in async_call
response_data = await coro
^^^^^^^^^^
File "/usr/src/homeassistant/homeassistant/core.py", line 2774, in _execute_service
return await target(service_call)
^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 999, in entity_service_call
single_response = await _handle_entity_call(
^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 1071, in _handle_entity_call
result = await task
^^^^^^^^^^
File "/usr/src/homeassistant/homeassistant/components/select/__init__.py", line 188, in async_handle_select_option
await self.async_select_option(option)
File "/config/custom_components/tapo_control/select.py", line 315, in async_select_option
result = await self._hass.async_add_executor_job(
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.12/concurrent/futures/thread.py", line 58, in run
result = self.fn(*self.args, **self.kwargs)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.12/site-packages/pytapo/__init__.py", line 1576, in setDayNightMode
return self.setNightVisionModeConfig("md_night_vision")
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.12/site-packages/pytapo/__init__.py", line 1586, in setNightVisionModeConfig
return self.executeFunction(
^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.12/site-packages/pytapo/__init__.py", line 510, in executeFunction
raise Exception(
Exception: Error: 60305, Response: {"method": "setNightVisionModeConfig", "result": {}, "error_code": 60305}
2024-07-20 11:25:23.572 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [548047419664] Unexpected exception
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 241, in handle_call_service
response = await hass.services.async_call(
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/src/homeassistant/homeassistant/core.py", line 2731, in async_call
response_data = await coro
^^^^^^^^^^
File "/usr/src/homeassistant/homeassistant/core.py", line 2774, in _execute_service
return await target(service_call)
^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 999, in entity_service_call
single_response = await _handle_entity_call(
^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 1071, in _handle_entity_call
result = await task
^^^^^^^^^^
File "/usr/src/homeassistant/homeassistant/components/select/__init__.py", line 188, in async_handle_select_option
await self.async_select_option(option)
File "/config/custom_components/tapo_control/select.py", line 315, in async_select_option
result = await self._hass.async_add_executor_job(
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.12/concurrent/futures/thread.py", line 58, in run
result = self.fn(*self.args, **self.kwargs)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.12/site-packages/pytapo/__init__.py", line 1572, in setDayNightMode
return self.setNightVisionModeConfig("inf_night_vision")
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.12/site-packages/pytapo/__init__.py", line 1586, in setNightVisionModeConfig
return self.executeFunction(
^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.12/site-packages/pytapo/__init__.py", line 491, in executeFunction
data = self.performRequest(
^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.12/site-packages/pytapo/__init__.py", line 618, in performRequest
self.refreshStok()
File "/usr/local/lib/python3.12/site-packages/pytapo/__init__.py", line 423, in refreshStok
raise Exception("Invalid authentication data")
Exception: Invalid authentication data
2024-07-20 11:25:26.694 ERROR (MainThread) [custom_components.tapo_control] [initOnvifEvents] Initiating onvif connection failed.
2024-07-20 11:25:26.694 ERROR (MainThread) [custom_components.tapo_control]
2024-07-20 11:25:34.588 ERROR (SyncWorker_1) [homeassistant] Error doing job: Task exception was never retrieved (None)
Traceback (most recent call last):
File "/config/custom_components/tapo_control/utils.py", line 1175, in update_listener
hass.data[DOMAIN][entry.entry_id]["eventsDevice"] = onvifDevice["device"]
~~~~~~~~~~~^^^^^^^^^^
TypeError: 'bool' object is not subscriptable
```

**Comment by JurajNyiri** [comment]
Fixed in https://github.com/JurajNyiri/HomeAssistant-Tapo-Control/releases/tag/5.4.27

**Comment by RedNo7** [comment]
should I now raise a separate issue for selecting `auto` for night vision or does the fix address both?

**Comment by JurajNyiri** [comment]
Yes please, make sure to document what you see in the app for that option as well please and we can take it from there.

**Comment by RedNo7** [comment]
great - thanks
