### ISSUE TITLE
Event entity is not created

### ISSUE THREAD

**Issue by tomasbedrich** [JurajNyiri/HomeAssistant-Tapo-Control#676]
### Description

Event entity is not created

### Reproduction Steps

Setup according to default install procedure with C325WB.

Event integration using Webhook / long-polling: doesn't matter - the same result.

### Expected behavior

Event entity should be automatically created when motion is detected for the first time (as per README)

### If applicable, add error logs.

```
2024-09-16 12:02:32.201 DEBUG (MainThread) [custom_components.tapo_control] [initOnvifEvents] Creating onvif connection...
2024-09-16 12:02:32.252 DEBUG (MainThread) [custom_components.tapo_control] [initOnvifEvents] Connection estabilished.
2024-09-16 12:02:32.253 DEBUG (MainThread) [custom_components.tapo_control] [initOnvifEvents] Getting device information...
2024-09-16 12:02:32.274 DEBUG (MainThread) [custom_components.tapo_control] [initOnvifEvents] Got device information.
2024-09-16 12:02:32.274 DEBUG (MainThread) [custom_components.tapo_control] setupOnvif - entry
2024-09-16 12:02:32.274 DEBUG (MainThread) [custom_components.tapo_control] Setting up onvif...
2024-09-16 12:02:32.274 DEBUG (MainThread) [custom_components.tapo_control] setupEvents - entry
2024-09-16 12:02:32.275 DEBUG (MainThread) [custom_components.tapo_control] Detected base_url schema: http
2024-09-16 12:02:32.275 DEBUG (MainThread) [custom_components.tapo_control] Detected base_url schema: http
2024-09-16 12:02:32.276 DEBUG (MainThread) [custom_components.tapo_control] Using HTTPS: False
2024-09-16 12:02:32.276 DEBUG (MainThread) [custom_components.tapo_control] Webhook enabled: True
2024-09-16 12:02:32.276 DEBUG (MainThread) [custom_components.tapo_control] Using Webhooks: True
2024-09-16 12:02:32.276 DEBUG (MainThread) [custom_components.tapo_control] Setting up events...
2024-09-16 12:02:32.276 DEBUG (MainThread) [custom_components.tapo_control] WSPullPointSupport: True
...
2024-09-16 12:02:36.893 DEBUG (MainThread) [custom_components.tapo_control] Creating binary sensor entity.
2024-09-16 12:02:36.897 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved (None)
Traceback (most recent call last):
  File "/config/custom_components/tapo_control/utils.py", line 1374, in update_listener
    await setupOnvif(hass, entry)
  File "/config/custom_components/tapo_control/utils.py", line 1431, in setupOnvif
    hass.data[DOMAIN][entry.entry_id]["eventsSetup"] = await setupEvents(
                                                       ^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/tapo_control/utils.py", line 1467, in setupEvents
    ].createBinarySensor()
      ^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/tapo_control/binary_sensor.py", line 188, in createBinarySensor
    for event in events.get_platform("binary_sensor")
                 ^^^^^^^^^^^^^^^^^^^
AttributeError: 'bool' object has no attribute 'get_platform'
```

### Device Firmware

1.1.17 build 240529 rel.57938n

### Integration Version

5.6.1

### Using stream component

Yes

### Does camera work via official integrations?

Yes

### Camera has all attributes filled out in developer tools

Yes

### HASS Environment

Home Assistant Green

### Search for similar issues

Yes

### Additional information

Cam IP: 192.168.1.190, Home Assistant IP: 192.168.1.2, local HTTP without TLS, on the same subnet

**Comment by tomasbedrich** [comment]
Only the official Tapo app + Home Assistant. In Home Assistant, there are two integrations interacting with the camera: [WebRTC](https://github.com/AlexxIT/WebRTC) and this integrations. The WebRTC integration is set up using `tapo://` protocol ([docs](https://github.com/AlexxIT/go2rtc?tab=readme-ov-file#source-tapo)).

**Comment by JurajNyiri** [comment]
I think this might be cause by the webrtc integration. I do not believe it is needed as long as you do not need 2 way talk, you can simply use a card something like this:

```
type: custom:webrtc-camera
intersection: 1
entity: camera.living_room_sd
background: true
digital_ptz:
  persist: false
ptz:
  service: button.press
  data_left:
    entity_id: button.living_room_move_left
  data_right:
    entity_id: button.living_room_move_right
  data_up:
    entity_id: button.living_room_move_up
  data_down:
    entity_id: button.living_room_move_down
shortcuts:
  - name: Privacy Mode
    icon: mdi:eye-outline
    service: switch.toggle
    service_data:
      entity_id: switch.living_room_privacy
  - name: Home
    icon: mdi:home
    service: script.set_living_room_camera_home
  - name: Home
    icon: mdi:palm-tree
    service: script.set_living_room_camera_away
style: >-
  .shortcuts {left: unset; top: 30px; left: 5px; display: flex; flex-direction:
  column; gap: 12px;}

```

**Comment by JurajNyiri** [comment]
Closing due to inactivity.
