### ISSUE TITLE
Issue with C500 v1.0 hw and 1.3.1 Sw

### ISSUE THREAD

**Issue by rlsm-sed** [JurajNyiri/HomeAssistant-Tapo-Control#711]
### Description

In a previous installation of HA to test, the siren and force alarm off and On was working.

Don't know why, impossible to put it back to work.

### Reproduction Steps

Just by using défaut butons 
![Screenshot_20241124_213124_Home Assistant](https://github.com/user-attachments/assets/8ed8fb6f-cc4f-432d-b97c-9dedf7457cf6)

### Expected behavior

Would like to have

Manual alarm start (Error: Parameter to get/do does not exist, Response: {"error_code": -40106} )
Manual alarm stop (Error: Parameter to get/do does not exist, Response: {"error_code": -40106})

Siren (Camera does not support trigering of siren error, not sure if this worked previously)

IDEA IS TO AUTOMATE ALL SIRENS GOIN ON IF ONE CAMERA DETECTS

### If applicable, add error logs.

Enregistreur: homeassistant.components.websocket_api.http.connection
Source: components/websocket_api/commands.py:245
intégration: Home Assistant WebSocket API (documentation, problèmes)
S'est produit pour la première fois: 18 novembre 2024 à 13:39:47 (24 occurrences)
Dernier enregistrement: 21:34:04

[140686077524672] Unexpected exception
[140685910091680] Unexpected exception
[140686347436816] Unexpected exception
[140685908802528] Unexpected exception
[140685920484464] Unexpected exception
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 245, in handle_call_service
    response = await hass.services.async_call(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2802, in async_call
    response_data = await coro
                    ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2845, in _execute_service
    return await target(service_call)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 1007, in entity_service_call
    single_response = await _handle_entity_call(
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 1079, in _handle_entity_call
    result = await task
             ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/button/__init__.py", line 132, in _async_press_action
    await self.async_press()
  File "/config/custom_components/tapo_control/button.py", line 121, in async_press
    await self._hass.async_add_executor_job(self._controller.startManualAlarm)
  File "/usr/local/lib/python3.12/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/pytapo/__init__.py", line 1714, in startManualAlarm
    return self.performRequest(
           ^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/pytapo/__init__.py", line 621, in performRequest
    raise Exception(
Exception: Error: Parameter to get/do does not exist, Response: {"error_code": -40106}

### Device Firmware

C500 by TP-Link HW version 1.0 SW 1.3.1 Build 240820 Rel.71705n

### Integration Version

5.8.0

### Using stream component

Yes

### Does camera work via official integrations?

Yes

### Camera has all attributes filled out in developer tools

Yes

### HASS Environment

Vmachine in synology

### Search for similar issues

Yes

### Additional information

 I can try or do tests if required

**Comment by JurajNyiri** [comment]
Unfortunately if an app can not trigger the siren manually niether can integration. There is no way to detect whether camera supports it or not.
