### ISSUE TITLE
Integration TAPO:Cameras Control cannot be loaded, shows error: Exception importing custom_components.tapo_control.config_flow

### ISSUE THREAD

**Issue by Buggykiter** [JurajNyiri/HomeAssistant-Tapo-Control#767]
### Description

Integration: Tapo:Cameras Control 6.0.1 has been added via HACS, but loading of Cameras Control is not possible. Always gives the error message: invalid config (see error log)

### Reproduction Steps

1. Add Tapo: Cameras Control via HACS
2. Restart Home Assistant
3. Add Cameras Control to Config

### Expected behavior

Start of Camera integration as it had work a year ago

### If applicable, add error logs.

Logger: homeassistant.setup
Source: setup.py:251 
First occurred: 15:29:54 (1 occurrences) 
Last logged: 15:29:54 
Setup failed for custom integration 'tapo_control': Unable to import component: Exception importing custom_components.tapo_control 
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/loader.py", line 822, in get_component
    ComponentProtocol, importlib.import_module(self.pkg_path)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 936, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1074, in get_code
  File "<frozen importlib._bootstrap_external>", line 1004, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/config/custom_components/tapo_control/__init__.py", line 961
    f"Media sync ignoring {searchResult[key]["date"]}. Media sync: {enableMediaSync}."
                                              ^^^^
SyntaxError: f-string: unmatched '['

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 251, in _async_setup_component
    component = integration.get_component()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 830, in get_component
    raise ImportError(f"Exception importing {self.pkg_path}") from err
ImportError: Exception importing custom_components.tapo_control

Logger: homeassistant.loader
Source: loader.py:822 
First occurred: 15:29:54 (1 occurrences) 
Last logged: 15:29:54 
Unexpected exception importing component custom_components.tapo_control 
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/loader.py", line 822, in get_component
    ComponentProtocol, importlib.import_module(self.pkg_path)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 936, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1074, in get_code
  File "<frozen importlib._bootstrap_external>", line 1004, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/config/custom_components/tapo_control/__init__.py", line 961
    f"Media sync ignoring {searchResult[key]["date"]}. Media sync: {enableMediaSync}."
                                              ^^^^
SyntaxError: f-string: unmatched '['

### Device Firmware

320WS von tp-link Firmware: 1.3.11 Build 231117 Rel.44732n(4555)

### Integration Version

HAOS 14

### Using stream component

Yes

### Does camera work via official integrations?

Yes

### Camera has all attributes filled out in developer tools

Yes

### HASS Environment

Homeassistant in VMware

### Search for similar issues

Yes

**Comment by JurajNyiri** [comment]
If using unsupported HA install method, python3.12 or python3.13 has to be used as that is what HA requires.

**Comment by Buggykiter** [comment]
I am using HA via official install method for 3 years now. Everything is running fine except TAPO cameras control. Where do I find which python version is used in my installation? In the logs it seems to be a syntax error ( f-string: unmatched '[').

**Comment by JurajNyiri** [comment]
From the logs provided:

```
File "/usr/local/lib/python3.11/importlib/init.py", line 126, in import_module
```

Python 3.11 has been dropped in April 2024.

![image](https://github.com/user-attachments/assets/b16344ac-2857-4997-a2da-c9a144e878bc)

**Comment by Buggykiter** [comment]
Thank you for this info. I have checked my versions. The HA core was outdated (version 2024.1.3). After manual update to core 2024.12.3 the camera control error was gone. Thanks for your help !

**Comment by JurajNyiri** [comment]
Thank you, I have modified hacs info file to ensure it cannot be installed on outdated HA versions before April going forwards.
