### ISSUE TITLE
Unable to connect to Tapo: Cameras Control controller: 'bool' object is not subscriptable

### ISSUE THREAD

**Issue by mmaelz** [JurajNyiri/HomeAssistant-Tapo-Control#86]
**Describe the bug**
Camera connection is not possible. Error message in logs is:

"Unable to connect to Tapo: Cameras Control controller: 'bool' object is not subscriptable"

**Log**
Logger: custom_components.tapo_control
Source: custom_components/tapo_control/__init__.py:243 
Integration: Tapo: Cameras Control (documentation, issues) 
First occurred: 21:16:16 (16 occurrences) 
Last logged: 21:35:30

Unable to connect to Tapo: Cameras Control controller: 'bool' object is not subscriptable

**Camera (please complete the following information):**
 - Device Model: C100
 - FW: 1.0.19 Build 210319 Real. 42963n(4555)

**Using stream component**
yes

**Camera works through onvif component OR different cameras work in general**
unknown

**Camera has all attributes filled out properly in developer tools**
I think so

**HASS Environment**
Home Assistant core on Ubuntu 20.04 LTS

**Additional context**
RTSP-Stream via VLC-Stream and same credentials works fine

**Comment by JurajNyiri** [comment]
Please post a full error from the error log with the stack trace.

**Comment by JurajNyiri** [comment]
Closing due to inactivity.

**Comment by raihatneloy** [comment]
Hi, 
I am facing the same issue. Each night, while the motion sensor is idle for around 3-4 hours, its not coming back. Then if I restart HASS, it becomes unavailable. Then I have to re-add the camera again. Thats very weird. I also couldn't debug the logs for onvif.

**Comment by JurajNyiri** [comment]
This issue is not about motion sensor. Are you seeing this error message?

**Comment by brunohoff** [comment]
Hello. I'm facing the same issue. Everything works on the C200 cameras, only the motion sensor gives the following error. I tried to reset the cameras and all 10 started to raise the same error. I'm suspecting that maybe is a network issue. There is a way to better debug the issue?

`2022-12-29 16:56:52.281 ERROR (MainThread) [custom_components.tapo_control] Unexpected error fetching Tapo resource status data: 'bool' object is not subscriptable
Traceback (most recent call last):
File "/srv/homeassistant/lib/python3.11/site-packages/homeassistant/helpers/update_coordinator.py", line 225, in _async_refresh
self.data = await self._async_update_data()
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/srv/homeassistant/lib/python3.11/site-packages/homeassistant/helpers/update_coordinator.py", line 181, in _async_update_data
return await self.update_method()
^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/home/homeassistant/.homeassistant/custom_components/tapo_control/__init__.py", line 203, in async_update_data
hass.data[DOMAIN][entry.entry_id]["eventsDevice"] = onvifDevice[
^^^^^^^^^^^^
TypeError: 'bool' object is not subscriptable`
